### ISSUE TITLE
[Bug] Grafana V 4.6.0-beta2 - Hover ToolTips Missing Values

### ISSUE THREAD

**Issue by gaetan29** [grafana/grafana#9614]
Hi
Here is my setup:

Grafana V 4.6.0-beta2
Data Source: InfluxDB
Grafana Docker Version on Synology NAS

Graph Panel
Mode= All Series
Stacked Value = Cumulative
Stack = On
Mode = Single
![grafana-01](https://user-images.githubusercontent.com/788375/31860694-50558b6a-b71e-11e7-9f93-517652e3819a.png)

Issue: Value are missing on the hover tooltip

Thanks

**Comment by torkelo** [comment]
Strange, I am unable to replicate this. Can you show what data is returned from your query?

**Comment by torkelo** [comment]
sure your not hovering over a null value?

**Comment by gaetan29** [comment]
Not over a null value ...
![grafana-03](https://user-images.githubusercontent.com/788375/31861827-ea5ae024-b733-11e7-9458-f481fa1d6651.png)


{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "http://80.168.187.108:32799/query",
    "params": {
      "db": "influxdb_frtmap01",
      "q": "SELECT mode(\"value\") FROM \"FRTMAP_Today_Live_JC_DEI\" WHERE time >= now() - 90d GROUP BY time(1d) fill(null);SELECT mode(\"value\") FROM \"FRTMAP_Today_Live_JC_DEX\" WHERE time >= now() - 90d GROUP BY time(1d) fill(null)",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms"
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "FRTMAP_Today_Live_JC_DEI",
            "columns": [
              "time",
              "mode"
            ],
            "values": [
              [
                1500854400000,
                "11"
              ],
              [
                1500940800000,
                "29"
              ],
              [
                1501027200000,
                "19"
              ],
              [
                1501113600000,
                "24"
              ],
              [
                1501200000000,
                "28"
              ],
              [
                1501286400000,
                "0"
              ],
              [
                1501372800000,
                "0"
              ],
              [
                1501459200000,
                "23"
              ],
              [
                1501545600000,
                "24"
              ],
              [
                1501632000000,
                "20"
              ],
              [
                1501718400000,
                "15"
              ],
              [
                1501804800000,
                "22"
              ],
              [
                1501891200000,
                "0"
              ],
              [
                1501977600000,
                "0"
              ],
              [
                1502064000000,
                "24"
              ],
              [
                1502150400000,
                "22"
              ],
              [
                1502236800000,
                "11"
              ],
              [
                1502323200000,
                "20"
              ],
              [
                1502409600000,
                "19"
              ],
              [
                1502496000000,
                "0"
              ],
              [
                1502582400000,
                "0"
              ],
              [
                1502668800000,
                "21"
              ],
              [
                1502755200000,
                "19"
              ],
              [
                1502841600000,
                "12"
              ],
              [
                1502928000000,
                "21"
              ],
              [
                1503014400000,
                "32"
              ],
              [
                1503100800000,
                "0"
              ],
              [
                1503187200000,
                "0"
              ],
              [
                1503273600000,
                "18"
              ],
              [
                1503360000000,
                "27"
              ],
              [
                1503446400000,
                "13"
              ],
              [
                1503532800000,
                "19"
              ],
              [
                1503619200000,
                "18"
              ],
              [
                1503705600000,
                "0"
              ],
              [
                1503792000000,
                "0"
              ],
              [
                1503878400000,
                "21"
              ],
              [
                1503964800000,
                "24"
              ],
              [
                1504051200000,
                "6"
              ],
              [
                1504137600000,
                "22"
              ],
              [
                1504224000000,
                "15"
              ],
              [
                1504310400000,
                "0"
              ],
              [
                1504396800000,
                "0"
              ],
              [
                1504483200000,
                "29"
              ],
              [
                1504569600000,
                "28"
              ],
              [
                1504656000000,
                "21"
              ],
              [
                1504742400000,
                "12"
              ],
              [
                1504828800000,
                "18"
              ],
              [
                1504915200000,
                "0"
              ],
              [
                1505001600000,
                "0"
              ],
              [
                1505088000000,
                "32"
              ],
              [
                1505174400000,
                "12"
              ],
              [
                1505260800000,
                "8"
              ],
              [
                1505347200000,
                "13"
              ],
              [
                1505433600000,
                "20"
              ],
              [
                1505520000000,
                "0"
              ],
              [
                1505606400000,
                "0"
              ],
              [
                1505692800000,
                "27"
              ],
              [
                1505779200000,
                "26"
              ],
              [
                1505865600000,
                "15"
              ],
              [
                1505952000000,
                "22"
              ],
              [
                1506038400000,
                "17"
              ],
              [
                1506124800000,
                "0"
              ],
              [
                1506211200000,
                "0"
              ],
              [
                1506297600000,
                "23"
              ],
              [
                1506384000000,
                "25"
              ],
              [
                1506470400000,
                "14"
              ],
              [
                1506556800000,
                "17"
              ],
              [
                1506643200000,
                "18"
              ],
              [
                1506729600000,
                "0"
              ],
              [
                1506816000000,
                "0"
              ],
              [
                1506902400000,
                "15"
              ],
              [
                1506988800000,
                "5"
              ],
              [
                1507075200000,
                "26"
              ],
              [
                1507161600000,
                "12"
              ],
              [
                1507248000000,
                "21"
              ],
              [
                1507334400000,
                "0"
              ],
              [
                1507420800000,
                "0"
              ],
              [
                1507507200000,
                "28"
              ],
              [
                1507593600000,
                "25"
              ],
              [
                1507680000000,
                "11"
              ],
              [
                1507766400000,
                "16"
              ],
              [
                1507852800000,
                "14"
              ],
              [
                1507939200000,
                "0"
              ],
              [
                1508025600000,
                "0"
              ],
              [
                1508112000000,
                "12"
              ],
              [
                1508198400000,
                "26"
              ],
              [
                1508284800000,
                "15"
              ],
              [
                1508371200000,
                "13"
              ],
              [
                1508457600000,
                "17"
              ],
              [
                1508544000000,
                "0"
              ],
              [
                1508630400000,
                null
              ]
            ]
          }
        ]
      },
      {
        "statement_id": 1,
        "series": [
          {
            "name": "FRTMAP_Today_Live_JC_DEX",
            "columns": [
              "time",
              "mode"
            ],
            "values": [
              [
                1500854400000,
                "12"
              ],
              [
                1500940800000,
                "14"
              ],
              [
                1501027200000,
                "15"
              ],
              [
                1501113600000,
                "19"
              ],
              [
                1501200000000,
                "21"
              ],
              [
                1501286400000,
                "1"
              ],
              [
                1501372800000,
                "0"
              ],
              [
                1501459200000,
                "9"
              ],
              [
                1501545600000,
                "20"
              ],
              [
                1501632000000,
                "14"
              ],
              [
                1501718400000,
                "15"
              ],
              [
                1501804800000,
                "22"
              ],
              [
                1501891200000,
                "0"
              ],
              [
                1501977600000,
                "0"
              ],
              [
                1502064000000,
                "15"
              ],
              [
                1502150400000,
                "13"
              ],
              [
                1502236800000,
                "8"
              ],
              [
                1502323200000,
                "14"
              ],
              [
                1502409600000,
                "21"
              ],
              [
                1502496000000,
                "0"
              ],
              [
                1502582400000,
                "0"
              ],
              [
                1502668800000,
                "16"
              ],
              [
                1502755200000,
                "12"
              ],
              [
                1502841600000,
                "10"
              ],
              [
                1502928000000,
                "13"
              ],
              [
                1503014400000,
                "22"
              ],
              [
                1503100800000,
                "0"
              ],
              [
                1503187200000,
                "0"
              ],
              [
                1503273600000,
                "12"
              ],
              [
                1503360000000,
                "19"
              ],
              [
                1503446400000,
                "15"
              ],
              [
                1503532800000,
                "20"
              ],
              [
                1503619200000,
                "24"
              ],
              [
                1503705600000,
                "0"
              ],
              [
                1503792000000,
                "0"
              ],
              [
                1503878400000,
                "4"
              ],
              [
                1503964800000,
                "26"
              ],
              [
                1504051200000,
                "14"
              ],
              [
                1504137600000,
                "13"
              ],
              [
                1504224000000,
                "23"
              ],
              [
                1504310400000,
                "0"
              ],
              [
                1504396800000,
                "0"
              ],
              [
                1504483200000,
                "16"
              ],
              [
                1504569600000,
                "24"
              ],
              [
                1504656000000,
                "12"
              ],
              [
                1504742400000,
                "16"
              ],
              [
                1504828800000,
                "17"
              ],
              [
                1504915200000,
                "1"
              ],
              [
                1505001600000,
                "0"
              ],
              [
                1505088000000,
                "6"
              ],
              [
                1505174400000,
                "22"
              ],
              [
                1505260800000,
                "11"
              ],
              [
                1505347200000,
                "18"
              ],
              [
                1505433600000,
                "15"
              ],
              [
                1505520000000,
                "0"
              ],
              [
                1505606400000,
                "0"
              ],
              [
                1505692800000,
                "12"
              ],
              [
                1505779200000,
                "19"
              ],
              [
                1505865600000,
                "10"
              ],
              [
                1505952000000,
                "16"
              ],
              [
                1506038400000,
                "23"
              ],
              [
                1506124800000,
                "1"
              ],
              [
                1506211200000,
                "0"
              ],
              [
                1506297600000,
                "13"
              ],
              [
                1506384000000,
                "14"
              ],
              [
                1506470400000,
                "18"
              ],
              [
                1506556800000,
                "17"
              ],
              [
                1506643200000,
                "20"
              ],
              [
                1506729600000,
                "0"
              ],
              [
                1506816000000,
                "4"
              ],
              [
                1506902400000,
                "16"
              ],
              [
                1506988800000,
                "16"
              ],
              [
                1507075200000,
                "5"
              ],
              [
                1507161600000,
                "11"
              ],
              [
                1507248000000,
                "22"
              ],
              [
                1507334400000,
                "0"
              ],
              [
                1507420800000,
                "0"
              ],
              [
                1507507200000,
                "15"
              ],
              [
                1507593600000,
                "12"
              ],
              [
                1507680000000,
                "16"
              ],
              [
                1507766400000,
                "11"
              ],
              [
                1507852800000,
                "17"
              ],
              [
                1507939200000,
                "0"
              ],
              [
                1508025600000,
                "0"
              ],
              [
                1508112000000,
                "9"
              ],
              [
                1508198400000,
                "20"
              ],
              [
                1508284800000,
                "7"
              ],
              [
                1508371200000,
                "18"
              ],
              [
                1508457600000,
                "10"
              ],
              [
                1508544000000,
                "1"
              ],
              [
                1508630400000,
                null
              ]
            ]
          }
        ]
      }
    ]
  }
}

**Comment by torkelo** [comment]
your values are strings not numbers. Make sure when you write data to InfluxDB that your data is written as number as not strings.

**Comment by gaetan29** [comment]
How can graphs been displayed if values are strings and not numbers ?
Regards

**Comment by torkelo** [comment]
the graph component is a bit too forgiving. But lots of other stuff will break (legend values, etc)

**Comment by gaetan29** [comment]
;-)
Ok, it does work indeed with the latest release when storing correct values ;-)

Thanks for this great system and good support.
Regards
