### ISSUE TITLE
[Bug] tooltips not escaping <> characters

### ISSUE THREAD

**Issue by bobbwest** [grafana/grafana#9615]
Grafana: 4.5.2
Data source: InfluxDB
OS: Ubuntu 16.04.3  

![image](https://user-images.githubusercontent.com/16171945/31873544-8d4292f6-b80f-11e7-9d30-c2cca54310d9.png)

It seems that the tooltips are not escaping HTML in the labels, but the graph legends are escaping HTML.

I have noticed this on the hover tooltips on the graphs, as well as the selection dialogs for templating and the data source selection dialogs when editing the graph metrics (e.g. when tags in the data source contain <> characters).  

Expected results:
(1) the hover tooltips should match the graph legend
(2) InfluxDB data sources containing measurements with tags that contain <> characters should be displayed correctly in selection dialogs

**Comment by bergquist** [comment]
the tooltip should use angular sanitize function to escape content.
