### ISSUE TITLE
Singlestat: null point handling and value to text mappings removed

### ISSUE THREAD

**Issue by felixPG** [grafana/grafana#9616]
Hi:

Im looking for a way to map in singlestat null values or NON values to text, or with 0. Reading that the option was added in https://github.com/grafana/grafana/issues/1130 but appear that the option was removed in recent versions. So, how I can map null, non values, etc, as text or numbers??? In my dashboard I have "no value" text when null or non values are returned by a query!!!

Regards

**Comment by torkelo** [comment]
If I have a query that return null values I can mapp that to a text in the Value mappings tab

![image](https://user-images.githubusercontent.com/10999/31883350-ea5767ee-b7e9-11e7-8860-0072b01dedb8.png)

**Comment by felixPG** [comment]
Thank you, working like a charm!
