### ISSUE TITLE
Stateful URL's for dashboards

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#9617]
Updating a dashboard in Grafana should update the URL to include that change as an override. When an user shares a dashboard he/she should be able to expect the receiver to see the dashboard the same way without saving the dashboard. This could be used to test/improve dashboards easier. 

When changes for a dashboard is saved. All those query parameter that override the dashboard.json should be removed.

**Comment by lukaszgryglicki** [comment]
Any updates here?

**Comment by bergquist** [comment]
@lukaszgryglicki no real updates yet. But I've been thinking about this feature for quite a while and I like it a lot. Still too early to say when we have time to look into it more or even start developing it. Hopefully, we will be able to work on this in 5.1/5.2 

It's a powerful feature that could enable lots of great workflows but there are also a bunch of edge cases that we need to handle to make this good enough to release to all our users.
