### ISSUE TITLE
[feature request] text alerting

### ISSUE THREAD

**Issue by hah2930** [grafana/grafana#9623]
Hello, 

My apologies if this isn't categorized correctly. I have configured text and email alerts with Grafana. The issue that I am having is with text alerts.  Email alerts are nice and readable but the text alerts are very long (10 messages +) and do not provide any useful data. With the text message alert, the graph image is converted into text instead. My question is, Is there a way to remove the graph from the alerts altogether? 

Thanks in advance

**Comment by bergquist** [comment]
What do you mean by text alerting? webhook?

You can turn of images from alert notifications by unchecking the `include image` checkbox
![image](https://user-images.githubusercontent.com/618863/31926944-05b75ca8-b892-11e7-99a8-fcbc52e8d097.png)

**Comment by hah2930** [comment]
Thank you  for the response. When the alert is triggered, I am sending them to the email address as well as phone numbers, such as, 123456789@txt.att.net  or 123456789@vtext.com. 

I receive the text messages on the phone  perfectly fine but the problem is with the content of the text message.  First of all, the image is not displayed and instead there are various numbers which doesn’t indicate the what the alert is all about.  

The version of grafana I am using does not have the option to remove the image from the alerts.  Is that something that was added to a later release? I am using v4.1.2

Thanks again!

**Comment by hah2930** [comment]
![2da07122-1a39-466b-97f2-220219324041](https://user-images.githubusercontent.com/26228239/31949695-f5ba1fe6-b8a7-11e7-8355-cfe06d68e412.jpeg)

**Comment by torkelo** [comment]
closing as it's the same as this feature request, https://github.com/grafana/grafana/issues/11436
