### ISSUE TITLE
[Bug] Notification to hipchat doesn't send when room id have # in name

### ISSUE THREAD

**Issue by xelite** [grafana/grafana#9632]
I've got configured notification channel to hipchat room. My room is called `#notifications`. When I set room id to `#notifications` and try send test notification got error (in grafana.log): `logger=alerting.notifier.hipchat error="Webhook response status 405 Method Not Allowed"`

When change Room ID to `%23notifications` or real numeric ID everything works.

**Comment by bergquist** [comment]
What version of Grafana are you using?

**Comment by xelite** [comment]
Grafana 4.6.0-beta2

**Comment by xelite** [comment]
Hipchat is dead.
