### ISSUE TITLE
Grafana Alerting: Cannot add alert rule to a provisioned alert group

### ISSUE THREAD

**Issue by ryan-grafana** [grafana/grafana#96320]
### What happened?

A customer has a provisioned alert group that they are trying to add a new alert rule to using TF. They are getting an error that they cannot add the rule as it's a provisioned or "locked down rule". We should ensure users can use TF to add rules to existing provisioned alert groups. 

### What did you expect to happen?

As TF is a provisioning / as code method, the user should be able to add a new alert rule into a provisioned alert group via terraform

### Did this work before?

unsure if this ever worked.

### How do we reproduce it?

1. make an alert group with an alert through the prov API
2. Try and add a new rule to that group via TF
3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.4 - Cloud
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

**Comment by aifraenkel** [comment]
Related: https://github.com/grafana/grafana/issues/80323

**Comment by aifraenkel** [comment]
@soniaAguilarPeiron could you please describe the approach to solve this problem in the description once that is clear?

**Comment by soniaAguilarPeiron** [comment]
The approach is to allow the user to select the provisioned group by providing an option to export a new alert rule without saving it. This way, the user can obtain the Terraform definition of the group, including the new rule.
