### ISSUE TITLE
[Bug] Cannot import dashboards from json file greather than 128KB

### ISSUE THREAD

**Issue by pozda2** [grafana/grafana#9635]
Hi

- Grafana version: 4.5.2
- Datasource: InfluxDB 1.3.5
- OS: CentOS Linux release 7.4.1708 (Core)
- HTTP: httpd-2.4.6-67

I have large dashboard defined via JSON. I use curl to import this file to grafana.
curl -H "Content-Type: application/json" -k -s -X POST -u user:pass -d '...' http://localhost/grafana/api/dashboards/db

If the file is large approximately then 128KB, the import failed. If reduce file size for instance by removing space, import works.

The limit could be in grafana or apache server.

Martin

**Comment by bergquist** [comment]
Could you verify that your problem lies with Grafana by posting directly to Grafana instead of apache?

**Comment by torkelo** [comment]
this mush be an issue with your apache setup

**Comment by pozda2** [comment]
I use Apache with proxy only for an authentication. But I tried the importing directly against Grafana with the same result. 

The importing of the following dashboard in the valid JSON failed. 
https://drive.google.com/file/d/0B14HcbvmTCZ4T1pJb19IY2JYWFk/view?usp=sharing
If I stripped some white spaces, import works.

**Comment by daniellee** [comment]
Looks like invalid Dashboard json - it is wrapped with an extra field: `{ "dashboard" :`  

How are you generating this?

**Comment by pozda2** [comment]
It's generated according documentation http://docs.grafana.org/http_api/dashboard/

JSON exported via web interface must be wrapped 

{
  "dashboard": { 
  },
  "overwrite": false
}

And if I stripped white spaces from my JSON it works.

**Comment by daniellee** [comment]
@pozda2 yes, you're right (missed the part that the import was via the API) - I was importing via the UI. Just tried with curl on my local grafana:

```bash
curl -X POST --insecure -H "Content-Type: application/json" --data-binary @/path/to/file.json http://admin:admin@localhost:3000/api/dashboards/db
```

and I could import it no problem.

> But I tried the importing directly against Grafana with the same result.

No firewalls, VPNs or proxies in between?

**Comment by pozda2** [comment]
It could be limit of curl. I passed degenerated json to curl directly without file. Now I saved JSON to file and call curl with --data-binary @/path/to/file.json and it works.

Thanks, for help
