### ISSUE TITLE
Product Area: Short description of bug

### ISSUE THREAD

**Issue by ArunMagi** [grafana/grafana#96375]
### What happened?

for me not working

### What did you expect to happen?

anguler ui not working

### Did this work before?

for me not working

### How do we reproduce it?

1.for me not working
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by leeoniya** [comment]
https://grafana.com/docs/grafana/latest/developers/angular_deprecation/
