### ISSUE TITLE
[Bug] Annotations: regions-events not working on firefox 56

### ISSUE THREAD

**Issue by Farfaday** [grafana/grafana#9638]
Hi,

- What Grafana version are you using?
v4.6.0-beta3

- What OS are you running grafana on?
Archlinux

- Issue:
Adding-regions-events (http://docs.grafana.org/reference/annotations/#adding-regions-events) works with chrome/chromium, but not with firefox 56.

Thanks!

**Comment by wjoelcognite** [comment]
I'm having the same issue with v4.6.0-beta3, Firefox Nightly (58.0a1 2017-10-08) on Ubuntu 17.04. Works perfectly using Chromium.

**Comment by volter** [comment]
It doesn't work in FF 54 either.

**Comment by nicolargo** [comment]
Do not work on Firefox 56.0 (64-bit) / Ubuntu 16.04.

**Comment by danpalmer** [comment]
I can reproduce this on macOS too.
