### ISSUE TITLE
Bug: Display issue - X-Axis series mode, names overlap

### ISSUE THREAD

**Issue by 6y5t4r** [grafana/grafana#9647]
Steps to reproduce:
- Open http://play.grafana.org/
- Edit the 'server requests' panel
- Axes: change X-Axis mode to "series". All looks fine
- Metrics: remove the 'AliasByNode' element.
X-Axis names becomes too big and overlap each other.

**Comment by torkelo** [comment]
Yes, that is why it's good to keep the series names short.

Closing this there already is a feature request to tillt the x axis legend ticks which would fit more and longer x axis ticks
