### ISSUE TITLE
[Feat Req] Use Azure MySQL for sessions & datasource

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#9649]
Similar to #8618. 

With the fix for #8618, I am able to use Azure MySQL as a database, but if I try to do the same for "sessions", or if I try to point to that same database as a datasource, I get the "this user requires mysql native password authentication." error.

Please include this information:
- What Grafana version are you using? 4.5.2
- What datasource are you using? MySQL
- What OS are you running grafana on? Windows
- What did you do? I attempted to configure Grafana to use an Azure MySQL database for session storage.
- What was the expected result? That the MySQL database would work.
- What happened instead? Grafana server fails to start, outputting: "this user requires mysql native password authentication."

**Comment by funrockstefan** [comment]
Any update for this bug?

**Comment by tibbing** [comment]
Having the same issue, MySQL for Azure is not working in Grafana 4.5.2. Is this something planned to be fixed? @torkelo

**Comment by daniellee** [comment]
Does it work if you add allowNativePasswords to the connection string in your config file?

```
[session]
provider = mysql
provider_config = user:password@tcp(127.0.0.1:3306)/grafana?allowNativePasswords=true
```

**Comment by tibbing** [comment]
@daniellee We are using the offical Grafana template in Azure marketplace. As I understand it session is not the same thing as data source? We are getting the error while trying to add a Azure MySQL data source, other MySQL databases and data sources is working fine.

**Comment by daniellee** [comment]
@tibbing No, it is not the same - it is actually much easier. In the plugin, the querystring is built up using the fields specified on the data source config page - you do not have access to the raw connection string. In this case, you can enter the raw connection string and just add `allowNativePasswords` to it.  

My example above is from the Grafana config file and the `provider_config` variable is the connection string for the session database. Have you tested it?

**Comment by tibbing** [comment]
@daniellee I'm not sure I'm following now. We are happy with storing grafana sessions on file, we don't want to change that to MySQL. The issue we have is with adding a MySQL data source. Or do you mean we can somehow specify the raw connection string for the data source?

**Comment by daniellee** [comment]
@tibbing your comment said "Having the same issue"  and as the issue seemed to be mostly about the session table - I assumed that was what you were asking.

I can fix the data source but it will be a while before it is released. We are preparing for a major release and I don't think we will be doing any smaller releases for a while.

**Comment by tibbing** [comment]
@daniellee Ah okay, sorry for the confusion. I read the original issue as concerning both sessions and data sources. Anyway, I guess we can use a non-azure db for now but it would be great if this issue would be addressed in a later release. Thank you for your help!

**Comment by yesoreyeram** [comment]
@tibbing , @bergquist  @daniellee , we are still having the issue using azure mysql as session store. 

My config looks like

```
[session]
provider=mysql
provide_config=grafanaadmin@mygrafanainstancename:mbK9gtJIrniAuPvM@tcp(mygrafanainstancename.mysql.database.azure.com:3306)/grafanasessionpoc?allowNativePasswords=true
cookie_name=grafana_sess_dev
cookie_secure=false
session_life_time=86400
gc_interval_time=86400
```

I am running grafana from my azure VM and it has following azure mysql settings; Grafana v4.5.2

![image](https://user-images.githubusercontent.com/153843/37968028-f41904f4-31c4-11e8-9565-8e3ac191ac21.png)


![image](https://user-images.githubusercontent.com/153843/37967951-c07ce6ec-31c4-11e8-91a4-6cb87dce3783.png)

and the error I am getting is

```
panic: invalid DSN: missing the slash separating the database name

goroutine 1 [running]:
github.com/grafana/grafana/pkg/middleware.Sessioner(0x1bacd40, 0x108c740, 0x12786f0)
	/go/src/github.com/grafana/grafana/pkg/middleware/session.go:71 +0x2d5
github.com/grafana/grafana/pkg/api.(*HttpServer).newMacaron(0xc4202b0a00, 0x40)
	/go/src/github.com/grafana/grafana/pkg/api/http_server.go:172 +0x6ec
github.com/grafana/grafana/pkg/api.(*HttpServer).Start(0xc4202b0a00, 0x7f8a4b7421b0, 0xc4201e1640, 0x120b909, 0x7)
	/go/src/github.com/grafana/grafana/pkg/api/http_server.go:53 +0x94
main.(*GrafanaServerImpl).startHttpServer(0xc4201e16c0)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:102 +0x65
main.(*GrafanaServerImpl).Start(0xc4201e16c0)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:80 +0x2c2
main.main()
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:84 +0x1bb
```

**Whereas; with similar azure mysql database, i can use it as grafana database provider but not session provider. Could someone help?**

**Comment by yesoreyeram** [comment]
my user name contains "@" symbol. Is that breaking the connection string ? ( User name supplied by azure )

`grafanaadmin@mygrafanainstancename`

**Comment by balaby25** [comment]
hi,
i am using mysql 8.0.4. grafana mysql datasource  . 
CREATE USER 'grafRead' IDENTIFIED WITH mysql_native_password BY  'passwd'; and gave privs.
test datasource gives "this user requires mysql native password authentication.".
is there any other step to do before trying to add a mysql datasource? 
Bala.

**Comment by paulstaffs** [comment]
Using a database for sessions isn't really needed anymore thanks to the new token support in v6, but for anyone else still struggling with this I noticed today there is a Bitnami deployment of grafana that includes Azure maraidb support.

It seems the solution is simply to quote the provider string like this:
`provider_config="USER@HOST:PASSWORD@tcp(HOST.mariadb.database.azure.com:3306)/DBNAME?tls=skip-verify"`

I have tested with Azure MySQL v5.7 and grafana v5.4.2 and it worked for me.
