### ISSUE TITLE
[bug?] nested template usage as title, prometheusdb

### ISSUE THREAD

**Issue by cchance27** [grafana/grafana#9650]
Ok i'm not sure if this is a big or if i'm doing something wrong. 

I've got stats like the following in my prometheus db
sysName{instance="172.16.1.72",job="c450",sysName="SX450-02"} | 1
probe_duration_seconds{instance="172.16.1.72",job="icmp"} | 0.001350519

I'm trying to get the singlestat to show the ping times, but with the title of each graph as the sysName{sysName} attribute

I've got the following template variables...
$IP | label_values(probe_success, instance) | Include All Option enabled
$Name | label_values(sysName{instance=~'$IP'}, sysName)

I've got it repeating on IP, with title set to [[Name]] and the singlestat set to probe_duration_seconds{instance=~"$IP"}*1000

The issue is the graphs create correctly, they all show the correct times, the titles however all all the same (basically showing whatever happens to be the first entry in the Name template drop down.

Is their a way to fix this or is it a bug, i mean it would be cool if i could just use the label_values call as the value of the title for the panel but that doesn't seem to be an option....

**Comment by torkelo** [comment]
Your repeating over IP, only IP will be different for each panel.

**Comment by cchance27** [comment]
so wait how are you supposed to handle the above scenario if it's not a bug?

How do you handle nested template variables with a repeating dashboard? Especially if label_values queries aren't allowed in title fields?

**Comment by torkelo** [comment]
Panel repeats do not support nested variables the way you want to. The nested variable will not be updated for each panel repeat only the variable you want to repeat by. 

For more complex scenarios we recommend you build your dashboard programmatically and use the HTTP api to save it.
