### ISSUE TITLE
DashBoards: Span detail of Tempo  is not display normally when Span name is too long.

### ISSUE THREAD

**Issue by shalk** [grafana/grafana#96519]
### What happened?

when span name is long , explore of tempo can not display normally.

![Image](https://github.com/user-attachments/assets/6e4d02aa-39f5-49cb-a704-8515935505cc)

### What did you expect to happen?

when span name is long , explore of tempo can display normally.

### Did this work before?

no.

### How do we reproduce it?

1. setup a tempo
2. setup a grafana
3. grafana add tempo datasource
4. send a span with long span name. k6 or tracegen can be used.

### Environment (with versions)?

Grafana: 11.0
OS: mac os 14.1
Browser: chrome 130.0.6723.117

### Grafana platform?

None

**Comment by grafakus** [comment]
Hi @shalk! Thank you for reporting the bug.
Indeed in case of a long path name, the browser should also be able to wrap or to crop the name and add ellipsis.
