### ISSUE TITLE
Dashboard: "last 24h view" is constantly flickering

### ISSUE THREAD

**Issue by LFrank2021** [grafana/grafana#96547]
### What happened?

It seems since the update to grafana-enterprise 11.3 (2024-10-24 00:40:14) the any dashboard with the 'last 24h' view is constantly flickering for the x-axis.
One fraction of a second it shows the date and hour then, for the remainder of the second, just the hour.

### What did you expect to happen?

The dashboard x-axis should not flicker and show the past 24 hours.

### Did this work before?

I cannot be 100% sure but it worked with grafana-enterprise 11.2 and prior.

### How do we reproduce it?

1. Update to grafana-enterprise 11.3 (most likely without following the additional instructions, if any) 
`/usr/bin/zypper --quiet --non-interactive --xmlout update --type package --auto-agree-with-licenses --no-recommends`
2. Go to any dashboard and selevt the 'last 24h' filter
3. move the cursor away from the panels, as a cursor inside the panels stops the flickering (at least sometimes)

### Environment (with versions)?

Grafana: enterprise 11.3
OS: openSUSE Leap 15.6
Browser: Mozilla FF (132.0.2 64-bit) and Chrome (126.0.6478.127)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by LFrank2021** [comment]
Update 1
In fact it is not for all Dashboards.
Rather with one I created myself and where I set the option "Refresh live dashboards".
Once this option is set the flickering starts.

**Comment by kbrint** [comment]
I can confirm that the bug IS present in 11.3.0, and IS NOT present in 11.2.0.

I agree with @LFrank2021 that it only appears to affect dashboards with "Refresh live dashboards" is enabled.

This annoys me enough that I bisected it.  As far as I can tell, the commit that introduced this behavior is: 7bca69849f08ac9d0ea96fe04016a11420f3acf3

**Comment by kbrint** [comment]
This is the behavior in question: https://github.com/user-attachments/assets/b9441bfd-21ae-4671-acf7-eafe7e891ac3

**Comment by PetrMa** [comment]
I have the same issue. Change &from=now-24h or &from=now-1d to &from=now-25h solve the issue.
So finally there is some specific issue only if parameter from= has value 24h or 1d

**Comment by kbrint** [comment]
Re @PetrMa 's comment, it's not necessary to change the range by a whole hour.  Even one second appears to eliminate the flicker.

* `now-86401s` (24h+1sec) consistently shows the date.  There's no flicker
* `now-86399s` (24h-1sec) consistently does not show the date.  There's no flicker.

I suspect there's a `>=` where a `>` belongs, or vice versa.

**Comment by weichenb** [comment]
Can confirm th issue still with 11.3.1https://github.com/user-attachments/assets/f6ea6e8e-8f0d-45ab-81ea-b426554e327f

**Comment by kbrint** [comment]
Adding `DISABLE_SCENES=true` to the environment eliminate this bug, further suggesting that 7bca69849f08ac9d0ea96fe04016a11420f3acf3 introduced the flicker.

**Comment by weichenb** [comment]
@kbrint : This mornig you posted a message that "Adding DISABLE_SCENES=true to the environment eliminate this bug".
Having added this configuration to my environment, the issue is still present.

**Comment by kbrint** [comment]
> [@kbrint](https://github.com/kbrint) : This mornig you posted a message that "Adding DISABLE_SCENES=true to the environment eliminate this bug". Having added this configuration to my environment, the issue is still present.

I removed that post because it turned out to be untrue.

**Comment by weichenb** [comment]
> I removed that post because it turned out to be untrue.

@kbrint : True is that on my platform with environment (GF-variables and GF-environment-settings- see screenshots) issue is still present

![Image](https://github.com/user-attachments/assets/7658f431-597a-46d4-928a-fbe9a8d5cbff)
![Image](https://github.com/user-attachments/assets/e8ff8aeb-10fa-4b67-bf03-a706c40ca586)

Video:
https://github.com/user-attachments/assets/80d4f1c0-be64-4dc9-a5e0-e28a911c45c2

**Comment by oscarkilhed** [comment]
A temporary workaround for this until we can get the issue fixed is to set the `Now delay` dashboard setting to 1s

![Image](https://github.com/user-attachments/assets/86115b3f-bb7a-497f-8d7f-440e5cd5ee39)
