### ISSUE TITLE
Alternative to [dashboard.json] & document breaking change

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9654]
[dashboard.json] option was removed in v5. Implement alternative or document change or how wizzy can be used to solve the same problem.

**Comment by tomwilkie** [comment]
Out of interest, why was the [dashboard.json] removed?

To kick of the discussion: we use jsonnet to generate out dashboard json and load it into a Kubernetes config map, which then gets mounted into the container as a series of files in a directory.  I'd really like to see support from this way of working, as it means we can use upstream Grafana docker images.  The current [dashboard.json] works quite well (modulo the hidden directories), but equally if I needed to generate a yaml index of all the dashboards that too would be possible.  I do really want dynamic reloading of thiss, as I don't want to have to restart my Grafana every time I add a new dashboard.

**Comment by torkelo** [comment]
[dashboard.json] feature is problematic as the dashboards are not loaded into the database but instead loaded on the fly from disk (or an in-memory cache). The problem is that users want these dashboards to be included in search which complicated search a lot as it needs to search DB and the dashboard.json in memory cache. The dashboard.json dashboards have no database id so cannot be starred or flagged as home dashboard which makes them less useful, since they have no id you wont be able to assign permissions on them (feature upcoming in v5)

We want to replace this feature with something that syncs the json file dashboards to the database (so they appear in search as regular dashboards), and you will have options to make these dashboards read only or prompt a warning when someone tries to save them.

**Comment by daniellee** [comment]
It is still very early but this might be of interest to you in the future - a jsonnet lib for Grafana: https://github.com/grafana/grafonnet-lib

**Comment by tomwilkie** [comment]
Thanks for the background @torkelo!  Will this be ready for v5?  Will the dashboard json format stay the same?  

> It is still very early but this might be of interest to you in the future - a jsonnet lib for Grafana: https://github.com/grafana/grafonnet-lib

@daniellee I have one of them too!  An old version is here: https://github.com/tomwilkie/ksonnet-prometheus/blob/master/grafana.jsonnet but I'm about to update it and move it.  The main enhancements I've made are things like auto-ID generation for panels and automatic distribution of panels within rows.  Would these kind of feature be of interest to you in that library?

**Comment by torkelo** [comment]
the dashboard schema is largely the beside rows and panel layout. All panels now live in a single panel array and their position is determined by a gridPos property {x, y, width, height}  (all in grid coordinates not pixels)

**Comment by bergquist** [comment]
@tomwilkie both auto-id generation and automatic distribution sound interesting. Could you create two PR's for that on https://github.com/grafana/grafonnet-lib ? Would be awesome. 

We are not sure if dashboard.json will be able to look the same. We have to introduce some new optional properties to make it work with organizations and dashboard folders. If we introduce any breaking it should be fairly easy to adopt current dashboards/provisioning scripts.

**Comment by bergquist** [comment]
Created a 'mother' issue for this issue. https://github.com/grafana/grafana/issues/9957

**Comment by bergquist** [comment]
The goal for this issue is to support:

```yaml
- name: 'default'
  org_id: 1
  folder: ''
  type: file
  options:
    folder: /var/lib/grafana/dashboards
```
