### ISSUE TITLE
Rule Group Configuration: query_offset field not found

### ISSUE THREAD

**Issue by ankense-cariad** [grafana/grafana#96572]
### What happened?

We are trying to use the Mimir field `query_offset` in a rule group configuration. Per the [Mimir documentation](https://github.com/grafana/mimir/blob/6ca9c52b6e89a515a6c403126b103cfe537ec4f2/docs/sources/mimir/release-notes/v2.13.md?plain=1#L70) this field has been available since version 2.13. However, when the rule group is deployed to Grafana, we encounter an error in the UI:

`Failed to load rules config from metrics: yaml: unmarshal errors: line 60: field query_offset not found in type definitions.GettableRuleGroupConfig`

I've also referenced the Grafana definition for the [GettableRuleGroupConfig](https://github.com/grafana/grafana/blob/06196022cf9a4f205748a4f37250313f220c4f03/pkg/services/ngalert/api/tooling/api.json#L1680) and this field is included in the definition. 

`"query_offset": {
     "type": "string"
    }`

Our question is why does Grafana show this error in the UI if the field is supported and what are the steps to resolve the error? If it helps, in the network traffic we can see that the error is thrown by a call to the endpoint: 

GET `/api/ruler/main-metrics/api/v1/rules?subtype=mimir`

**500 Internal Server Error**

_{
    "message": "yaml: unmarshal errors:\n  line 60: field query_offset not found in type definitions.GettableRuleGroupConfig",
    "traceID": "a29b8de6f545e6ee27f8f6a3d962ed9d"
}_

### What did you expect to happen?

The expectation is that this field is available in Grafana since it is also supported by Mimir. 

### Did this work before?

No, this is the first time we have attempted to use this parameter

### How do we reproduce it?

1. Setup a new terraform file using the [Mimir provider](https://registry.terraform.io/providers/fgouteroux/mimir/1.0.5/docs/resources/rule_group_recording)
2. Configure a mimir rule group recording resource with _query_offset_ set
`resource "mimir_rule_group_recording" "test" {
  name         = "test1"
  namespace    = "namespace1"
  interval     = "6h"
  query_offset = "5m"
  rule {
    expr   = "sum by (job) (http_inprogress_requests)"
    record = "job:http_inprogress_requests:sum"
  }
}`

3. Apply the terraform resource, navigate to Grafana and on the Alert Rules page you will now see the above referenced error

### Environment (with versions)?

Grafana: 11.2.2-security-01 / Helm chart: 8.5.12
Mimir: 2.14
Mimir Terraform provider: fgouteroux/mimir 1.0.5

### Grafana platform?

Kubernetes

**Comment by moustafab** [comment]
Thanks for filing this issue! I believe this was fixed in https://github.com/grafana/grafana/pull/94030 which would have landed in 11.3.0. Upgrading grafana should take care of that error!
