### ISSUE TITLE
Time Picker is not hidden if kiosk=1 parameter is used in URL in Grafana v11.2.2 (c47b921ef4)

### ISSUE THREAD

**Issue by PetrMa** [grafana/grafana#96595]
### What happened?

Hello,

I´am using Grafana in my Home Assistant system and the Grafana grafs is displayed in iframe in my dasboards.
I´am using this URL with specific parameters for ex.:
https://myurl/statistiky-internet?kiosk=1&orgId=1&refresh=1m&from=now-1M&to=now&viewPanel=6

In Grafana previous version Grafana v11.2.2 (c47b921ef4) the same URL shows this
![Image](https://github.com/user-attachments/assets/85e5e7f4-89cb-4c35-af80-a31007b48eb5)

In Grafana version Grafana v11.3.0 (d9455ff7db) this URL displays this
![Image](https://github.com/user-attachments/assets/2df9df0c-8048-4703-9804-155fc3ec83c5)

Why the Time Picker is displayed now in Kiosk view? I also tried to add the parameters
&notimepicker&notitle&nologo
to the URL but this does not help.

How can I hide the time picker from grafs in the iframe with Kiosk mode please?

### What did you expect to happen?

Hide the time picker from grafs in the iframe Kios mode parameter is used

### Did this work before?

Yes, it work in version Grafana v11.3.0 (d9455ff7db)

### How do we reproduce it?

1. upgrade from Grafana v11.3.0 (d9455ff7db) to Grafana v11.2.2 (c47b921ef4)
2. used these parameters in URL statistiky-internet?kiosk=1&orgId=1&refresh=1m&from=now-1M&to=now&viewPanel=6
3. the Time picker is displayed

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: Grafana v11.2.2 (c47b921ef4)
OS: Home Assistant OS
Browser: latest Chrome and Edge

### Grafana platform?

I don't know

**Comment by sithmein** [comment]
According to https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v11-3/#scenes-powered-dashboards-are-generally-available you have to add additional query parameters now, such as _dash.hideTimePicker. It requires modifications to all existing dashboard though. This should have been done the other way, add parameters to show controls on demand.

**Comment by PetrMa** [comment]
adding &_dash.hideTimePicker to my URL solved my problem. thanks
