### ISSUE TITLE
[Feature request] Atlassian Stride integration

### ISSUE THREAD

**Issue by Xorima** [grafana/grafana#9660]
Would it be possible to get atlassian Stride integration similar to how we have Hipchat (They decided to replace hosted hipchat with Stride)

I am happy to have an attempt at this but not really sure where to look, if someone could give me pointers it would be appreciated

Thanks

Jason

**Comment by BulatSaif** [comment]
@Jason-field, did you find workaround?

**Comment by azhard4int** [comment]
@Jason-field @BulatSaif on the same boat. Were you able to find the solution/workaround?

**Comment by rhodessteve** [comment]
Also wanting this feature.

**Comment by DmitryShaburov** [comment]
Workaround: use "Unified Webhooks" app in Stride, and configure Slack alert in grafana

**Comment by aelse** [comment]
Unfortunately Stride has been discontinued. Further details available at the link below.

https://www.atlassian.com/blog/announcements/new-atlassian-slack-partnership

**Comment by marefr** [comment]
Thanks @aelse. Closing this. Will consider reopen if I misunderstood something.
