### ISSUE TITLE
Dashboards: wasted space since 11.3

### ISSUE THREAD

**Issue by sithmein** [grafana/grafana#96620]
### What happened?

Before 11.3 the dashboard breadcrumbs and the time picker controls were on the same "line":
![Image](https://github.com/user-attachments/assets/0a2a9d02-a77b-4785-a0a8-e4692ae69cae)
Since 11.3 the time picker controls occupy a separate "line" which is most empty. This leads to wasted space:
![Image](https://github.com/user-attachments/assets/e587907c-5839-427a-84c1-1465245e0e0d)

### What did you expect to happen?

Leave the breadcrumbs and time picker controls in one "line".

### Did this work before?

Yes, it worked until 11.2.

### How do we reproduce it?

See screenshots in description.

### Environment (with versions)?

Grafana: 11.3
OS: Linux
Browser: Firefox 132

### Grafana platform?

Docker

**Comment by JoaoSilvaGrafana** [comment]
The reason for the timepicker being on another line might be because it is now in scenes, @grafana/dashboards-squad could you help answer that?
