### ISSUE TITLE
[Bug] 4.6.0-beta3 breaks cloudwatch templating filters

### ISSUE THREAD

**Issue by chrono** [grafana/grafana#9667]
A templating query like `ec2_instance_attribute(us-east-1, Tags.Name, { "tag:Environment": ["production"] })` should return results filtered by Environment tag.

It doesn't seem to apply any filters at all.

CloudWatch datasource, Grafana v4.6.0-beta3 (commit: 9a91a88)

**Comment by torkelo** [comment]
@mtanda is this something you could take a look at?

**Comment by TryTryAgain** [comment]
Would this be related to 4.6.0 breaking my templates which are like:

`$region | regions()`
`$LinkedAccount | dimension_values($region, AWS/Billing, EstimatedCharges, LinkedAccount)`
`$ServiceName | dimension_values($region, AWS/Billing, EstimatedCharges, ServiceName)`

I use that to see all possible services for all accounts out of our master billing account which has all the linked accounts through it. Now I'm getting `Metric request error`

**Comment by vasdee** [comment]
I can confirm this has been broken for all the 4.6 beta builds and the final 4.6 build. I had assumed this was an issue on my aws credentials until I saw this issue

**Comment by csghuser** [comment]
This appears to be broken in 4.6.0 for us. Filters have no effect.

**Comment by jdkindy** [comment]
This is an issue with 4.6.1

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/9718
