### ISSUE TITLE
[Bug]runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lwhile** [grafana/grafana#9668]
grafana version: 4.5.2 commit: ec2b0fe
datasource: influxdb
os: centos 7

description: I sent a json data which exported from grafana dashboard to ```/api/dashboards/import``` , 
and grafana server return a status about ```500 Internal Server error```.I think the reason for this error is because I missed the title field in json.

Does this need to be repaired? I think the grafana server should return a message about this error.If necessary, how do I contribute the code?

thanks.

**Comment by torkelo** [comment]
this api is not documented and only intended to be used by UI Import process.
