### ISSUE TITLE
Background color not updating on singlestat with value mapping to number

### ISSUE THREAD

**Issue by kylejvrsa** [grafana/grafana#9669]
I have a singlestat panel where I map null to 0 and then have any other value other than 0 shown as green and 0 shown as red, however when I try to use the background color option it doesn't work when the value is 0 even though the value itself changes to zero showing my logic works.

Grafana 4.5.2
Influxdb 1.3.6

Value mappings:
null -> 0

Thresholds:
1,1

**Comment by torkelo** [comment]
related to these feature requests:
https://github.com/grafana/grafana/issues/8404
https://github.com/grafana/grafana/issues/7631
