### ISSUE TITLE
docker image tag 11.3.1 unavailable

### ISSUE THREAD

**Issue by sebPomme** [grafana/grafana#96728]
### What happened?

Try to upgrade from grafana/grafana:11.3.0-security-01 to grafana/grafana:11.3.1 . 
Looks like the tag didn't exist, there is no more tag like <version> ?  
Sorry but i didn't see any note about this I just want to be sure.

### What did you expect to happen?

I except to find an image with the tag `11.3.1`

### Did this work before?

Yes

### How do we reproduce it?

1. `docker pull docker run grafana/grafana:11.3.1`

### Is the bug inside a dashboard panel?

No

### Grafana platform?

Docker

**Comment by mjnagel** [comment]
It looks like `11.3.1-ubuntu` is available but not the alpine (`11.3.1`) tag?

**Comment by jimmybrancaccio** [comment]
This is also happening with `grafana/grafana-enterprise:11.3.1`.

```console
~ docker pull grafana/grafana-enterprise:11.3.1
Error response from daemon: manifest for grafana/grafana-enterprise:11.3.1 not found: manifest unknown: manifest unknown
```

**Comment by Footur** [comment]
@sebPomme There is a type in the title → "11.3.1".

**Comment by aangelisc** [comment]
Hi everyone, apologies for this issues. We've now updated the docker images and they should all be available. Going to close this out but please reopen if the issue reoccurs!
