### ISSUE TITLE
[Question] d3.drag event is null in the new plugin I develop

### ISSUE THREAD

**Issue by ali-bugdayci** [grafana/grafana#9677]
Please include this information:
- What Grafana version are you using? 
master branch

I am creating a network graph plugin with d3. I am trying to use d3.drag() for dragging elements. 

Similar to this: https://bl.ocks.org/mbostock/4062045 

The callbacks were working. d3.event in the callbacks get null values. e.g: the dragged function I send in the block link above.

I checked the web for a solution and tried a couple of things but none worked. Hence I am asking if you guys have any recommendations.

The things I tried:

* I tried removing the drag event on the panel elements since they might be overlapping:

```
elem.parents(".panel").first().off();
```

The callbacks were working  so I dont think this is the problem, 

* Babel might be causing some problems according to this bug report: 
https://github.com/d3/d3/issues/2733#issuecomment-271321156

So I added d3-selection.js inside the plugin and imported it (adding d3-selection to dist/ folder without  System.register's )

```
import * as d3 from 'd3';
//import {event as currentEvent} from 'd3-selection';
import {event as currentEvent} from './d3-selection';

....

function dragged(d) {
      d.fx = currentEvent.x;
      d.fy = currentEvent.y;
    }

```

But this did not work too.

Any recommendations are kindly accepted.

**Comment by torkelo** [comment]
strange, not sure what could be the cause for this. 
Please using development section in community site for questions
https://community.grafana.com/c/development
