### ISSUE TITLE
[Feature request] Be able to use multiples of auto interval

### ISSUE THREAD

**Issue by adrianlzt** [grafana/grafana#9679]
The "auto" interval sometimes is not very useful, generating metrics too _noisy_:
![img-2017-10-26-150325](https://user-images.githubusercontent.com/3237784/32054595-2b5289dc-ba5f-11e7-858a-775abb5380af.png)

It could be changed to something bigger, but then it is static, and changing the timeframe will probably end with the same problem (too small intervals).

The same graphic with a better interval (IMHO)
![img-2017-10-26-150339](https://user-images.githubusercontent.com/3237784/32054591-2734d0e4-ba5f-11e7-9d78-e5a3edf06dc8.png)

If the "auto" could be used as a variable, like:
```
Interval: $auto*5
```
We could create graphics with the interval adapted to our needs and adapted to the timeframe selected.

**Comment by phemmer** [comment]
Dup of #8919
