### ISSUE TITLE
Plugin provisionning: Failed to download plugin archive

### ISSUE THREAD

**Issue by coutug** [grafana/grafana#96790]
### What happened?

I want to install the version 1.10.2 of grafana oncall plugin (latest version matching the oncall OSS [helm chart](https://github.com/grafana/oncall/blob/dev/helm/oncall/Chart.yaml) on dev branch). I am using this configuration for the grafana helm chart:
```
plugins:
  - https://grafana.com/api/plugins/grafana-oncall-app/versions/v1.10.2/download;grafana-oncall-app
```

The grafana pod get stuck in `CrashLoopBackOff` with the log `grafana Error: ✗ failed to download plugin archive: 404: Element not found (linux-amd64)`.

### What did you expect to happen?

Grafana installs the proper version of the plugin.

### Did this work before?

I did not try with other grafana version. But using older version of the plugin works. For instance, using oncall version `1.9.24` works.

### How do we reproduce it?

1. Install the grafana helm chart with the plugin configuration shown before.

### Environment (with versions)?

Grafana: 11.3.0
Kubernetes: 1.31.2

### Grafana platform?

Kubernetes

**Comment by mckn** [comment]
That resource does not exist. Please try removing the `v` from the version and it should work.

```bash
plugins:
  - https://grafana.com/api/plugins/grafana-oncall-app/versions/1.10.2/download;grafana-oncall-app
```

**Comment by coutug** [comment]
ah yes working now, thanks!
