### ISSUE TITLE
Alerting: grafana-server crashed reporting "fatal error: concurrent map iteration and map write"

### ISSUE THREAD

**Issue by JHoffman-FlexGen** [grafana/grafana#96809]
### What happened?

Our `grafana-server` instance crashed after reporting `fatal error: concurrent map iteration and map write`. We are running `grafana-enterprise-11.3.0`.

It seems there may have been a race condition in the alerting system which caused a crash when it tried to simultaneously read and write to the same map while processing alert rules. 

At the time of the crash, there were dashboards auto-refreshing, and alert rules being evaluated. other than that, there were no specific actions being taken by any users. 

I have attached the logs received at the time of the crash, which includes the trace. 
[grafana-server-crash-logs_2024-11-20.log](https://github.com/user-attachments/files/17837632/grafana-server-crash-logs_2024-11-20.log)

Please let me know if there's any additional information I can provide. 

### What did you expect to happen?

For the `grafana-server` instance to run without crashing.

### Did this work before?

We have not had this issue in the past. We have been running `grafana-enterprise-11.3.0` for a few weeks without issue. 

### How do we reproduce it?

I am unsure how to reproduce this, as it seemed to happen randomly. We have not seen this happen in the past. 

### Environment (with versions)?

Grafana: grafana-enterprise-11.3.0
OS: CentOS 7.9
Browser: Google Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

influxdb

**Comment by alexander-akhmetov** [comment]
Hi, thanks for reporting this! This bug [has been fixed recently](https://github.com/grafana/grafana/pull/95985). It will be included in the closest release.

**Comment by alexander-akhmetov** [comment]
The fix is released in Grafana 11.3.2 and 11.4.0. I'm closing this issue, but please feel free to reopen it if the problem remains.
