### ISSUE TITLE
[Feature request] Graph-independent annotations

### ISSUE THREAD

**Issue by yacoob** [grafana/grafana#9680]
4.6 annotations are really nice. It'd be really nice if we could also add an annotation that is graph-independent - that is, once added, would appear on every single graph on the dashboard. As far as I can tell, annotation is only present on the graph you've added it too. For general "outage starts here" periods, it might be convenient to mark them once, and view the same affected region on multiple graphs.

**Comment by daniellee** [comment]
It is totally possible to do this. Think we have to make the documentation a bit clearer on this point.

> You can create new annotation queries that fetch annotations from the native annotation store via the -- Grafana -- data source and by setting Filter by to Tags. Specify at least one tag. For example create an annotation query name outages and specify a tag named outage. This query will show all annotations you create (from any dashboard or via API) that have the outage tag.

http://docs.grafana.org/reference/annotations/#query-by-tag  

Add a tag to your annotation and it can be accessed by any dashboard.

**Comment by yacoob** [comment]
Yup, this is exactly what I wanted to achieve. The UI could be more accomodating (eg. autocompletion/selection of existing tags), but other than that, this works exactly as I wanted. Thank you! :)

**Comment by cruiser607** [comment]
Was looking for the exact same thing ... love it!
