### ISSUE TITLE
[Feature Request] Support for DB2 data source. 

### ISSUE THREAD

**Issue by jrespeto** [grafana/grafana#9682]
Some of our projects are having databases with DB2.
Can you add DB2 as a data sources for Grafana?

https://bitbucket.org/phiggins/db2cli

**Comment by bergquist** [comment]
This have to wait for backend plugins.

https://github.com/grafana/grafana/issues/6841

**Comment by daniellee** [comment]
Should also add that it is very unlikely that the Grafana team will build this. However, someone from the community might. There are go drivers for db2: https://bitbucket.org/phiggins/db2cli

**Comment by blenard81** [comment]
Does anyone know the proper way to write a DB2 connect for Grafana?  We use BLU for our metrics and would like to see Grafana connectivity.

**Comment by bergquist** [comment]
Closing this since it won't be part of Grafana Core but rather a plugin developed by the community.
