### ISSUE TITLE
Variables are not updated

### ISSUE THREAD

**Issue by felixPG** [grafana/grafana#9685]
Hi All!

I have in my dashboard a variable that get a list of pods in an specific namespace:

label_values(kube_pod_info{namespace="mynamespace"}, pod)

The datasource is prometheus.

I have the variable values exposed in my dashboard for select. The problem is when (for example) I kill a pod and the pod restart again, the pod name change (is a replicaset) and the new pod name does not appear in a list of pods for select in my dashboard. Appear if I go to the variable declaration and change something to re-evaluate the variable.

If posible to update a variable values with an interval time?? How I can update the variable values?
The other problem is that pods that was deleted since a certain time appear as variable value like alive!! How can avoid this?

**Comment by torkelo** [comment]
In variable options, set refresh to on dashboard Load
