### ISSUE TITLE
Grafana  4.5.2 Anonymous Auth means need not login just watch dashborad ??

### ISSUE THREAD

**Issue by dtbdtb** [grafana/grafana#9686]
hi
our version is 452
so we set config about anonymous auth like ";enabled = true"
i think it means not need login can watch dashboard but with only viewer?
am i right?
but stiil need auth 
why ?
thanks a lot

**Comment by torkelo** [comment]
Remove the semicolon it means the line commented out

**Comment by dtbdtb** [comment]
that is right
thank you torkelo
welcome to china
by the way .how to change title in login page
i found login.html is only part of login page
and how to remove foorter?
