### ISSUE TITLE
Not exist file : grafana-latest.linux-x64-musl.tar.gz

### ISSUE THREAD

**Issue by worker24h** [grafana/grafana#96885]
### What happened?

compile source on Dockerfile , occur a error: 
```
Step 61/86 : FROM ${BASE_IMAGE} as tgz-builder
 ---> 05455a08881e
Step 62/86 : WORKDIR /tmp/grafana
 ---> Using cache
 ---> 067ba919902b
Step 63/86 : ARG GRAFANA_TGZ="grafana-latest.linux-x64-musl.tar.gz"
 ---> Using cache
 ---> 4de1ac3fd7f6
Step 64/86 : COPY ${GRAFANA_TGZ} /tmp/grafana.tar.gz
COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist
```

### What did you expect to happen?

Fixed the bug

### Did this work before?

git clone the latest code,  `docker build .`

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by Proximyst** [comment]
You're intended to run `make build-docker-full`. See our documentation here: https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md#build-a-docker-image

**Comment by RenhaoPan** [comment]
version 12.2.1; branch release-12.2.1
Getting the same issue here.
changed the Makefile:

> 439 .PHONY: build-docker-full-ubuntu
440 build-docker-full-ubuntu: ## Build Docker image based on Ubuntu for development.
441     @echo "build docker container mode=($(DOCKER_JS_NODE_ENV_FLAG))"
442     tar -ch . | \
443     docker build - \
444     --network host \
445     --platform $(PLATFORM) \
446     --build-arg NODE_ENV=$(DOCKER_JS_NODE_ENV_FLAG) \
447     --build-arg JS_NODE_ENV=$(DOCKER_JS_NODE_ENV_FLAG) \
448     --build-arg JS_YARN_INSTALL_FLAG=$(DOCKER_JS_YARN_INSTALL_FLAG) \
449     --build-arg JS_YARN_BUILD_FLAG=$(DOCKER_JS_YARN_BUILD_FLAG) \
450     --build-arg GO_BUILD_TAGS=$(GO_BUILD_TAGS) \
451     --build-arg WIRE_TAGS=$(WIRE_TAGS) \
452     --build-arg COMMIT_SHA=$$(git rev-parse HEAD) \
453     --build-arg BUILD_BRANCH=$$(git rev-parse --abbrev-ref HEAD) \
454     --build-arg BASE_IMAGE=ubuntu:22.04 \
455     --build-arg GO_IMAGE=golang:$(GO_VERSION) \
456     --tag grafana/grafana$(TAG_SUFFIX):dev-ubuntu \
457     $(DOCKER_BUILD_ARGS)

Using the Build Command: `make build-docker-full-ubuntu`

COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist

**Comment by RenhaoPan** [comment]
> version 12.2.1; branch release-12.2.1 Getting the same issue here. changed the Makefile:
> 
> > 439 .PHONY: build-docker-full-ubuntu
> > 440 build-docker-full-ubuntu: ## Build Docker image based on Ubuntu for development.
> > 441     [@echo](https://github.com/echo) "build docker container mode=($(DOCKER_JS_NODE_ENV_FLAG))"
> > 442     tar -ch . | 
> > 443     docker build - 
> > 444     --network host 
> > 445     --platform $(PLATFORM) 
> > 446     --build-arg NODE_ENV=$(DOCKER_JS_NODE_ENV_FLAG) 
> > 447     --build-arg JS_NODE_ENV=$(DOCKER_JS_NODE_ENV_FLAG) 
> > 448     --build-arg JS_YARN_INSTALL_FLAG=$(DOCKER_JS_YARN_INSTALL_FLAG) 
> > 449     --build-arg JS_YARN_BUILD_FLAG=$(DOCKER_JS_YARN_BUILD_FLAG) 
> > 450     --build-arg GO_BUILD_TAGS=$(GO_BUILD_TAGS) 
> > 451     --build-arg WIRE_TAGS=$(WIRE_TAGS) 
> > 452     --build-arg COMMIT_SHA=$$(git rev-parse HEAD) 
> > 453     --build-arg BUILD_BRANCH=$$(git rev-parse --abbrev-ref HEAD) 
> > 454     --build-arg BASE_IMAGE=ubuntu:22.04 
> > 455     --build-arg GO_IMAGE=golang:$(GO_VERSION) 
> > 456     --tag grafana/grafana$(TAG_SUFFIX):dev-ubuntu 
> > 457     $(DOCKER_BUILD_ARGS)
> 
> Using the Build Command: `make build-docker-full-ubuntu`
> 
> COPY failed: file not found in build context or excluded by .dockerignore: stat grafana-latest.linux-x64-musl.tar.gz: file does not exist

I fix this by build my Dockerfile:

```
FROM ubuntu:22.04

ADD sources.list_image22 /etc/apt/sources.list
ADD pip.conf /root/.pip/pip.conf
ADD vimrc /root/.vimrc

ENV NODE_OPTIONS=--max_old_space_size=8000

WORKDIR /tmp/grafana

# JS build
RUN apt-get update && \
    apt-get install --no-install-recommends -y ca-certificates curl gnupg tzdata && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" > /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install --no-install-recommends -y make gcc g++ python3 git nodejs && \
    corepack enable && \
    corepack prepare yarn@4.9.2 --activate && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    node -v && \
    yarn -v

ADD grafana.tar.gz /tmp/grafana/
RUN ls -l /tmp/grafana/

ENV NODE_ENV=production

RUN yarn install

RUN yarn build


# Golang build stage
RUN curl -LO https://go.dev/dl/go1.25.3.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.25.3.linux-amd64.tar.gz && \
    rm go1.25.3.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
RUN go version

WORKDIR /tmp/grafana

# 设置 GOPROXY 避免网络问题
ENV GOPROXY=https://goproxy.cn,direct

RUN go mod download

ENV COMMIT_SHA=""
ENV BUILD_BRANCH=""

RUN make build-go GO_BUILD_TAGS=oss WIRE_TAGS=oss

ENV PATH="/usr/share/grafana/bin:$PATH" \
  GF_PATHS_CONFIG="/etc/grafana/grafana.ini" \
  GF_PATHS_DATA="/var/lib/grafana" \
  GF_PATHS_HOME="/usr/share/grafana" \
  GF_PATHS_LOGS="/var/log/grafana" \
  GF_PATHS_PLUGINS="/var/lib/grafana/plugins" \
  GF_PATHS_PROVISIONING="/etc/grafana/provisioning"

# grafana
WORKDIR /usr/share/grafana

RUN cp -r /tmp/grafana/conf ./conf

RUN if [ ! $(getent group "0") ]; then \
  if grep -i -q alpine /etc/issue; then \
  addgroup -S -g 0 grafana; \
  else \
  addgroup --system --gid 0 grafana; \
  fi; \
  fi && \
  GF_GID_NAME=$(getent group 0 | cut -d':' -f1) && \
  mkdir -p "$GF_PATHS_HOME/.aws" && \
  if grep -i -q alpine /etc/issue; then \
  adduser -S -u 472 -G "$GF_GID_NAME" grafana; \
  else \
  adduser --system --uid 472 --ingroup "$GF_GID_NAME" grafana; \
  fi && \
  mkdir -p "$GF_PATHS_PROVISIONING/datasources" \
  "$GF_PATHS_PROVISIONING/dashboards" \
  "$GF_PATHS_PROVISIONING/notifiers" \
  "$GF_PATHS_PROVISIONING/plugins" \
  "$GF_PATHS_PROVISIONING/access-control" \
  "$GF_PATHS_PROVISIONING/alerting" \
  "$GF_PATHS_LOGS" \
  "$GF_PATHS_PLUGINS" \
  "$GF_PATHS_DATA" && \
  cp conf/sample.ini "$GF_PATHS_CONFIG" && \
  cp conf/ldap.toml /etc/grafana/ldap.toml && \
  chown -R "grafana:$GF_GID_NAME" "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING" && \
  chmod -R 777 "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"

RUN mkdir -p ./bin && \
    cp -r /tmp/grafana/bin/*/grafana* ./bin/

EXPOSE 3000

RUN cp /tmp/grafana/packaging/docker/run.sh /run.sh

ENTRYPOINT [ "/run.sh" ]
```
