### ISSUE TITLE
[Bug] Failed to get annotations - Grafana 4.6.0

### ISSUE THREAD

**Issue by audip** [grafana/grafana#9688]
Please include this information:
- What Grafana version are you using? **4.6.0**
- What datasource are you using? Cloudwatch, but error occurs on all
- What OS are you running grafana on? Kubernetes 1.7.7 on AWS 
- What did you do? Opened an existing dashboard
- What was the expected result? Dashboard working
- What happened instead? Errors on each dashboard page

Attaching screenshot
<img width="1403" alt="screenshot 2017-10-26 11 36 49" src="https://user-images.githubusercontent.com/4290846/32065305-041989e6-ba42-11e7-969f-723938201cc1.png">

**Comment by audip** [comment]
@torkelo @bergquist Please take a look

**Comment by torkelo** [comment]
looks like a backend error, can you look in you grafana server backend log file? located at /var/lib/grafana/grafana.log on linux systems

**Comment by audip** [comment]
Adding log file from internal grafana running on Kubernetes 
[logs-from-grafana-in-grafana-487328344-5xh1q.txt](https://github.com/grafana/grafana/files/1419932/logs-from-grafana-in-grafana-487328344-5xh1q.txt)

**Comment by torkelo** [comment]
very strange, your annotation table does not have a tags column. Can you open your mysql database and inspect the mysql table? also the contents of you migration_log ? there is a migration with id "Add column tags to annotation table" , but if this migration did not complete your server should not be able to start so very strange. 

Anyway adding (manually) a tags column with nvarchar length 500 should fix your problem

**Comment by audip** [comment]
@torkelo We recently migrated from sqlite to MySQL for Database, will that be a reason for this aberrant behaviour?

**Comment by torkelo** [comment]
Yes,, the schema is out of sync with the migration log

**Comment by audip** [comment]
Will do manual upgrade tomorrow and close this issue when it succeeds, otherwise I can ask you follow-up questions

**Comment by audip** [comment]
On inspecting,

- annotation table on MySQL didn't have a tags column
<img width="688" alt="screenshot 2017-11-01 14 43 18" src="https://user-images.githubusercontent.com/4290846/32294308-bd885ff8-bf13-11e7-9949-a5d41c8f7c32.png">
- couldn't find "Add column tags to annotation table" when `grep`'d: `SELECT * FROM grafana.migration_log`
- grafana server did start without that migration "Add column tags to annotation table"
- will update more details

**Comment by torkelo** [comment]
no, closing this for now as no one else has encountered this

**Comment by tehlers320** [comment]
I just encountered it. I wonder if it's an ordering issue, starting the new grafana then loading an old mysql dump over it?

procedure
v4.5.2 is running on another vm.
Started a new RDS instance
Started v4.6.1 on new VM
Loaded mysql dump from old to new RDS instance

**Comment by torkelo** [comment]
Well of course that is an issue

**Comment by tehlers320** [comment]
Yup verified, i repeated the procedure ensuring v4.6.1 was off until the mysqldump restore was complete. Then once complete started v4.6.1 and there are no issues.

Ordering of upgrade.
