### ISSUE TITLE
[Bug] Link to panel fullscreen inside closed row is not working

### ISSUE THREAD

**Issue by hrochniak** [grafana/grafana#9689]
Hello guys. I am not really sure if this should be bug or feature request ... it works, but as I understand it is not official feature yet and have some "buggy" behavior.

I have SingleStat panels with count of events (with some filters) on the top of dashboard. In the bottom there are Table panels with specific list of those events. What I want to do is make a link from SingleStat panel to open Table panel in the bottom on fullscreen. 

Now I am using absolute link like "dashboard/db/dashboard-name?panelId=6&fullscreen&orgId=2". It works, but I am getting two types of behavior:
1. In case row with Table is open, it will normally open Table on fullscreen, and it will add "Back to dashboard" link to the header. This is really nice and works as expected! 
2. In case row with Table is closed, it will not open Table panel on fullscreen, but will stack whole dashboard until I will open this row. 

I would like to have this tables closed by default, because they are not needed to be opened until I want to see that specific list. From my point of view there are two possible solutions:
1. Add feature to add link to the panel (I think it is more complex, but not needed)
2. Fix the problem with opening panel to fullscreen inside closed row.

Is there any chance to make this? 

Thank you!

**Comment by bergquist** [comment]
Fixed in 5.0.4
