### ISSUE TITLE
[Bug] Duplicate imports within plugins in 4.6.0

### ISSUE THREAD

**Issue by limscoder** [grafana/grafana#9691]
Please include this information:
- What Grafana version are you using?

4.6.0

- What datasource are you using?

Prometheus

- What OS are you running grafana on?

OSX Docker image

- What did you do?

This one is going to be a bit tough to explain. I've got a plugin that imports `d3` `v4.11`. Everything works correctly in `4.5.2`. I get multiple instances of the `d3` object in 4.6.0, as if something in the module import code is not working correctly. Below is the simplest fail case I could come up with.

```javascript
import * as d3 from './lib/d3/d3.min.js';
import { MetricsPanelCtrl } from 'app/plugins/sdk';
import panelTemplate from './panel.html';

export default class MyCtrl extends MetricsPanelCtrl {
  static template = panelTemplate;

  constructor($scope, $injector, variableSrv) {
    super($scope, $injector);
    this.events.on('data-received', this.onDataReceived.bind(this));
  }

  onDataReceived(dataList) {
    const el = d3.select('.render-root');
    rootEl.append('button')
          .html('Click ME!')
          .on('click', () => {
            // d3.event is null, because there are multiple d3 instances
            console.log('this is null', d3.event);
          });
  }
}
``` 

- What was the expected result?

`d3.event` is populated with the current event object and there is a single instance of `d3`.

I know this sounds like a problem with the plugin, but I've scoured the code and don't see any issues, and it works perfectly fine with grafana `4.5.2` and below. Did something change about how modules are imported with `4.6`?

**Comment by torkelo** [comment]
see https://github.com/grafana/grafana/blob/master/PLUGIN_DEV.md 

Grafana includes d3 and exposes this to plugins via d3 path.   (import d3 from 'd3')

**Comment by limscoder** [comment]
Awesome, thanks!

**Comment by limscoder** [comment]
@torkelo What version of D3 does Grafana 4.6 expose?

**Comment by limscoder** [comment]
@torkelo problem seems to persist even when using `import d3 from 'd3'`.
![screen shot 2017-10-26 at 1 26 11 pm](https://user-images.githubusercontent.com/121623/32072885-7c4a4a72-ba51-11e7-9a25-227bfb595674.png)
