### ISSUE TITLE
Alerting: graphite maxDataPoints seems to be hardcoded to 500

### ISSUE THREAD

**Issue by kamilkrampa** [grafana/grafana#96934]
### What happened?

Grafana seems to be always sending 500 maxDataPoints parameter to Graphite regardless of the value set on UI. This behaviour happens only in alerts, not in panels.

### What did you expect to happen?

It should use maxDataPoints value from the UI

![Image](https://github.com/user-attachments/assets/8555b97b-be76-4866-9a99-50818686ef23)

### Did this work before?

I don't think so. It is broken in Grafana 9 and 11.

### How do we reproduce it?

1. Create any alert which uses graphite, set maxDataPoints to more than 500
2. Log requests on the graphite side and see that the value is 500

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes

### Datasource(s)?

Graphite

**Comment by aangelisc** [comment]
Hi @kamilkrampa, thank you for raising this issue. #97178 should fix this 😊
