### ISSUE TITLE
[Bug] Single Stat still not changing color when it exceeds max threshold

### ISSUE THREAD

**Issue by cjyumul** [grafana/grafana#9694]
Hello, I deployed my grafana instance on docker using the latest image. (4.6.0) on Rhel 7  and add MySQL as my default datasource. 

I created a single stat to filter if the exec id exceeds the threshold and therefore change its background color to red, but it didn't changed at all.

Here is the option config and the current value of the exec id
![screen shot 2017-10-26 at 9 43 12 pm](https://user-images.githubusercontent.com/19282239/32084367-b222b964-ba96-11e7-9dc8-b238e344caf6.png)

And here is the result when i return to the dashboard and refresh it many times.
![screen shot 2017-10-26 at 9 44 15 pm](https://user-images.githubusercontent.com/19282239/32084398-df80408e-ba96-11e7-80cb-8a1847db4e66.png)
 

Do I need to set the right UNIT?
Help for the right config is very much appreciated.

Thanks all!

**Comment by cjyumul** [comment]
Additional, here my instance running on docker
![screen shot 2017-10-26 at 9 36 46 pm](https://user-images.githubusercontent.com/19282239/32084524-a63c51ae-ba97-11e7-982e-cde9f5ce8f14.png)

**Comment by torkelo** [comment]
Can you show response from your query? Sometimed having strikh values in your tsdb can cause this

**Comment by utkarshcmu** [comment]
I am facing a similar issue, as earlier Singlestat color use to change based on the formattedValue but now it changes on the actual value.

**Comment by cjyumul** [comment]
Isn't that '829' from my query the response. 
![screen shot 2017-10-27 at 2 05 06 am](https://user-images.githubusercontent.com/19282239/32090032-4d4d11ea-babb-11e7-879c-74bb766af8eb.png)

For additional info, I created a table panel to quickly track changes on every row or Exec IDs.
![screen shot 2017-10-26 at 10 04 52 pm](https://user-images.githubusercontent.com/19282239/32090040-5bdcdd08-babb-11e7-9cba-b483469ad749.png)

**Comment by torkelo** [comment]
In metric last tab click query inspector, expand response to show the type of the returned value column

**Comment by cjyumul** [comment]
Okay, here it is.

`xhrStatus:"complete"
request:Object
method:"POST"
url:"api/tsdb/query"
data:Object
from:"1509064744976"
to:"1509088067081"
queries:Array[1]
0:Object
refId:"A"
intervalMs:300000
maxDataPoints:100
datasourceId:1
rawSql:"SELECT jc_exec_id as 'Exec ID', ctx_project as 'Project', report_id as 'Report ID', status as 'Job Status', node as 'Result' FROM base_report WHERE ctx_project = 'DEV' and id = 829"
format:"table"
response:Object
results:Object
A:Object
refId:"A"
meta:Object
rowCount:1
sql:"SELECT jc_exec_id as 'Exec ID', ctx_project as 'Project', report_id as 'Report ID', status as 'Job Status', node as 'Result' FROM base_report WHERE ctx_project = 'DEV' and id = 829"
series:null
tables:Array[1]
0:Object
columns:Array[5]
0:Object
text:"Exec ID"
1:Object
text:"Project"
2:Object
text:"Report ID"
3:Object
text:"Job Status"
4:Object
text:"Result"
rows:Array[1]
0:Array[5]
0:"**829**"
1:"**DEV**"
2:"**Server Validation/Server Validation**"
3:"**succeed**"
4:"**1/0/1**"`

**Comment by bergquist** [comment]
I think its the same error as your issue with the table panel. You have three thresholds but you only need two.

Anything below the first one is green. anything between first and second is orange. anything above the second is red.

**Comment by torkelo** [comment]
Make sure the column your SQL query is returning is a number (use a SQL convert function if needed)

**Comment by cjyumul** [comment]
Thanks @torkelo. I see, my query returns the id 829 as a string and not a number. I got it working when I created a dummy table and query it. Thanks @bergquist.
