### ISSUE TITLE
[Bug] Table Panel's Threshold color not working - 4.6.0

### ISSUE THREAD

**Issue by cjyumul** [grafana/grafana#9695]
Hello, I deployed my grafana instance on docker using the latest image. (4.6.0) on Rhel 7 and add MySQL as my default datasource.

I added a table panel to show the recent job. Here is my table.
![screen shot 2017-10-26 at 10 08 38 pm](https://user-images.githubusercontent.com/19282239/32084970-5e05059a-ba9a-11e7-87af-85c54a31c33d.png)

Now here is the Column style
![screen shot 2017-10-26 at 10 11 22 pm](https://user-images.githubusercontent.com/19282239/32085015-abfa755a-ba9a-11e7-9ad3-55f08179a004.png)

Now when I go back to the dashboard and refresh it, the color still doesn't show up.

**Comment by whatwehaveunlearned** [comment]
I have exactly the same problem running the previous version. I can not make the color to stick. Colors change when you select a new time frame.

**Comment by bergquist** [comment]
Might be related to https://github.com/grafana/grafana/issues/9681

**Comment by bergquist** [comment]
@cjyumul you have three values in the threshold input. You only need two. 
In your case `300, 500`. anything above 500 should be red.

**Comment by torkelo** [comment]
thresholds seem to be working fine for me:
http://play.grafana.org/dashboard/db/table-panel-showcase?orgId=1 

make sure the column you apply the thresholds as a numeric value and not a string (with a number in it)
