### ISSUE TITLE
Bug,  sql syntax error when replace quotes for SqlDataSource

### ISSUE THREAD

**Issue by worker24h** [grafana/grafana#96953]
### What happened?

For MySQL DataSource:
=> e.g. ` SELECT aa, bb FROM t1 WHERE  bb in ('$query0')  and $__timeFilter(date_time)  LIMIT 10 `
The variable of `query0` is the variable of dashboard， for example：
![Image](https://github.com/user-attachments/assets/ad67806c-c12e-4c1b-ac7e-01d3ca8ccadd)

When selected 'ALL' or  some items of the options, we will get a incorrect sql， which it is generated by grafana. 

The incorrect sql may be：
`SELECT aa, bb FROM t1 WHERE  bb in (''XXX', 'YYY'')  and $__timeFilter(date_time)  LIMIT 10`

### What did you expect to happen?

The correct sql is `SELECT aa, bb FROM t1 WHERE  bb in ('XXX', 'YYY')  and $__timeFilter(date_time)  LIMIT 10`

### Did this work before?

NO

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by worker24h** [comment]
Hello everyone, I commit a PR for this bug.  PR:  https://github.com/VictoriaMetrics/victorialogs-datasource/issues/117

**Comment by zoltanbedi** [comment]
I tried to reproduce the issue without success.

This is what I tried:

### Custom variable with _multiple values_ and _include all_ enabled:
**a, b selected**
`SELECT *  FROM table1 WHERE value in ($multi)` -> `SELECT *  FROM table1 WHERE value in ('a','b')`

**a selected**
`SELECT *  FROM table1 WHERE value in ($multi)` -> `SELECT *  FROM table1 WHERE value in ('a')`

**all selected**
`SELECT *  FROM table1 WHERE value in ($multi)` -> `SELECT *  FROM table1 WHERE value in ('a','b')`


### Custom variable with _include all_ enabled:
**a selected**
`SELECT *  FROM table1 WHERE value in ($multi)` -> `SELECT *  FROM table1 WHERE value in ('a')`

**all selected**
`SELECT *  FROM table1 WHERE value in ($multi)` -> `SELECT *  FROM table1 WHERE value in ('a','b')`

Although the following query `SELECT *  FROM table1 WHERE value in ('$multi')` is producing the wrong query with quotes. The solution is to remove the quotes around the variable.

**Comment by worker24h** [comment]
@zoltanbedi Do you show me, your  the variables of grafana?

**Comment by zoltanbedi** [comment]
I tried it out from the main branch of grafana as you didn't specify the version. I also don't understand the problem. Is removing the quotes around the variable not working for you? How does your query looks like once you remove the quotes around them?

**Comment by worker24h** [comment]
> I tried it out from the main branch of grafana as you didn't specify the version. I also don't understand the problem. Is removing the quotes around the variable not working for you? How does your query looks like once you remove the quotes around them?

Yes, although I had to remove the quotes, the query is not working.

Cloud you show me your variables ?

**Comment by zoltanbedi** [comment]
> Cloud you show me your variables ?

Sorry but I can't.

**Comment by worker24h** [comment]
> > Cloud you show me your variables ?
> 
> Sorry but I can't.

Ok，I will build it with the newest code tomorrow. I try to reproduce it

**Comment by zoltanbedi** [comment]
> Ok，Do you use the MySQL datasouce?
yes

**Comment by worker24h** [comment]
> > Ok，Do you use the MySQL datasouce?
> 
> yes

You are right, the issue doesn't reproduce, But it does come up. Maybe it is fixed in `grafana/scenes`.  Sorry for wasting your time
@zoltanbedi

**Comment by zoltanbedi** [comment]
No worries @worker24h
