### ISSUE TITLE
[Bug] Zabbix triggers panel does not load and produces an error since update to version 4.6.0

### ISSUE THREAD

**Issue by belnarlo** [grafana/grafana#9696]
We updated to Grafana 4.6.0 (CentOS 7.3) yesterday. Since then any dashboards that have the Zabbix Triggers panel produce the following error on page load:

<img width="624" alt="error" src="https://user-images.githubusercontent.com/1818869/32094798-e96c4bc6-baf8-11e7-9c2d-02711807a6d4.png">

After the error clears, the panel is just a black box, which cannot be configured:

<img width="1414" alt="panel view" src="https://user-images.githubusercontent.com/1818869/32094822-04387aa6-baf9-11e7-9672-93dba0cb1915.png">

Before the upgrade the panel worked as expected, displaying the relevant zabbix triggers. Other data from Zabbix displayed in Grafan still displays as expected.

**Comment by torkelo** [comment]
Are you using latest version of the zabbix pluton?

**Comment by belnarlo** [comment]
I wasn't 100% sure how to check that so installed the latest version (3.7.0) to be sure, and restarted grafana, but the error remains the same I fear.

**Comment by belnarlo** [comment]
I came in this morning and "suddenly" it all works. No clue how, but I guess it must have been the (re)install of the zabbix plugin yesterday
