### ISSUE TITLE
[Feature request] Pass through time range & template variables on table links

### ISSUE THREAD

**Issue by wtigotw** [grafana/grafana#9702]
- What Grafana version are you using? **v4.5.2**
- What datasource are you using? **InfluxDB**
- What OS are you running grafana on? **Docker hub official container**
- What did you do? **Created a link on a table column**
- What was the expected result? **Ability to pass through time ranges and variables**
- What happened instead? **I can't**

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/1909
