### ISSUE TITLE
[Bug] - Upgraded from 4.5.2 to 4.6.0 and google auth through proxy no longer works.

### ISSUE THREAD

**Issue by jbehrends** [grafana/grafana#9703]
Please include this information:
- What Grafana version are you using?
4.6.0
- What datasource are you using?
Graphite
- What OS are you running grafana on?
CentOS 7.4
- What did you do?
Upgraded from 4.5.2 to 4.6.0.  No settings were changed.
- What was the expected result?
I should be able to click the login with google button and sign in.
- What happened instead?
I went to sign in with Google auth and get an error:  login.OAuthLogin(NewTransportWithCode)

I manage my Grafana install via Puppet and did nothing other than rev the version.  So all of my configs are exactly the same.

I have http_proxy, https_proxy, and no_proxy defined in /etc/sysconfig/grafana-server

I verified that the running process has these set in it's environment by looking at:
cat /proc/$(pgrep grafana-server)/environ

Relevant log line:
t=2017-10-27T12:36:22-0700 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="Post https://accounts.google.com/o/oauth2/token: dial tcp 216.58.216.141:443: getsockopt: connection refused"

If I revert back to 4.5.2 everything works fine.

**Comment by torkelo** [comment]
Very strange, nothing oauth related has changed that I know, this looks like a pure connection issue as well.

**Comment by torkelo** [comment]
In 4.6 we verify TLS for oauth calls and since your using a proxy that set could fail. 

in the [oauth.github] section in your grafana ini try adding:

```
tls_skip_verify_insecure = true
```

**Comment by jbehrends** [comment]
@torkelo 
Your suggestion did not work.  I assume that setting can also go under the [auth.google] section since I don't have a [oauth.github] section in my config.  So I tried adding that under my auth.google section and had no luck.

So I DID verify that the grafana-server process does see the proxy.  I tailed my proxy server access logs and when the grafana-server service is restarted I see it making a call out to grafana.com:443.

**Comment by mattbostock** [comment]
The `tls_skip_verify_insecure` setting would not resolve a 'connection refused' error; if the connection is being refused then the TLS handshake cannot take place.

**Comment by beardface** [comment]
Getting the same issue here.

**Comment by beardface** [comment]
Rolling back this file fixed it for us:
https://github.com/RiotGames/grafana/commit/f9a5d0e182de055c7621dbe8e6ee2c24e0b7337c

**Comment by mcv21** [comment]
I'm also seeing this with 4.6.1. `lsof` is showing me that even though `http_proxy` and `https_proxy` are set, grafana is trying to talk to google directly, not via the proxy, so auth fails with connection timed out.

**Comment by bergquist** [comment]
fixed by https://github.com/grafana/grafana/pull/12079
