### ISSUE TITLE
[Bug] v4.6.0 Segmentation Violation

### ISSUE THREAD

**Issue by Arovix** [grafana/grafana#9706]
Please include this information:

* _What Grafana version are you using?_
4.6.0 Linux-x64
* _What datasource are you using?_
InfluxDB 1.3.5
* _What OS are you running grafana on?_
RHEL 6.4
* _What did you do?_
Did a fresh install of v4.6.0, copied over conf files and grafana.db file from old v3.0.2 install. Server runs normally for a couple hours.
* _What was the expected result?_
Server continues to run normally.
* _What happened instead?_

Server process dies without writing error to logs. I restarted it with Debug level logging and left the console open to see if it printed anything there.

Issue encountered:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xecb1fa]

runtime stack:
runtime.throw(0x1276e2a, 0x2a)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8
```

(Full output in files below.)

I included the last few lines from the log before the stack trace. I also removed the usernames, but didn't otherwise alter the text.

Crash 1:
[grafanaCrash1.txt](https://github.com/grafana/grafana/files/1423738/grafanaCrash1.txt)

Crash 2:
[grafanaCrash2.txt](https://github.com/grafana/grafana/files/1423739/grafanaCrash2.txt)

Similar lines from the log that didn't cause a crash:

```
t=2017-10-27T15:27:00-0700 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-10-27T15:27:10-0700 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-10-27T15:27:20-0700 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-10-27T15:27:30-0700 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-10-27T15:27:33-0700 lvl=dbug msg="Updating last user_seen_at" logger=context userId=3 orgId=1 uname="<REMOVED>" user_id=3
t=2017-10-27T15:27:33-0700 lvl=dbug msg="Updating last user_seen_at" logger=context userId=3 orgId=1 uname="<REMOVED>" user_id=3
t=2017-10-27T15:27:33-0700 lvl=dbug msg="Updating last user_seen_at" logger=context userId=3 orgId=1 uname="<REMOVED>" user_id=3
t=2017-10-27T15:27:33-0700 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2017-10-27T15:27:40-0700 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-10-27T15:27:50-0700 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-10-27T15:28:00-0700 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-10-27T15:28:10-0700 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
```

I know 3.0.2->4.6.0 is a big jump, and I can do an intermediate upgrade first if necessary.

If there's an incompatibility with RHEL 6.4 I can upgrade that as well, but I'd prefer not to.

**Comment by torkelo** [comment]
Strange, we have other reports of "Database table locked" issues with sqlite3 not sure if its due to sqlite3 update or golang update or how Grafana uses sqlite. We will investigate. But the only known current fix is to migrate to mysql or postgres.

**Comment by ivanich** [comment]
@torkelo Not sure if this related but golang-1.9.2 has the following sql related fix https://github.com/golang/go/issues/22314

**Comment by bergquist** [comment]
4.6.1 will be built using golang 1.9.2 https://github.com/grafana/grafana/issues/9713

**Comment by Arovix** [comment]
I updated to 4.6.1 and so far it's looks like it's handling this correctly now (or at least not crashing):

```
DBUG[11-01|16:18:54] Scheduling update                        logger=alerting.scheduler ruleCount=3
DBUG[11-01|16:19:04] Scheduling update                        logger=alerting.scheduler ruleCount=3
DBUG[11-01|16:19:14] Scheduling update                        logger=alerting.scheduler ruleCount=3
DBUG[11-01|16:19:20] Updating last user_seen_at               logger=context userId=3 orgId=1 uname="<REMOVED>" user_id=3
DBUG[11-01|16:19:20] Updating last user_seen_at               logger=context userId=3 orgId=1 uname="<REMOVED>" user_id=3
DBUG[11-01|16:19:20] Updating last user_seen_at               logger=context userId=3 orgId=1 uname="<REMOVED>" user_id=3
DBUG[11-01|16:19:20] Updating last user_seen_at               logger=context userId=3 orgId=1 uname="<REMOVED>" user_id=3
DBUG[11-01|16:19:20] Updating last user_seen_at               logger=context userId=3 orgId=1 uname="<REMOVED>" user_id=3
INFO[11-01|16:19:20] Database table locked, sleeping then retrying logger=sqlstore retry=0
INFO[11-01|16:19:20] Database table locked, sleeping then retrying logger=sqlstore retry=0
INFO[11-01|16:19:20] Database table locked, sleeping then retrying logger=sqlstore retry=0
DBUG[11-01|16:19:24] Scheduling update                        logger=alerting.scheduler ruleCount=3
DBUG[11-01|16:19:32] avatar.fetch(fetch new avatar): http://secure.gravatar.com/avatar/4ca7499556227bbb17a4597a76ea27b0?d=retro&r=pg&size=200 
DBUG[11-01|16:19:34] Scheduling update                        logger=alerting.scheduler ruleCount=3
DBUG[11-01|16:19:44] Scheduling update                        logger=alerting.scheduler ruleCount=3
<continues>
```

I'll confirm next week that it has stayed up.

**Comment by bedrin** [comment]
I got a crash on 4.6.1 again:

> fatal error: unexpected signal during runtime execution
> runtime stack:
> 
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xecb1fa]
> 
> runtime.throw(0x1276e2a, 0x2a)
> /usr/local/go/src/runtime/panic.go:605 +0x95
> runtime.sigpanic()
> /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8
> goroutine 18357 [syscall, locked to thread]:
> runtime.cgocall(0xe8f400, 0xc420ba8578, 0xc420ba85a0)
> 
> .....
> 
> 
> net/http.(*connReader).backgroundRead(0xc420962090)
> created by net/http.(*connReader).startBackgroundRead
> /usr/local/go/src/net/http/server.go:656 +0xd8
> goroutine 32088 [chan receive]:
> database/sql.(*Tx).awaitDone(0xc420be8600)
> /usr/local/go/src/database/sql/sql.go:1695 +0x4b
> created by database/sql.(*DB).beginDC
> /usr/local/go/src/database/sql/sql.go:1451 +0x216

**Comment by orfey** [comment]
I updated grafana from 4.6.0 to 4.6.1 on Friday (November 3) and it works without crash now. The previous one crashes every 2 days.

**Comment by Arovix** [comment]
It's been over a week now since I upgraded to 4.6.1 and it hasn't crashed. I think the issue I was seeing is resolved.

**Comment by gjcarneiro** [comment]
Running grafana 4.6.1 in docker, with sqlite3 storage, and am also seeing this error, roughly every 30 minutes:
```
t=2017-11-13T15:22:09+0000 lvl=info msg="Starting Grafana" logger=server version=4.6.1 commit=cac8b97 compiled=2017-11-01T10:27:12+0000
[...]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xecb1fa]
```

**Comment by daniellee** [comment]
@gjcarneiro thanks for reporting this. We will investigate. Any action in the UI that seems to trigger it?

**Comment by Arovix** [comment]
I think I spoke too soon, this happened again today after installing 4.6.1 on another server.

Here's the error the user saw:
```
Annotation Query Failed
{"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/alerts/states-for-dashboard","params":{"dashboardId":2},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"error"}
￼
Annotation Query Failed
{"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/annotations","params":{"from":1510532721126,"to":1510619121126,"dashboardId":2},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"error"}
￼
Unexpected error
```

And the beginning of the console output:
```
INFO[11-13|16:03:59] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/dashboard/db/tra-dashboard status=302 remote_addr=192.168.70.63 time_ms=0 size=29 referer=
INFO[11-13|16:17:17] Database table locked, sleeping then retrying logger=sqlstore retry=0
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xecb1fa]

runtime stack:
runtime.throw(0x1276e2a, 0x2a)
	/usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

```

**Comment by orfey** [comment]
I also have a crash on another server after yesterday's update to 4.6.1, a second server with 4.6.1 the fifth day running without errors.

**Comment by torkelo** [comment]
Those who experience can you provide more detail on the hardware and OS? if running in docker what is the docker image used? docker file system? docker version?

**Comment by gjcarneiro** [comment]
docker image: `grafana/grafana:4.6.1` (from the normal docker hub). `Docker version 1.11.2, build b9f10c9`.  Driver: aufs.  Running on Ubuntu 14.04 on an Intel X5687 CPU.

**Comment by torkelo** [comment]
and any details on load / type of usage? alert count, req/s to grafana api? 

Been load testing grafana under different loads, have been able to generate multiple 

"Database table locked, sleeping then retrying logger=sqlstore retry=0" 

but no one that has caused a crash yet :(

**Comment by gjcarneiro** [comment]
From my side, it's hard to say what causes it.  This is used in production.  I configured Trace log level, but it doesn't even log HTTP requests, WTH?

**Comment by gjcarneiro** [comment]
All I can see from the logs is that at every crash there is a sqlite3 call involved:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xecb1fa]

runtime stack:
runtime.throw(0x1276e2a, 0x2a)
    /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 163 [syscall, locked to thread]:
runtime.cgocall(0xe8f400, 0xc420802d68, 0xc42068cd90)
    /usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc420802d38 sp=0xc420802cf8 pc=0x408254
github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3._Cfunc_sqlite3_step(0x7fc960002678, 0x7fc900000000)
    github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:841 +0x49 fp=0xc420802d68 sp=0xc420802d38 pc=0x914db9
github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next.func1(0x7fc960002678, 0xfc8a20)
    /go/src/github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3.go:917 +0x60 fp=0xc420802da0 sp=0xc420802d68 pc=0x923030
github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next(0xc420548730, 0xc4207fa380, 0xe, 0xe, 0x124c6ab, 0xc420802fa0)
    /go/src/github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3.go:917 +0x5d fp=0xc420802f30 sp=0xc420802da0 pc=0x91ecbd
database/sql.(*Rows).nextLocked(0xc4207cee00, 0xc420802fb0)
    /usr/local/go/src/database/sql/sql.go:2457 +0x70 fp=0xc420802f80 sp=0xc420802f30 pc=0x84f640
database/sql.(*Rows).Next.func1()
    /usr/local/go/src/database/sql/sql.go:2442 +0x3c fp=0xc420802fb0 sp=0xc420802f80 pc=0x85219c
--
```

**Comment by Arovix** [comment]
The second server that I encountered the error on is a VM running RHEL 7.2. It crashed two more times so I reverted it to the previous version for now.

There are no existing alerts as I'm upgrading from 3.0.4. I added three alerts on separate panels of one dashboard to test them out. All three of them are simple alerts formatted like: Evaluate every 5m, WHEN sum() OF query(A, 6m, now-1m) IS ABOVE 50.

**Comment by torkelo** [comment]
Anyone who had this issue with a fresh grafana 4.6.1 install? Maybe it's a newer version  sqlite3 reading an older db that is causing it.

Will try to replicate with by first using grafana 3 then upgrading, if that does not work it will spin up rhel 7

**Comment by gfl3** [comment]
I’m also seeing intermittent crashes with v4.6.2 on Centos 7.4.

**Comment by dimovnike** [comment]
this still happens in 4.6.3 in the latest docker container.

**Comment by mihaitdr** [comment]
I'm having the same issue in v4.6.3.

**Comment by Arovix** [comment]
Found a workaround in the linked issue (#9979).

Set the env variable GOMAXPROCS=1 before starting the server. After doing this it's been running 4.6.3 for two weeks with no crashes.

**Comment by torkelo** [comment]
closing this as it seems to have been fixed in later releases
