### ISSUE TITLE
Grafana upgrade to v11.2.0, v11.3.0 or v11.3.1, plugins page show "Not found" Error

### ISSUE THREAD

**Issue by daochun-zhao** [grafana/grafana#97074]
### What happened?

Grafana upgrade to v11.2.0, v11.3.0, and v11.3.1, the plugins page shows a “Not Found” Error, and no plugins are displayed.
but actually, there are a lot of plugins installed.

I found some 404 Not Found  #logs:

```
level=info msg="Request Completed" method=GET path=/api/instance/provisioned-plugins status=404 remote_addr=xxx.xxx.xxx.xxx ...
level=info msg="Request Completed" method=GET path=/api/instance/plugins status=404 remote_addr=xxx.xxx.xxx.xxx ...
```

The Grafana is running in AWS EKS.

How to resolve this?
thanks!

### What did you expect to happen?

1. no errors show
2. show plugins

### Did this work before?

yes, it works on v10 version

### How do we reproduce it?

1. upgrade to v11.2.0, v11.3.0 or v11.3.1
2. going to `Plugins` page
3. will see the issue

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by oshirohugo** [comment]
@daochun-zhao both endpoints that are giving you 404 should not be called in your case, this probably a wrong configuration. Please check the following property in your config file
```
[plugins]
plugin_admin_external_manage_enabled = false
```
it should be set to `false` as provided by `default.ini` originally.

**Comment by daochun-zhao** [comment]
> [@daochun-zhao](https://github.com/daochun-zhao) please check the value of `plugin_admin_enabled` it should be set to `true` as described here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#plugin_admin_enabled
> 
> more info about grafana config can be found in our docs: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana

@oshirohugo  I checked documents, and the config is below:

```
[plugins]
plugin_admin_enabled = true
plugin_admin_external_manage_enabled = false
```

But I still get the warning: `You do not have permission to install this plugin.`
For sure I'm the Admin Role.

Thanks!

**Comment by oshirohugo** [comment]
@daochun-zhao can you please go to Administration > Users and access > Users, click in your user and check if the Permissions are "Grafana Admin" and the Role in Organizations section is "Admin"?

**Comment by daochun-zhao** [comment]
![Image](https://github.com/user-attachments/assets/4753118a-17eb-403d-b5b0-34d99f0446bc)
@oshirohugo  see the image. Thanks.

**Comment by mckn** [comment]
@daochun-zhao can you please verify that [changing](https://community.grafana.com/t/error-you-do-not-have-permission-to-install-this-plugin/137276/2) the role to "Grafana Admin" solves it for you? Regardless, I have reached out to the team working with identity access within Grafana to investigate this a bit more in details.

**Comment by daochun-zhao** [comment]
@mckn  I'll try that, thanks.
