### ISSUE TITLE
Single stat panel with gradient color

### ISSUE THREAD

**Issue by Tittan31** [grafana/grafana#9709]
- What Grafana version are you using? 4.4.3
- What datasource are you using? Influx DB
- What OS are you running grafana on? Windows 10
- What did you do?...lot of things :-)
- What was the expected result? - more than lot of things
- What happened instead? - nothing :-) lol

Hey thanks for absolutelly amazing job with Grafana!.. Is there any chance to implement single stat panel with gradient color? Not just three based on threshold? Or is there any chance to increase the number of thresholds? 3 colors are huge limitation.. Single stat panels will be absolutelly amazing if more on screen...20 and so on with gradient colors... Thank you! Have a nice day.

**Comment by Tittan31** [comment]
funny thing is that on main page of grafana.com there is picture of single stat plugin - pointing on the Prometheus data source, and the single stat on that picture definitelly looks like using gradient colors.... is that possible to make somehow or that picture is just phantasy :-)

**Comment by bulletfactory** [comment]
I took artistic license for that dashboard graphic on the homepage.
Currently this is not possible in the actual software. :)

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.
