### ISSUE TITLE
[Bug] Discrepancy between docs and err for mysql annotations in 4.6.0

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#9710]
- What Grafana version are you using? 
4.6.0
- What datasource are you using? 
mysql
- What OS are you running grafana on? 
linux
- What did you do? 
upgraded from 4.5.0 to 4.6.0
- What was the expected result?
No errors - annotations continue working
- What happened instead?
Errors - no annotations are shown 

the documentation states that there should be a column named title:
![screen shot 2017-10-29 at 13 47 21](https://user-images.githubusercontent.com/4352719/32143298-e0ec718e-bcaf-11e7-8a5f-a98c31f5cf7f.png)

yet when adding one there is an error that pops up:
![screen shot 2017-10-29 at 13 47 32](https://user-images.githubusercontent.com/4352719/32143310-1c19f722-bcb0-11e7-9563-af874bd7ced2.png)
 
It seems that the error is inserted intentionally by the following commit https://github.com/grafana/grafana/commit/d1c9760fa8520701ff56a07bbe89ae666783c40f

Please ether fix the documentation or remove the error/fix the code.

**Comment by daniellee** [comment]
The change didn't occur in the commit referenced above. It was part of the new Annotations feature: 25aa9df2704ae23f808452a2280ae3dd13c17a0a and the docs are out of date.
