### ISSUE TITLE
[Request] Expose 'd3-scale-chromatic' to plugins

### ISSUE THREAD

**Issue by petrslavotinek** [grafana/grafana#9711]
For some reason d3-scale-chromatic is no longer part of d3. In order to make it work in my plugin, I had to copy its source into my plugin's source.
Would it be possible to expose it to plugins alongside core d3 library?
Built-in plugin Heatmap also imports it separately.
Thanks!

**Comment by daniellee** [comment]
As the carpet plot plugin is not being maintained anymore, I don't think you still need this. It is still a valid feature request so please comment or upvote this if you would still like us to expose this for React plugins in the toolkit.

https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/src/config/webpack.plugin.config.ts#L172
