### ISSUE TITLE
[Bug] Can't select color in "Display Override" menu

### ISSUE THREAD

**Issue by Dlizzz** [grafana/grafana#9715]
# Environment
- Grafana v4.6.0 (commit: c47f670) 
- Ubuntu Server Zesty 17.04 x64
- Browser on Windows 10 Professional 1709 - OS 16299.19 x64
- Microsoft Edge 41.16299.15.0 or Google Chrome 61.0.3163.100 (same behavior)
- Datasource: Influxdb 1.3.5-1 Ubuntu Server Zesty 17.04 x64

# Bug
When editing a Panel Graph, on the Display / Series Override tab, we don't see color palette in the menu when trying to change series color. This prevents to change the color.    
![grafana - override color - 2](https://user-images.githubusercontent.com/25765160/32148006-9564fce0-bcf0-11e7-9bf5-5f85f7ce7f01.png)
![grafana - override color - 1](https://user-images.githubusercontent.com/25765160/32148008-9a517896-bcf0-11e7-823e-cea233f2567b.png)
It seems similar to the closed issue:  #3554

# Expected behavior
See the color palette in the menu allowing color selection.

**Comment by civik** [comment]
I can confirm this bug with the following config:

Chrome: 62.0.3202.6
Client: OSX Sierra, 
Server: Grafana v4.6.0 from grafana/grafana:latest in Dockerhub running on Centos 7.4
Datasource: Prometheus 1.8

No color palette is presented when attempting to use "+  > Color > Change" menu on the Series Override dialog.

**Comment by alexanderzobnin** [comment]
Yes, confirmed.

**Comment by Dlizzz** [comment]
I confirmed that with Grafana v4.6.1 (commit: cac8b97) it works like a charm. And we have now the possibility to choose custom colors (outside of the standard palette) and you see the modification in real time on your chart. Great job! Thanks for the reactivity and the quality of your work. 
![image](https://user-images.githubusercontent.com/25765160/32383566-9fb91a20-c0b8-11e7-9b1b-e4e612940974.png)
![image](https://user-images.githubusercontent.com/25765160/32383647-d750ef1c-c0b8-11e7-967b-1bd2de529b7d.png)
