### ISSUE TITLE
Dashboard Panel Options Contract for Automatic Migrations

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#97152]
**Why?**

See incident docs https://docs.google.com/document/d/1Wv5IYYtCGGKD3suV_wgbg2d7H6lwMMeARLcAKg38WL0/edit?tab=t.0

We have a migration handler for Panels that we ask our developers to use https://grafana.com/developers/plugin-tools/how-to-guides/panel-plugins/migration-handler-for-panels to ensure smooth update experience. 

However the exact contract of what data is available when inside of the migration handler is not very strictly defined.

**Goal:**
Define the migration handler contract and cover it with automated tests/checks/linting (whatever makes the most sense) to prevent changes in dashboard runtime to deviate from this contract. 

If we can't find and automated way to scream at us when we violate contract - at least document it a bit better here https://grafana.com/developers/plugin-tools/how-to-guides/panel-plugins/migration-handler-for-panels

**Comment by academo** [comment]
finished with https://github.com/grafana/grafana/pull/97743
