### ISSUE TITLE
Colors not getting stored for default graph widget.

### ISSUE THREAD

**Issue by whatwehaveunlearned** [grafana/grafana#9716]
We have a System running: Grafana 4.6.0

We are experiencing a weird behavior with the colors in our dashboard using the default graph widget.

We are experiencing two different behaviors:

Using the default graph widget in line chart mode: When we set a different color from the color picker in the legend of the graph the lines change to the color selected. But when you chose a different time range the colors get back to the original default colors. We were expecting the colors to stick for all time ranges. Is there a way so that we could set the same customized colors for all time ranges?

Using the default graph widget in the histogram mode. When we set a different color from the color picker in the legend of the graph the bars change to the color selected. But when you refresh the page or when the page auto refreshes the colors get  back to the original default colors. So we are not able to set a different color for any of the histograms.

**Comment by torkelo** [comment]
When in histogram mode the series is created with the name count:

Enable legend and click the colored icon next series name. 

![image](https://user-images.githubusercontent.com/10999/32214053-e4f7a270-be1d-11e7-9fbe-48150839ecb2.png)

**Comment by whatwehaveunlearned** [comment]
That’s what we have been doing. Then the histogram returns back to the original color on refresh. And all the rest of the linecharts return to the default color when changing the time frame.

**Comment by torkelo** [comment]
ok, can replicate, caused by this issue https://github.com/grafana/grafana/issues/8886 

To work around, disable histogram mode, then change color on the first series returned, then enable histogram mode.
