### ISSUE TITLE
[Feature request] Need a way to specify name prefix and icons

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#9719]
Please include this information:
- What Grafana version are you using? **4.7.0-9930pre1 (nightly build)**
- What datasource are you using? **InfluxData**
- What OS are you running grafana on? **Ubuntu 17**
- What did you do? **I've created script to change tab name and page title prefix from "Grafana - " to "K8s DevStats - " and manually replaced all logo icons"**
- What was the expected result? **I'm expecting to be able to set this in the config file instead of manually changing text in minimified js files**
- What happened instead? **It is working OK, but requires manual sources override and is quite tricky**

This is the script I'm using ATM:
```
#!/bin/sh
# GRAFANA_DATA=/usr/share/grafana/
for f in `find ${GRAFANA_DATA} -type f -exec grep -l "Grafana -" "{}" \; | sort | uniq`
do
  ls -l "$f"
  vim -c "%s/Grafana -/K8s DevStats -/g|wq" "$f"
done
cp -n ${GRAFANA_DATA}public/img/grafana_icon.svg ${GRAFANA_DATA}public/img/grafana_icon.svg.bak
cp grafana/img/k8s.svg ${GRAFANA_DATA}public/img/grafana_icon.svg || exit 1
cp -n ${GRAFANA_DATA}public/img/fav32.png ${GRAFANA_DATA}public/img/fav32.png.bak
cp grafana/img/k8s32.png ${GRAFANA_DATA}public/img/fav32.png || exit 1
cp -n ${GRAFANA_DATA}public/img/fav16.png ${GRAFANA_DATA}public/img/fav16.png.bak
cp grafana/img/k8s32.png ${GRAFANA_DATA}public/img/fav16.png || exit 1
cp -n ${GRAFANA_DATA}public/img/fav_dark_16.png ${GRAFANA_DATA}public/img/fav_dark_16.png.bak
cp grafana/img/k8s32.png ${GRAFANA_DATA}public/img/fav_dark_16.png || exit 1
cp -n ${GRAFANA_DATA}public/img/fav_dark_32.png ${GRAFANA_DATA}public/img/fav_dark_32.png.bak
cp grafana/img/k8s32.png ${GRAFANA_DATA}public/img/fav_dark_32.png || exit 1
echo 'OK'
``` 

Would be great to be able to set this in config file.

**Comment by torkelo** [comment]
Rebranding options are not something we want to add :)
