### ISSUE TITLE
[Feature request] Need to have Display, Stacking, Percent as a end-user UI toggle + URL for that

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#9722]
Please include this information:
- What Grafana version are you using? **4.7.0-pre1 (commit: e1765e3)**
- What datasource are you using? **Influx**
- What OS are you running grafana on? **Ubuntu 17**
- What did you do? **Created two separate dashboards one with stacking and percent and another one without percent option selected**
- What was the expected result? **I would like to have UI toggle to change display of stacking value: just like toggling "Percent" box in the edit mode**
- What happened instead? **I need to create two separate dashboards for this**

I just want to merge those two dashboards into one with UI Toggle "Percent"
I also need to have stateful URLs for this:
![screen shot 2017-10-30 at 11 53 56](https://user-images.githubusercontent.com/2469783/32167613-b502f696-bd69-11e7-8fff-7101bfefd2fd.png)
![screen shot 2017-10-30 at 11 54 09](https://user-images.githubusercontent.com/2469783/32167614-b51df73e-bd69-11e7-9e59-a212b9a7474c.png)
https://devstats.k8s.io/dashboard/db/companies-stats?orgId=1
https://devstats.k8s.io/dashboard/db/companies-stats-percent?orgId=1

cc @dankohn

**Comment by torkelo** [comment]
maybe add graph option toggle (hidden under panel extra actions panel menu where we have Toggle Legend). 

Not seeing a way to have this be a dashboard wide toggle.

**Comment by lukaszgryglicki** [comment]
You mean this?
![screen shot 2017-10-31 at 09 31 23](https://user-images.githubusercontent.com/2469783/32214188-50fed894-be1e-11e7-9492-f362512ca673.png)

I think it is OK to be a graph option, but maybe it should be more visible, just like a graph toggle/checkbox but visible somewhere on the graph area?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
