### ISSUE TITLE
[Feature request] [js] login using password managers such as KeeFox with Keepass

### ISSUE THREAD

**Issue by arthurlogilab** [grafana/grafana#9725]
- What Grafana version are you using?

 Grafana v4.5.2 (commit: ec2b0fe) 

- What datasource are you using?

n/a

- What OS are you running grafana on?

debian (n/a I believe)

- What did you do?

Using Firefox, go to the login page, try using keefox to login to grafana. keefox and keepass (or firefox) prefills the textareas for login and password. Login button is disabled. 

- What was the expected result?

To be logged in (or at least be able to click on the Login button)

- What happened instead?

Login button is disabled. Typing Enter in the user field of password field doesn't log me in. 

Workaround : simulate typing is those two fields by adding a space and then removing it. Javascript "magic" enables the login button and I can login.

**Comment by bergquist** [comment]
We should enable password managers

**Comment by daniellee** [comment]
Not sure I understand this. The login button is never disabled? This is an empty login form on Firefox and the login button is not disabled:

![image](https://user-images.githubusercontent.com/434655/32178667-96204da4-bd8d-11e7-83c7-3b5fcd2e74a4.png)

I am installing Keefox now to test this out.

**Comment by arthurlogilab** [comment]
@daniellee when you type something in user/password the button will turn orange, it is then enabled. Otherwise clicking on the grey button doesnt have any effect.

**Comment by daniellee** [comment]
@arthurlogilab ok, confirmed now on 4.5.2 - native autofill and CKP (Keepass for Chrome) autofill in Chrome works but not the Keefox password manager. So I'm wondering if it only is Keefox that does not trigger the right event or if this is a general problem for all password managers? This seems to be the first issue about it.

There do seem to be a few workarounds from 3-4 years ago when autofill for Chrome and Firefox did not work with Angular forms.

**Comment by daniellee** [comment]
Think this is fixed now as the login page has been rewritten in React and does not have this Angular form problem anymore. Tested with Keefox and it works on Firefox now. Will reopen if someone is still having problems.
