### ISSUE TITLE
[Bug] Cannot use password containing "!"

### ISSUE THREAD

**Issue by phanohanover** [grafana/grafana#9728]
Grafana v4.4.3 (commit: 54c79c5) 
Influxd & Prometheus
Centos 7.3

Good morning to you, My grafana install works perfect. Thanks to all of you guys!
Question: When setting up email in grafana.ini, it does not interprete the password properly.
IE: 
#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = 1.2.3.4:25
user = some-email@mbslgs.com
password = 2017!Mbs
from_address = some-email@mbslgs.com

In the exemple above, the password contains a "!" and because of this, i am getting authentication fails on the mail server.

Any suggestions on how to encapsulate my password? ( Chnaging the password would be a real headache.

I tried between ' ' and [ ] but it did not work.

SP

**Comment by bergquist** [comment]
Please try using triple quotes. ex `"""2017!Mbs"""

http://docs.grafana.org/installation/configuration/#password

**Comment by phanohanover** [comment]
That did it!

So many thanks for your fast reply.

Best regards,

SP


Stéphane Poissant  <https://ca.linkedin.com/in/phanohanover> Linux
Administrator
@ IBM
78 Principale Sud, Delson, Québec, J5B 1Z6
Portable: 514-793-3506 spoissantca@gmail.com
<https://ca.linkedin.com/in/phanohanover>


<https://ca.linkedin.com/in/phanohanover>


2017-10-30 9:40 GMT-04:00 Carl Bergquist <notifications@github.com>:
