### ISSUE TITLE
Broadcast messages to Grafana users

### ISSUE THREAD

**Issue by GuillaumeConnan** [grafana/grafana#9731]
I just wanted to share a new feature suggestion.

It would be very useful (in the case of highly mutualised Grafana environements) to be able to create broadcast messages (like GitLab for example): a customizable and colored banner that appears at the top of every page, for every users, and for a given timeperiod.

Most of the time, people only consult their own dashboards and not the home dashboard where it is possible to set text messages.
Sharing information with everyone without mass emailing can become complicated.
For example , when a downtime period is needed, it would be much simpler to inform everybody through a little banner a the top of each page.

Thanks in advance !

**Comment by roidelapluie** [comment]
Mybe the messages could also come from annotations. They could also broadcast problems in prod etc.

**Comment by paulsson** [comment]
I would like to voice the opinion that this would be very beneficial for very large organizations, both Granfana Orgs and business organizations.
An excellent use case would be having a way to display a maintenance announcement or that a data source will be removed. There can be many components that get integrated together for building a monitoring service and a lot of times Grafana may be the only user facing UI. Having this capability would be great for broad user communications.

**Comment by adamcstephens** [comment]
The home dashboard can be overridden by users, so it's not an acceptable solution for this feature request.

It would be very helpful to have the ability to broadcast a message to all users. Whether it's planned maintenance, changes to datasources, or other site-wide information, Grafana currently provides no capability to make this visible in-app.

Please consider adding this feature.

**Comment by cruscio** [comment]
Un-stale this please. It's a valuable feature for organizations.

**Comment by joshhunt** [comment]
Small update - It's not on our immediate roadmap, but we are aware of this request and we would like to add this functionality. Hopefully we can get to it 'soon', but no details beyond that.

**Comment by R-Studio** [comment]
@joshhunt any news?

**Comment by joshhunt** [comment]
@R-Studio Nothing to share right now. It's on our roadmap, but no commitments for when it could ship (if at all).

**Comment by Clarity-89** [comment]
Hi, the feature has been completed and is currently being released in Grafana Cloud via the rolling release channels. It is available in Grafana Pro and Advanced versions. Additionally, it will be available in Grafana Enterprise 11.3 via the `notificationBanner` feature toggle. You can find more details about the feature in the [What's New entry](https://grafana.com/docs/grafana-cloud/whats-new/2024-09-10-announcement-banner/).
