### ISSUE TITLE
Dashboard links (settings->link) do not show up in non-dropdown mode

### ISSUE THREAD

**Issue by XANi** [grafana/grafana#9732]
"dashboard" links no longer generate correctly in non-dropdown mode

Sadly I can't remeber when it actually worked (it did at some point, we had that in our grafana instance) but on our inhouse 4.6.0 and on http://play.grafana.org:

With dropdown ON:

![zaznaczenie_2017-10-30_002](https://user-images.githubusercontent.com/147394/32183374-6e4a4260-bd99-11e7-87f8-a6eb060cca7d.png)

Without

![zaznaczenie_2017-10-30_001](https://user-images.githubusercontent.com/147394/32183383-74b41e64-bd99-11e7-9e09-0f83d209c86c.png)

Now when I switch "type" to link and back, it starts to show up

![zaznaczenie_2017-10-30_003](https://user-images.githubusercontent.com/147394/32183467-a9b315c0-bd99-11e7-8bfc-0c6eab672e29.png)

and on our internal grafana it also happens *when there is no tag filter*, with tag filter no matter what I do it only shows up when I switch to "with dropdown" mode

**Comment by torkelo** [comment]
thanks for reporting this! fixed in master/v4.7

**Comment by XANi** [comment]
I've applied that patch and it fixed the issue with generating links in non-dropdown mode, however behavior of "as dropdown" field is still a bit wonky:

![1](https://user-images.githubusercontent.com/147394/32230159-d0ab9940-be52-11e7-8a65-fd8aabf281db.gif)

It works correctly after saving dashboard and re-loading page

**Comment by torkelo** [comment]
strange, did you apply the patch ?

**Comment by XANi** [comment]
That was only one line patch right ?

    [18:18:02] ^ [~/src/os/grafana/public/app/features/dashlinks] {(remotes/origin/golang-1.9.2~1)}
    -> ᛯ sha1sum editor.html
    8d0b51e31b274f63bb585c5ba5d9671c02dd6431  editor.html
    [18:17:59]hal1:/usr/share/grafana/public/app/features/dashlinks☠ sha1sum editor.html 
    8d0b51e31b274f63bb585c5ba5d9671c02dd6431  editor.html

**Comment by torkelo** [comment]
Yes but you can't patch that file, as it's bundled in the boot js file in production builds

**Comment by XANi** [comment]
Will that change be in current nightly build or do I have to compile it from scratch ?

**Comment by torkelo** [comment]
it's in nightly

**Comment by iwittkau** [comment]
This is broken again in my `5.2.2 (aeaf7b2)` instance. Should I open a new issue for that?

**Comment by iwittkau** [comment]
@marefr I just found #11203. That was the issue. Dashbord link search is limited to `7`. Would be nice to have a hint somewhere in the settings at " Dashboard Links > Edit". Something like "Only seven links are shown, use dropdown to show more.".
