### ISSUE TITLE
[Bug] Cannot connect to Zabbix datasource after upgrading to 4.7.0

### ISSUE THREAD

**Issue by marcelo-salvatori** [grafana/grafana#9733]
Please include this information:
- What Grafana version are you using?
4.7.0/4.6.0
- What datasource are you using?
Zabbix
- What OS are you running grafana on?
Centos 7
- What did you do?
Upgraded from 4.3.0 to 4.7.0
- What was the expected result?
To see things working just as fine as before
- What happened instead?
Granfana can't connect to Zabbix datasource.
It returns the message: Could not connect to given url

Log:
t=2017-10-30T13:39:59-0300 lvl=info msg="Request Completed" logger=context userId=20 orgId=1 uname=marcelo method=POST path=/api/datasources/proxy/21 status=502 remote_addr=x.x.x.x time_ms=10 size=0 referer=http://x.x.x.x:3000/datasources/edit/21

**Comment by daniellee** [comment]
Dupe of this #9692 ? Are you using AuthProxy? And do you see an error in the Chrome Console?

**Comment by marcelo-salvatori** [comment]
No, and funny thing: it connected now with zabbix 3.2.7, but not with zabbix 3.4.3

**Comment by marcelo-salvatori** [comment]
![grafana](https://user-images.githubusercontent.com/10455019/32187068-a812a706-bd82-11e7-90d7-fe692c337074.jpg)
We also tried to swicth to direct access instead of proxy

**Comment by alexanderzobnin** [comment]
Can you explain, what exactly did you update? Zabbix plugin or Grafana or both?

**Comment by marcelo-salvatori** [comment]
I updated grafana. The zabbix plugins was up-to-date already.

**Comment by marcelo-salvatori** [comment]
Seems like the problem was found:

![grafana1](https://user-images.githubusercontent.com/10455019/32190763-0304e95e-bd96-11e7-947d-ac4ff9befc51.jpg)

![grafan2](https://user-images.githubusercontent.com/10455019/32190762-02e76212-bd96-11e7-9b01-f129ccbcdb6a.jpg)

After cheking the box, it worked. I was wondering if there is anyway it would work with the box unchecked.

**Comment by hsafe** [comment]
That was indeed an issue got into my hair ...alas went astray a lot :(
