### ISSUE TITLE
Annotation filtering based on template variable

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#9735]
- What Grafana version are you using? 4.6
- What did you do?
Added a new Grafana annotation (using the internal —Grafana— datasource) to a templated dashboard. The machine or server that is inspected is templated on our dashboard. I then choose another machine (changed template variable). 
- What was the expected result?
The annotation should disappear it is only valid in the context of the template variable I selected. 
- What happened instead?
The annotation remained visible. I would like to specify the template variables as annotation context in the annotation definition view.

**Comment by Ultraseamus** [comment]
+1

So long as you are filtering your graphs with templates, the annotations need to be filtered as well. The recent annotation work was great, and I think this would be the last piece of the puzzle to make the feature into something my organization uses.

**Comment by Strech** [comment]
@PaulKuiper @Ultraseamus is this PR what are you looking for? https://github.com/grafana/grafana/pull/9864

**Comment by christoph-buente** [comment]
I had the same expectations when adding the annotations to a templated dashboard. I punched in the template variabel $variable to the tag filter, but it would filter literally for the tag "$variable".
Thanks @Strech for the PR.

**Comment by christoph-buente** [comment]
@bergquist are there any plans to integrate this feature in future releases? Either through this PR https://github.com/grafana/grafana/pull/10163 or a separate implementation?

**Comment by kawmarco** [comment]
+1

**Comment by T-One** [comment]
+1

**Comment by pznamensky** [comment]
+1

**Comment by benkeil** [comment]
Any news on this? In an automated environment this feature is a must have.

**Comment by rainmote** [comment]
+1

**Comment by christoph-buente** [comment]
@bergquist @Ijin08 @marefr @xlson @torkelo @alexanderzobnin Any thoughts here?

You added such a great feature with annotations to grafana, but it does not support the most obvious usecase, to have annotations on a chart based on the template variables. Instead they show up on a the graph, wether or not it might be relevant at all.

Would love to get at least some feedback if this feature aligns with your roadmap or is simply not being worked on.

Thank you!

**Comment by eric-ibarra** [comment]
+1 This feature would be really nice

**Comment by mgf909** [comment]
+1 from me too.... This could be so much more powerful!

**Comment by thehackercat** [comment]
+1

**Comment by shivas** [comment]
+1

**Comment by TheStigB** [comment]
+1

**Comment by azharmajeed** [comment]
Hi is this issue really closed? Adding the template variables to the tags seems like a workaround, also under the Query section in the Annotations options if we select Filter by Tags it does not show the annotated lines (dotted lines) on the graph. It would be great if we could visually see the annotated ranges. Please let me know if this makes sense. 

Just to give some context I have 50-60 file_names which I use as variables. Each file_name would have its own annotations. Please let me know if any of y'all had similar use cases.

**Comment by borito1907** [comment]
I'm facing the same issue as azharmajeed.
