### ISSUE TITLE
[bug] template variable queries incorrectly escape dot (".") chars (influxDB)

### ISSUE THREAD

**Issue by dsw6** [grafana/grafana#9744]
- Grafana 4.6.0
- InfluxDB datasource
- Ubuntu 16.x

Template variable queries are used to query influxDB tag values.  Grafana escapes the "." (dots) in the query, which results in a failure from InfluxDB. 

Query:  SHOW TAG VALUES FROM logs WITH KEY=path where host = 'apps.testing.org'

Escaped Query:  SHOW TAG VALUES FROM logs WITH KEY=path where host = 'apps\.testing\.org'

InfluxDB responds with a 400-bad request.  The response body "{"error":"error parsing query: found \\., expected identifier, string, number, bool at line 1, char 89"}"

Sending the query without the escaped "." (dots) results in success.

**Comment by svenklemm** [comment]
You can probably work around this with regular expressions.
This should work:
```sql
SHOW TAG VALUES FROM logs WITH KEY=path where host =~ /^apps.testing.org$/
```

**Comment by phemmer** [comment]
@dsw6 I think you have a copy/paste error in your report. Both your "Query" and "Escaped Query" example are exactly the same.

@svenklemm In your regex example, the dots need to be escaped, other wise `.` will match any character, not just a literal `.`.

**Comment by dsw6** [comment]
Yes, there was a copy paste error.  Should read:
Escaped Query: SHOW TAG VALUES FROM logs WITH KEY=path where host = 'apps\.testing\.org'

@svenklemm  thanks for the suggestion of working around the issue with regular expressions.  I'll investigate.

**Comment by phemmer** [comment]
@dsw6 That's still the same thing :-)
I'm assuming you mean:

    SHOW TAG VALUES FROM logs WITH KEY=path where host = 'apps\.testing\.org'

**Comment by torkelo** [comment]
very strange, dots do not need to be escaped if enclosed in single quotes, this query works for me:
```sql
SELECT mean("value") FROM "logins.count" WHERE ("datacenter" =~ /^America$/ AND "hostname" = '10.1.100.1') AND time >= now() - 1h GROUP BY time(1m), "hostname"
```

**Comment by dsw6** [comment]
@torkelo Your query is a typical query used in the main query editor.  I haven't seen problems with those queries.  The query listed in the issue is from the template variable query editor.  For some reason the template variable query editor escapes the dots.      

@svenklemm Thanks for the regular expression work around.  I was able to get the template variable query to work using regular expressions.

**Comment by torkelo** [comment]
For influxdb the interpolation engine will automatically default to regex escaping of template variables in order to support multi value variables. 

Use `=~ /$variable$/`  syntax 

There is an issue / feature request for more control over escaping:
https://github.com/grafana/grafana/issues/7955
