### ISSUE TITLE
CloudWatch Logs: add support for new query languages

### ISSUE THREAD

**Issue by DColadas** [grafana/grafana#97458]
**Why is this needed**:

CloudWatch Logs recently added support for the OpenSearch PPL and OpenSearch SQL query languages, beyond the existing Logs Insights QL. See the [official announcement](https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-and-amazon-opensearch-service-launch-an-integrated-analytics-experience/) and the [documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData_Languages.html).

Currently, the CloudWatch Logs datasource uses the default Logs Insights QL, and doesn't provide a way to choose the new query languages.

**What would you like to be added**:

Provide a way to use any of the query languages supported by CloudWatch Logs (Logs Insights QL, OpenSearch PPL and OpenSearch SQL).

**Who is this feature for?**

Users of the CloudWatch Logs datasource.

**Comment by idastambuk** [comment]
Hi @DColadas, support for PPL and SQL was just added [in 11.4](https://grafana.com/docs/grafana/next/whatsnew/whats-new-in-v11-4/) 🎉
If you run into any issues of have suggestions for improvements, feel free to open a ticket :)
