### ISSUE TITLE
Grafana CHANGELOG.md to big to generate

### ISSUE THREAD

**Issue by drbobbb** [grafana/grafana#97453]
### What happened?

The usual source of loocking what changed 

 - https://github.com/grafana/grafana/blob/main/CHANGELOG.md

is, when viewed in browser

 - This blob took too long to generate.

### What did you expect to happen?

Move old Changelogs to changelog-archive like in the past

 -  previous CHANGELOG entries can be found in /.changelog-archive 

### Did this work before?

yes

### How do we reproduce it?

 - Go online
 - view changelog in browser

### Grafana platform?

A downloaded binary

**Comment by kminehart** [comment]
https://github.com/grafana/grafana/pull/97448
