### ISSUE TITLE
List of available panels is not scrollable

### ISSUE THREAD

**Issue by m0nhawk** [grafana/grafana#9746]
- What Grafana version are you using?
I have noticed it few releases before 4.6.0 and 4.6.0 also have this issue.

- What did you do?
"Add panel" to the row.

- What was the expected result?
List of panels should be scrollable, to have all panels available.

- What happened instead?
List of panels are not scrollable, thus only few of panels available.

Screenshot of missing scrollbar.
![default](https://user-images.githubusercontent.com/8220926/32245392-4892ba66-be84-11e7-9a81-59412d3bda6b.png)

**Comment by daniellee** [comment]
Which browser and which OS are you using?

**Comment by daniellee** [comment]
Confirmed.
