### ISSUE TITLE
Time Range 'now' is client-time, not server-time.

### ISSUE THREAD

**Issue by PhilSmithABB** [grafana/grafana#9755]
**What Grafana version are you using?**
4.5.2
**What datasource are you using?**
Our own, proprietary data source (ABB's real time database)
**What OS are you running grafana on?**
Windows 2012
**What did you do?**
Set the Time Range as *From: now-3h*, *To: now* 
**What was the expected result?**
That we would get the latest data from our database
**What happened instead?**
We got data from current time on client, to three hours before. The server and client machines were set to different time zones with an one hour time difference between them. This resulted in the data received being one hour old, we were expecting the latest data. This was part of test to see how Grafana works across time zones.

**_Suggested Fix_**
I've two suggested fixes for this, the first being my preference as it's less ambivalent: 
1. Include an option for 'server-now' (or something like that) so Grafana uses server-time instead of client-time
 2. 'now' means now on the server

**Comment by torkelo** [comment]
you can control this in your data source, grafana sends raw time range strings int the range.raw property. 

This used by some other data sources to send "now" to the data source backend.

**Comment by torkelo** [comment]
see https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/datasource.ts#L31 

that code is using the old rangeRaw property (depricated), use range.raw instead
