### ISSUE TITLE
Prometheus 2.0 default dashboard

### ISSUE THREAD

**Issue by Gouthamve** [grafana/grafana#9759]
Hi, as you might be aware, Prometheus 2.0 is nearing release and it is incompatible with the current default dashboard. I am willing to contribute the initial dashboard, but we need to support both 1.x and 2.x for now, is there a in-built mechanism for supporting 2 dashboard versions of a datasource?

Ref: https://github.com/prometheus/prometheus/issues/3388

**Comment by cboggs** [comment]
It might be fine to have an entirely separate dashboard for 2.0, considering how few metrics carry over from 1.x. I think it would make it a cleaner transition and avoid trying the struggle of conditionally showing certain metrics.

Thoughts?

**Comment by bergquist** [comment]
Two different dashboards make sense if the metrics are breaking. 

I recently added a Grafana dashboard for the Prometheus data source. This is how to do it: 
https://github.com/grafana/grafana/commit/beb203209b6d7b2236995434ddcd47f346d27ab8 

You could either open a PR or just paste the dashboard in the issue and I will bundle it in Grafana.

**Comment by danielmarbach** [comment]
Did you guys see https://grafana.com/dashboards/3662 ?

**Comment by josephholsten** [comment]
Absolutely terrible, no good, worthless reason to update the existing one: it's got dashboard ID `2`! It was the one community dashboard I didn't need to look up to use.

Whatever conclusion this ticket comes to, it would be really nice to have a way to kn

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/9762
