### ISSUE TITLE
Grafana internal metrics not being sent to graphite after 4.6.0 upgrade

### ISSUE THREAD

**Issue by Jonnymcc** [grafana/grafana#9760]
Upgraded to 4.6.0 and internal metrics stopped appearing in graphite. /metrics endpoint works though.
https://grafana.com/dashboards/55
aliasByNode(scaleToSeconds($prefix.*.api.dataproxy.request.all.count, 1), 2)

**Comment by bergquist** [comment]
We had a breaking change in how metrics are sent to graphite introduced in [4.5.2](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#breaking-changes) (by mistake) 

Seems like we forgot to update the dashboard with information about this. We also need to create a new dashboard with the new metric path's

**Comment by daks** [comment]
I'm facing the same problem. My actual dashboard does not work anymore. As I saw the warning in the changelog, I was prepared to update my dashboard.

But I can't find where are the new metrics, or how they are organized, in my Graphite server.

**Comment by daks** [comment]
I finally found my metrics but there is still a bug with their name, they are in `app.grafana._instance_name_`. _instance_name_ is used litteraly and not my server name.

**Comment by Jonnymcc** [comment]
@bergquist I do see metrics being sent to graphite, looks like the metric names have changed from what is used in that dashboard. Is there any work being done to update that dashboard?

**Comment by Jonnymcc** [comment]
I created a PR to fix the paths in the Grafana internal stats dashboard. https://github.com/torkelo/dashboards/pull/9

**Comment by Jonnymcc** [comment]
Since my PR above was merged and the metrics are still available (metric names have changed) I think this issue can be closed.

**Comment by daks** [comment]
@Jonnymcc I'm not sure, as I said above: my problem was not coming only from a not-updated dashboard but also from the fact that `prefix = app.grafana.%instance_name%` does not work.

**Comment by Jonnymcc** [comment]
@daks The change to the above format in the PR you linked to was reverted the following day. https://github.com/grafana/grafana/commit/ebecc5e5a0e025f4b64ae59dccaba844e8cf37bf#diff-b043a86af3c1c53714ffdc4400249921R308

**Comment by daks** [comment]
@Jonnymcc strange, because I just upgraded (to 4.6.3) and checked my instance and with the following config:
```
prefix = app.grafana.%(instance_name)s
```
I still receive all metrics in separate directories
```
$ ls /opt/graphite/storage/whisper/app/grafana/
...
drwxr-xr-x  8 www-data www-data 4096 Feb 19 16:29 server_domain_tld_api
drwxr-xr-x  3 www-data www-data 4096 Feb 19 16:34 server_domain_tldalerting
drwxr-xr-x  4 www-data www-data 4096 Feb 19 16:34 server_domain_tldaws
drwxr-xr-x  2 www-data www-data 4096 Feb 19 16:34 server_domain_tldstat
drwxr-xr-x  3 www-data www-data 4096 Feb 19 16:34 server_domain_tlddb
drwxr-xr-x 17 www-data www-data 4096 Feb 19 16:34 server_domain_tldapi
drwxr-xr-x  8 www-data www-data 4096 Feb 19 16:34 server_domain_tldgo
drwxr-xr-x 24 www-data www-data 4096 Feb 19 16:34 .
drwxr-xr-x  2 www-data www-data 4096 Feb 19 16:34 server_domain_tldinstance_start_total
drwxr-xr-x  3 www-data www-data 4096 Feb 19 16:34 server_domain_tldprocess
```

What I'm looking for, and how Grafana used to send its internal metrics, it's create a `server_domain_tld` directory and then store all metrics inside.

I changed the prefix setting to add the ending slash `prefix = app.grafana.%(instance_name)s/` but it seems to not solve my problem.

**Comment by torkelo** [comment]
@daks that is how graphite's data store (whisper) works, it creates directories for each part of the metric name.

**Comment by torkelo** [comment]
Just make sure the prefix ends with a dot, that will fix your problem

**Comment by daks** [comment]
I know how Graphite Whisper works, but not how Grafana does :)

After a **cold restart** (stop && start, not restart) of Grafana service, it seems that metrics are now sent to correct path, which is `app.grafana.server.foo`, `app.grafana.server.bar`. _(And not `app.grafana.serverfoo` or `app.grafana.server_bar` like it was until now)_

No need to ending prefix with dot, which would have been weird.

**Comment by daks** [comment]
_[previous comment deleted]_

**Comment by daks** [comment]
I know how Graphite Whisper works, but not how Grafana does :)

After a cold restart (stop && start, not restart) of Grafana service, it seems that metrics are now sent to correct path, which is app.grafana.server.foo, app.grafana.server.bar. (And not app.grafana.serverfoo or app.grafana.server_bar like it was until now)

And in fact prefix must end with a dot which is a little bit weird, but behave life before.

Thanks for your help.

**Comment by bennyboom38** [comment]
Hello
I'm using the version 5.4.2 and I try to get internal stats from Grafana, but nothing is get by Graphite.
Do you know if we can check grafana is well displaying metrics by reaching something like :
http://<graphite server>:3000/api/metrics ? 

Thanks a lot for your help

**Comment by marefr** [comment]
@bennyboom38 please see [documentation](http://docs.grafana.org/installation/configuration/#metrics-graphite). 

You can expose prometheus metrics which a prometheus server can scrape, see [documentation](http://docs.grafana.org/installation/configuration/#metrics). Metrics are available at `http://grafana host name and port>/metrics.

**Comment by bennyboom38** [comment]
@marefr your first link to the documentation said : "Include this section if you want to send internal Grafana metrics to Graphite." 
I don't have prometheus installed , only Graphite.
Thanks for the grafana metrics url, I can see grafana metrics.
How to see if grafana is well sending metrics to graphite? 

Thanks for your help

**Comment by marefr** [comment]
> How to see if grafana is well sending metrics to graphite?

I think that you should be able to see that in the Grafana server log. To be on the safe side I would recommend to enable debug logging of the metrics logger using following config and restart Grafana:

```
[log]
filters = metrics:debug
```
