### ISSUE TITLE
Explore: "line contains" field in logs search cannot be emptied once a value is set under latest Grafana Cloud version

### ISSUE THREAD

**Issue by tipani86** [grafana/grafana#97618]
### What happened?

Grafana Cloud > Explore > your-profile-logs (Loki)

![Image](https://github.com/user-attachments/assets/9ababf33-5ea7-4dfa-a743-7cd04b8cf88d)

One performs some log search by specifying some filters such as `job` or `level` or whatever, followed by a default `Line contains` operation which we treat as text search.

If you leave the `Line contains` field empty, it will return the latest log lines from the time window specified on the top. If you enter some text into the field, it only selects those log lines that the search substring appears in.

All good until now.

However, after a recent Grafana Cloud version update, you cannot delete the text within the `Line contains` field anymore. It's sticky that once you empty it of all characters, it will pop the original search string back in full. You can, however, write another string to replace it. Just cannot clear it entirely.

You'll have to delete the whole `Line contains` operation from the query to get back to the full search (all log lines), and then add it back if you want to again only filter some lines containing another substring. It's a small nitpick, but this deleting and adding back a whole operation to just toggle a search phrase on/off kind of kills my log search flow.

Note: This same bug may also apply to other fields, I just didn't try out others as I am mainly using the `Line contains` one.

### What did you expect to happen?

Earlier version behavior:

Just empty the `Line contains` field and it stays empty. Then the subsequent query run will be a full search again.

### Did this work before?

See "What did you expect to happen" above. The previous Grafana Cloud version worked like that.

### How do we reproduce it?

1. Use latest Grafana Cloud
2. Under Explore > your-profile-logs (Loki) perform some search with `Line contains` operation on
3. Try to delete the substring in that field after you ran the initial search. Doesn't matter if there were hits or not. But now you cannot delete the text in the `Line contains` field anymore!

### Environment (with versions)?

Grafana: Cloud
OS: Happens on both Windows (11) and Mac (don't remember exactly, I think it was Ventura)
Browser: Firefox

### Grafana platform?

I use Grafana Cloud

**Comment by matyax** [comment]
Thanks for reporting this issue! This was fixed by https://github.com/grafana/grafana/pull/97551
