### ISSUE TITLE
[bug] Broken graphs after editing rgb colours for series `aliasColors`

### ISSUE THREAD

**Issue by cas--** [grafana/grafana#9769]
I was changing the series colour to a custom rgb colour and then copied and pasted the value from the dialog to the other graphs. It all looked fine when editing but after saving all the graphs turned black with no way to edit colour:

![selection_073](https://user-images.githubusercontent.com/606038/32319278-f38eb932-bfb1-11e7-90f7-c97f6edbd7f4.png)

investigating the json diff I see the following extra content in `aliasColors`
![selection_072](https://user-images.githubusercontent.com/606038/32319639-2d5aca4c-bfb3-11e7-8cde-b0ba227204e4.png)

I have also found that __any__ manual modifications of the rgb values in the dialog will break the graphs colours. The same issue occurs with modifying the entire hex value.
 
This is on hosted grafana: https://niteo.grafana.net

**Comment by torkelo** [comment]
yes, can replicate. Looks like a bug that occurs whenever you use the text input field to set a color. 
Thanks for reporting this!

**Comment by Saliva520319** [comment]
I also meet this bug, any solutions?

**Comment by cas--** [comment]
To fix it you need to update the json for the panel in `Panel JSON` by removing all those additional line in `aliasColors`.

![selection_071](https://user-images.githubusercontent.com/606038/32367823-7088debc-c07b-11e7-9ad2-27cd4bbe4821.png)
