### ISSUE TITLE
[UX] Don't hide graph display options (Lines/Points) when draw mode is unchecked

### ISSUE THREAD

**Issue by cas--** [grafana/grafana#9770]
If you untick all draw modes and only set them in series override you will find that any mode options from the Draw options tab will still apply such a `fill` or `line width` even though they are hidden. 

I would expect that if the `Mode Options` are hidden then it reverts to the defaults in series override.

The workaround is to go to Draw options tab, tick label, change all the mode options to the default values and then untick label.

Hosted grafana: https://niteo.grafana.net

**Comment by torkelo** [comment]
Not sure reseting the options when you temporarily disable say lines is a good thing, think having those options still there makes sense as you frequently switch modes and experiment and constantly having them revert to default is not very nice.

**Comment by cas--** [comment]
Why is this being closed?

The mode options should not be hidden as it's bad UI design and not obvious where values are coming from

**Comment by cas--** [comment]
I am not talking about actually resetting the values in options. What I mean is that if a mode is unticked in Draw options tab then the global options apply not the user set one that are now hidden

**Comment by torkelo** [comment]
your right, we can disable the hiding of the draw options instead
