### ISSUE TITLE
OrganizationSwitcher: Incorrect URL on selection

### ISSUE THREAD

**Issue by CuteLeon** [grafana/grafana#97712]
### What happened?

Bug triggered when switching organizations in self-deployed Grafana:
1. Deploy Grafana on machine-A, and login on machine-B
> ![Image](https://github.com/user-attachments/assets/abec5875-2adf-428a-8b83-7bf5b290933c)
2. Try to switch Org
> ![Image](https://github.com/user-attachments/assets/5f876d57-2289-4b62-91ab-ad8fd8bc4450)
3. Host address was replaced by "localhost", and caused "404" error
> ![Image](https://github.com/user-attachments/assets/3f8e9ba3-baf5-4462-9168-afb08b1c947c)

### What did you expect to happen?

Hopes to switch Orgs and keep correct host address.

### Did this work before?

Have no idea.

### How do we reproduce it?

1. Deploy Grafana on machine-A, and login on machine-B
2. Click Org to switch
3. Host address was replaced by "localhost", and caused "404" error

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:Grafana v11.3.1 (9225f4a1cb)
OS:WindowsServer 2022
Browser:Chrome 131.0.6778.109

### Grafana platform?

A downloaded binary

**Comment by yincongcyincong** [comment]
i think this pr fixes this issue. but no one review it.
https://github.com/grafana/grafana/pull/96521

**Comment by ashharrison90** [comment]
fixed by https://github.com/grafana/grafana/pull/96521
