### ISSUE TITLE
Navigation: Show dashboard folders, subfolders, and individual dashboards in left navigation menu

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#97756]
**Why is this needed**:

In the left navigation menu, there is a header for "Dashboards", but this menu item does not allow you to drill down any further into dashboard folders or subfolders. This would be a lot more convenient for navigating through dashboards.

The inspiration is VMWare, which has this in a secondary menu 

![Image](https://github.com/user-attachments/assets/7b95a958-f75c-4cc7-bb3e-85c1d1447a35)

**What would you like to be added**:

A way to navigate through dashboard folders and dashboards without needing to use the entire page.

**Comment by gelicia** [comment]
Request comes from community slack https://grafana.slack.com/archives/C0Y4TLW74/p1733843429049969

**Comment by ashharrison90** [comment]
hi, thanks for the feature request! 🙂 

we don't think this would be an appropriate solution. we are exploring solutions to this problem internally, mostly around making the breadcrumbs more interactive.
