### ISSUE TITLE
Add support for passing credentials when deploying plugins from custom urls.

### ISSUE THREAD

**Issue by drishti1400** [grafana/grafana#97772]
**Why is this needed**:

When downloading plugins from a private repository only url env variable is there, no way to pass on credentials securely with it which are needed in case the repository has blocked anonymous user  access.
https://github.com/grafana/grafana/blob/3724ffd8589aaae1528a6d9b562521ee5eda20af/packaging/docker/run.sh#L73

**What would you like to be added**:

Support to pass the credentials as an env variable or securely through the plugin url.

**Comment by andresmgot** [comment]
Closing as duplicated of #97616, please add your comments there.
