### ISSUE TITLE
Cannot install plugins when I install grafana and plugins through a a script. But it works fine when installed manually.

### ISSUE THREAD

**Issue by rohitbagde** [grafana/grafana#9778]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by rohitbagde** [comment]
I am using grafana_4.6.0. and i am using gnocchixyz-gnocchi-datasource datasource and running on ubuntu. I am trying to insatll grafana plugins through a script where after insatlling the grafana I install plugins using query 'grafana-cli plugins install gnocchixyz-gnocchi-datasource'. The problem is when I install it through script, and execute cli 'grafana-cli plgins ls' to list installed plugins it shows gnocchi plugin as installed. But that plugin is not shown in grafana dashboard and I cannot add datasource of that plugin. But when I install plugins manually without using script, It works fine. Can anyone please help me with this

**Comment by torkelo** [comment]
please use community site for questions. 

> "Could not scan dir "/var/lib/grafana/plugins" error: open /var/lib/grafana/plugins: permission denied" in grafana logs.

Seems you have a permission issue, where the user running grafana-server (grafana by default) is not allowed to access the plugins dir.

**Comment by rohitbagde** [comment]
Then how to resolve this issue? When i install plugins manually one by one. It does not give any permission issue.

**Comment by torkelo** [comment]
after the script is done make sure grafana user has permission to read /var/lib/grafana/plugins
