### ISSUE TITLE
Docs: Clarify Azure monitor config option

### ISSUE THREAD

**Issue by lwandz13** [grafana/grafana#97794]
A Solutions Engineer provided feedback that the language under "Configure Managed Identity" needs to provide clearer detail that this option is only for Grafana Enterprise users and doesn't apply to Cloud

See Slack thread:
https://raintank-corp.slack.com/archives/C03MW34JP0U/p1733913005342559

I will add a clear admonition to the top of this section. 

This authentication method is only available on [Azure managed grafana](https://azure.microsoft.com/en-us/products/managed-grafana) or Grafana Enterprise, which the customer runs on Azure.

**Comment by kayodeprinceMS** [comment]
This option is also available in OSS Grafana running on Azure compute with Managed Identity enabled. It is not limited to Grafana Enterprise. https://learn.microsoft.com/en-us/azure/azure-monitor/visualize/grafana-plugin#use-managed-identity
