### ISSUE TITLE
SingleStat Value mapping to threshold

### ISSUE THREAD

**Issue by felixPG** [grafana/grafana#9781]
Hi:

In singlestat panel when we make a value mapping from NULL to 0 is convenient that this value (0) could be taken as threshold value too. 
For example: mapping from NULL to 0, then (when NULL values are returned) if threshold are 0.6,0.9 the color in the singlestat become green or red, or whatever that we have defined in threshold, taken mapped values as values too and not only as string!

**Comment by torkelo** [comment]
dupliate of https://github.com/grafana/grafana/issues/8404
