### ISSUE TITLE
No data displayed after upgrade to 4.6.x

### ISSUE THREAD

**Issue by song860918** [grafana/grafana#9783]
- What Grafana version are you using?
4.6.x
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
Upgraded to 4.6.0 /4.6.1
- What was the expected result?
Grafana works as normal
- What happened instead?
Grafana stop displaying any data

Before upgrade:
![screen shot 2017-11-03 at 9 54 26 am](https://user-images.githubusercontent.com/6957388/32386000-0f003468-c07d-11e7-9470-7ce28813d0e2.png)

After upgrade:
![screen shot 2017-11-03 at 9 51 11 am](https://user-images.githubusercontent.com/6957388/32385833-97a865f2-c07c-11e7-842d-6fc2b5cb744b.png)

I find the following in the log:
error="tsdb.HandleRequest() error Post https://127.0.0.1:443/render: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs" changing state to=keep_state

Can you suggest what to do here?

**Comment by torkelo** [comment]
in v4.6 Grafana by default verifies https certs,
https://github.com/grafana/grafana/pull/9377 

you can skip verification by toggling skip tls verification in data source settings
