### ISSUE TITLE
Docs: UPGRADING_DEPENDENCIES guide needs to reference makefile target

### ISSUE THREAD

**Issue by Proximyst** [grafana/grafana#97842]
The [upgrading dependencies guide](https://github.com/grafana/grafana/blob/main/contribute/UPGRADING_DEPENDENCIES.md) currently only references `go mod tidy` when updating dependencies. It should also mention (or maybe only mention?) the `make update-workspace` target, especially when updating more central dependencies.

**Comment by rgoltz** [comment]
Thanks for opening this issue, Mariell. I was struggling with these exact steps/details. Next time I try I'll keep this page in mind (and the make update-workspace command too) - If I can contribute to this guide I'll also make a PR.

**Comment by Proximyst** [comment]
@rgoltz That's wonderful. I am thinking of addressing these docs changes next week if nobody has by then :)
