### ISSUE TITLE
Failed at the grafana@4.7.0-pre1 build script

### ISSUE THREAD

**Issue by mengjoel** [grafana/grafana#9790]
Hello, 
 - What Grafana version are you using?- 4.7.0-pre1
- What datasource are you using?
- What OS are you running grafana on? -windows 64bit
- What did you do? -Building Grafana from source
- What was the expected result?-Build successfully
- What happened instead?--Failed at the grafana@4.7.0-pre1 build script 

When i exec the command of 'yarn install --pure-lockfile' meet the following warning:
`warning "sass-loader@6.0.6" has unmet peer dependency "node-sass@^4.0.0".`

And when i  exec the command of 'npm run build',meet the following errors:
```
E:\go_workspace\src\github.com\grafana\grafana\node_modules\.bin\grunt:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grafana@4.7.0-pre1 build: `node ./node_modules/.bin/grunt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grafana@4.7.0-pre1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2017-11-05T14_17_49
_824Z-debug.log

E:\go_workspace\src\github.com\grafana\grafana>npm run build--ignore-scripts
npm ERR! missing script: build--ignore-scripts

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2017-11-05T14_20_46
_016Z-debug.log

```
Any help will be appreciated. 
Thanks in advance.

**Comment by mliyanagamage** [comment]
Are you running that in cmd or in the the linux subsystem or in git bash or something? Cause its failing on the command `dirname` which is a bash command

**Comment by mengjoel** [comment]
I running that in cmd. @mliyanagamage

**Comment by mliyanagamage** [comment]
I am not sure if grafana runs on Windows natively

**Comment by bergquist** [comment]
Grafana should run on Windows. ( https://grafana.com/grafana/download?platform=windows )

@mengjoel Any chance you could try building it in Powershell instead?

**Comment by GapiSla** [comment]
Same issue here. Just run `grunt` command in the root directory and it should run fine.

**Comment by daniellee** [comment]
These are the [building from source](http://docs.grafana.org/project/building_from_source/) instructions. I don’t see anything about running npm run build. Do we have incorrect documentation somewhere? 

To build the front end code:

npm run watch

To build the backend:

bra run

**Comment by GapiSla** [comment]
@danielle see the image below.

![doc_error](https://user-images.githubusercontent.com/25174514/32479006-1fde97e4-c388-11e7-9c49-3840ac4ac9f7.PNG)

**Comment by mengjoel** [comment]
Thank everybody.I have tried many times,but it doesn't work.

**Comment by daniellee** [comment]
@mengjoel I could recreate your error and also noticed that the new jest tests don't run on Windows either (both due to path problems). Fix coming in a few minutes.
