### ISSUE TITLE
Graph Histogram mode - individual histogram for each series

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#9792]
In the current implementation, histogram mode converts all data point in the graph to single histogram. This is useful for most cases, but I think it's good to have also per-series histogram for comparing at the one graph. In this mode, I think it's better to use lines instead of bars, but not sure.

**Comment by mtanda** [comment]
It might be https://github.com/grafana/grafana/pull/8613 ?

**Comment by alexanderzobnin** [comment]
@mtanda Yea, if it was rebased, we can review it and try to merge.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by leeoniya** [comment]
@pkolyvas @alexanderzobnin we now have independent histogram support in the new Histogram panel.
