### ISSUE TITLE
[Issue] No Data when having data

### ISSUE THREAD

**Issue by sonchu** [grafana/grafana#9793]
- What Grafana version are you using?
4.6.1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Centos 7
- What did you do?
Enable alert on graph
- What was the expected result?
Running smoothly
- What happened instead?
Got [No Data] when still having data

I am experiencing a lot of [No Data] alert from more than 100 alerts randomly. The strange thing is the data is still available on graph but Grafana alerted me [No Data] and after 1 minute is OK alert. Please take a look at this graph for example:
https://uphinhnhanh.com/image/MNnTjv

Could you please advise?

Thanks in advance.

**Comment by torkelo** [comment]
make sure your group by time is not not to small or your alert query time range is not too small, what reducer are you using in your alert query (avg, min, last etc). 

If you still think it's wrong please include the time range of your alert query and the response from influxdb

**Comment by sonchu** [comment]
My group by time is 30s, query time range is 1 minute, the reducer is last value. Do you see any issues there? 

Sorry I am new to Grafana so what do you mean about time range of my alert query? And how can i get the response from influxdb to provide you?

Please advise.

Thanks in advance.

**Comment by torkelo** [comment]
how often do you write data? what is the normal distance (in time) between two data points?

**Comment by torkelo** [comment]
Do you have a fill(null) in your query?

**Comment by sonchu** [comment]
i write data every 30s. And yes i have a fill(null) in my query. My alert data has 0 and 1 only. If below 1 then an alert will be fired. I have noticed that when i have changed fill(null) to fill(0) then i have got alert after about 10 minutes and the alert from graph showed value 0 and it changed to 1 afterward. Not sure what happened.

Could you please advise?

Thanks in advance.

**Comment by torkelo** [comment]
If you use last value and time range 1m, then you will get null as last value often, maybe change so you alert on time range 2m, now-1m

**Comment by sonchu** [comment]
Sorry could you please explain a little bit about "If you use last value and time range 1m, then you will get null as last value often"? I don't understand. I will give my alert a try with your value to see if it works.

Thanks in advance.
