### ISSUE TITLE
grafana / prometheus | datasource as variable, only first datasource get processed, others ignored

### ISSUE THREAD

**Issue by matth-c3** [grafana/grafana#9794]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?  
   grafana-4.6.1-1.x86_64

- What datasource are you using?
   prometheus-1.8.2.linux-amd64.tar.gz 

- What OS are you running grafana on?
   aws amazon

- What did you do?
   I have several prometheus datasource . I created a templating variable : 
   name : datasources;
   type : datasource;
   Data source options : prometheus;

   This create a variable with the list of my datasource.  

   Following that, I created a second templating variable:
   - name datasourceJobs;
   - type : Query;
   - Datasource : I select the variable $datasources created previously;
   - Query : label_values(up, job)

- What was the expected result?
   The new variable should contains the list of the jobs present in each datasource represented by the variable $datasources;

- What happened instead?
   Only the first datasource returned by $datasources is processed

For example  : 

if $datasources is listing : 
  - datasource1
  - datasource2
  - datasource3

When processing, only the datasource1 is treated. 

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Thank you by advance.

**Comment by torkelo** [comment]
datasource variables only support a single value at a time (ie not multi value) so you cannot issue queries against all your data sources at once

**Comment by matth-c3** [comment]
What's the purpose to create variable type Datasource then ?

**Comment by torkelo** [comment]
to be able to switch the datasource for many/all panels on one dashboard at once without having to create separate dashboards for each Prometheus instance.

**Comment by fas3r** [comment]
Do you know if there is a way to achieve what he is describing ? Thanks

**Comment by torkelo** [comment]
no, if you want to query multiple prometheus instances and combine the results you need to a prometheus instances that scrapes your other Prometheus instances and collects data from all.

**Comment by fas3r** [comment]
Hello torleko,

Thank you for your answer, Are you referring to federation ?  
If that’s so, I tried, the only thing that I could retrieve from the federate node on grafana level was the metric scrape_job and the name of my slave  Prometheus , but nothing (no metric) related to the host monitored by those slave Prometheus. 
Do I need to create / add something specific on the slave Prometheus configuration to export the metrics to the federated node ? Maybe some rules to extract the metrics? 
Soorry but the documentation is a bit light regarding that part .

Thanks

**Comment by torkelo** [comment]
not sure how federation works actually, think it should be able to get all the data from all Prometheus servers as well. checkout the prometheus docs.

**Comment by fas3r** [comment]
the doc is almost inexistant, i will not talk about the integration/interoperability with graham...
