### ISSUE TITLE
POSTing an annotation does not return its ID

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#9798]
When we POST an annotation with the http api

It would be great to get the ID of the new annotation in the response

**Comment by natalysheinin** [comment]
@roidelapluie can you include which files I can look at to get started since this is marked beginner friendly?

**Comment by roidelapluie** [comment]
@nadezhdamosunova Welcome!

https://github.com/grafana/grafana/blob/master/pkg/api/annotations.go is a good start.

**Comment by mozey** [comment]
So for returning the ID there are two options?
- Change parameters for [ApiSuccess](https://github.com/grafana/grafana/blob/master/pkg/api/common.go#L79) fn so the ID can be passed in
- Make ID a part of the `message string` and the client has to parse it

The first requires many changes in various files and the second seems like a hack. Is there another option?

**Comment by torkelo** [comment]
You can return an ok message and an id, done in a few other places, like when creating a new datasource

**Comment by torkelo** [comment]
for reference use this: https://github.com/grafana/grafana/blob/master/pkg/api/datasources.go#L123
