### ISSUE TITLE
Using mySQL for session storage. FAILED on service start

### ISSUE THREAD

**Issue by luketopa** [grafana/grafana#9800]
Grafana v4.5.2 / centos 7

Hello,

I am trying to configure a HA instance of Grafana. I have a 4 node cluster, all instances share a connection to a mySQL DB. This is configured correctly and works as expected. 

My issue is with the 'session' storage. I have amended my grafana.ini (/etc/grafana/grafana.ini) to include the below.

provider = mysql
provider_config = grafanadb:xxxxxx@tcp(172.0.0.0):3306/hagrafanadb

cookie_name = grafana_sess
cookie_secure = false
session_life_time = 86400

On my Database I created the following table

CREATE TABLE `session` (
    `key`       CHAR(16) NOT NULL,
    `data`      BLOB,
    `expiry`    INT(11) UNSIGNED NOT NULL,
    PRIMARY KEY (`key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

When I attempt to start the service, I just get a FAILED. Nothing gets written to the logs?

>sudo service grafana-server start
FAILED

Have I missed something? My instances can ping my DB and I know the connection string is correct. What else do I need to consider?

**Comment by daniellee** [comment]
What does the config for logging look like? You should be able to log to a file and see the real error.

**Comment by luketopa** [comment]
Hi Thanks for replying,


I set logger to Debug


t=2017-11-07T00:21:15+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-11-07T00:21:15+0000 lvl=info msg="Registering plugin" logger=plugins name=TSRead
t=2017-11-07T00:21:15+0000 lvl=dbug msg="Checking for updates"
t=2017-11-07T00:21:15+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-11-07T00:21:15+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-11-07T00:21:15+0000 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/grafana-tsread-datasource dir=/var/lib/grafana/plugins/grafana-tsread-datasource-0.0.5

FAILED - Nothing further gets wrote. tsread is a custom datasource but shouldn't affect this should it?






Hashing out the session provider, provider_config.

Starts without Issue.

t=2017-11-07T00:21:15+0000 lvl=info msg="Initializing Stream Manager"
t=2017-11-07T00:21:15+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2017-11-07T00:21:16+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2017-11-07T00:21:20+0000 lvl=dbug msg="Looking for App Dashboard Updates" logger=plugins
t=2017-11-07T00:21:26+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2017-11-07T00:21:36+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2017-11-07T00:21:46+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2017-11-07T00:21:56+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2017-11-07T00:22:06+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0

**Comment by luketopa** [comment]
Sorry total typo! I sat down for 15min emptied my head, came back and spotted it!

provider_config = grafanadb:xxxxxx@tcp(172.0.0.0):3306/hagrafanadb

provider_config = grafanadb:xxxxxx@tcp(172.0.0.0:3306)/hagrafanadb

**Comment by daniellee** [comment]
Great that you fixed it!
