### ISSUE TITLE
Check a user is part of 2 AD Groups

### ISSUE THREAD

**Issue by srosenf** [grafana/grafana#9801]
- What Grafana version are you using?
   4.5.2

- What datasource are you using?
   ElasticSearch

- What OS are you running grafana on?
   RHEL 7.4

- What did you do?
   I am trying to setup a way to verify that a user is a member of 2 CNs for LDAP logins but am unsure as there isn't much documentation for this type of thing. We want to make sure they are entitled to the specific dashboard content that would be provided by that ORG as our unit has it's own OU but want to verify that they are also part of the OU that their ORG is as well.

- What was the expected result?
   As long as the member is part of the 2 CNs they will be allowed to login, otherwise the login is rejected.

- What happened instead?
   Unsure how to get this functionality

Thank you,
Stuart Rosenfeld

**Comment by torkelo** [comment]
The Grafana ldap integration does not support this scenario (and will likely not, until we rewrite the ldap integration)
