### ISSUE TITLE
Add a new option to reduce the size of the padding (table panel)

### ISSUE THREAD

**Issue by LucasArona** [grafana/grafana#9802]
There should be an option to reduce the size of the table cells padding to use the space more efficiently. I've already opened a thread on community.grafana.com:
https://community.grafana.com/t/reducing-the-padding-of-the-table-cells/3566

**Comment by torkelo** [comment]
not sure we need this option, if this is big requirement then you can create a custom table panel. 

But will leave it open for now to see if others want this and then we can reconsider it :)

**Comment by lperrin-tower** [comment]
can you please revisit the decision to merge this? it would actually be really helpful to pack more info in the tables. thanks

**Comment by torkelo** [comment]
The New table panel might support different size (padding) options

**Comment by sni** [comment]
"might support"?
+1 for me. 
Using the log panel might be a workaround if you only have a single column.

**Comment by codeincarnate** [comment]
Seeing as how this has only gotten a handful of comments across the past 5 years or so it seems like it's not something widely requested. The table panel has a large number of options so we definitely need to focus on ones that are pretty widely used. Going to close for now but if there's more momentum behind it we're happy to revisit this.
