### ISSUE TITLE
Alert notification send email failed:  Failed to send alert notifications  error="dial tcp 220.181.12.13:25: i/o timeout"

### ISSUE THREAD

**Issue by LiangJunChan** [grafana/grafana#9804]
Please include this information:
- What Grafana version are you using?
v4.6.1
- What datasource are you using?
influxDB
- What OS are you running grafana on?
Docker platform

When I test the alerting of grafana,I meet some problem.

**1.Runing container command for configured SMTP：**
`docker run -d -p 3002:3000 -e INFLUXDB_HOST=localhost -e INFLUXDB_PORT=8086 -e INFLUXDB_NAME=cadvisor -e INFLUXDB_USER=root -e INFLUXDB_PASS=root -e GF_SMTP_ENABLED=true -e GF_SMTP_HOST=smtp.163.com:25 -e GF_SMTP_USER=ljun000@163.com -e GF_SMTP_PASSWORD=123456 -e GF_SMTP_FROM_ADDRESS=ljun000@163.com --link influxsrv:influxsrv --name grafana-alerting grafana/grafana`

The setting of smtp in my grafana web UI is following:
```
smtp 
cert_file 
ehlo_identity  
enabled  true
from_address  ljun000@163.com
from_name  Grafana
host  smtp.163.com:25
key_file   
password  ************
skip_verify  false
user  ljun000@163.com
```

Then I check it and add test Alert notification:
```
t=2017-11-07T07:14:40+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-11-07T07:14:40+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[597690984@qq.com]
```
But it stuck on this message interface and I cannot receive any email.Why?
Is my configuration error? Please help point out, thanks a lot!

**Comment by torkelo** [comment]
the smpt connection times out, so maybe a docker networking issue?

**Comment by LiangJunChan** [comment]
@torkelo yeah.But now the log is stuck on "Sending alert notification to" and I can not receive any email.It troubles me a few days.
