### ISSUE TITLE
[Bug] The first condition's operator is "or" will cause "alert" to determine abnormal.

### ISSUE THREAD

**Issue by YouZhengChuan** [grafana/grafana#9805]
https://github.com/grafana/grafana/blob/f8698dc49b1090839e18d3714b2815dacc205ebe/pkg/services/alerting/eval_handler.go#L43

The first condition's operator is "or" will cause "alert" to determine abnormal.
In view of this situation, we need to ignore the value of the "operator" of the first "condition":

```golang
		if i == 0 {
			firing = cr.Firing
			noDataFound = cr.NoDataFound
		} else {
			// calculating Firing based on operator
			if cr.Operator == "or" {
				firing = firing || cr.Firing
				noDataFound = noDataFound || cr.NoDataFound
			} else {
				firing = firing && cr.Firing
				noDataFound = noDataFound && cr.NoDataFound
			}
		}

```

**Comment by torkelo** [comment]
Can you elaborate? What is abnormal?

**Comment by torkelo** [comment]
please update with more detail

**Comment by torkelo** [comment]
This should be fixed in v5
