### ISSUE TITLE
Rerun or refresh query if template variable value gets changed

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/grafana#9806]
Hi @torkelo,

I want to use one template variable in another template variable query of the same dashboard.
I can use it and I am getting data as well. But when I change the value of variable1 in combo box, the other template variable query doesn't get updated because it refreshes on "dashboard load" or "On time range changes".
I have attached the snapshot of variable 2 configuration.
That will be great if you have any workaround or solution of this.

Thanks in Advance!
-Himanshu

Please include this information:
- What Grafana version are you using? v4.1.2
- What datasource are you using? influxdb
- What OS are you running grafana on? ubuntu16.04

 
![image](https://user-images.githubusercontent.com/15123322/32486003-566c2fc2-c3cb-11e7-9cf7-441ddac98307.png)

**Comment by torkelo** [comment]
If you use the variable in the query field it will work, you can filter measurements directly in the query
