### ISSUE TITLE
[BUG] Transform: negative-Y series drawn as bars don't respect colors

### ISSUE THREAD

**Issue by giannello** [grafana/grafana#9808]
- What Grafana version are you using?
4.6.1

- What datasource are you using?
Elasticsearch

- What OS are you running grafana on?
Linux via Docker images

- What did you do?
Create a bar graph, add series override with colors and negative-y for some of the series

- What was the expected result?
All the bars should have a specific color applied

- What happened instead?
All the bars have the same color

 
![image](https://user-images.githubusercontent.com/551789/32495666-cf46b57a-c3c6-11e7-8a87-7a1fe9565949.png)

**Comment by torkelo** [comment]
unable to replicate, looks like the green bars are just drawn over the others. Maybe you need to enable (or disable) stacking or set different stack groups (via style override option)  

<img width="1262" alt="screen shot 2017-11-08 at 10 42 48" src="https://user-images.githubusercontent.com/10999/32542029-b30ef4b6-c471-11e7-88c8-08dae330e31c.png">

**Comment by giannello** [comment]
Yes, disabling stacking and adding the series to different stack groups (A for all the `negative-Y` series, and B for everything else) did the trick.
Maybe there should be a better default for this, it's surprising to see that things are overlapping, and not clear what the fix is.
