### ISSUE TITLE
lvl=eror msg="Failed to start session" logger=context error="Error 1062: Duplicate entry

### ISSUE THREAD

**Issue by luketopa** [grafana/grafana#9810]
CENTOS 7 / 4.6.1

I am trying to set grafana for HA using mySQL for database and session store.

I have a 4 node cluster all connected to a shared mySQL DB. All dashboards replicate as they should, I just seem to be having issues with the sessions. Can anyone give me any pointers?

[Database]

type = mysql
host = 172.0.0.0:3306 
name = crcgrafanadb
user = grafanadb
password = xxxxxx

[session]

provider = mysql
provider_config = grafanadb:xxxxxx@tcp(172.0.0.0:3306)/crcgrafanadb

[In Chrome Errors]

/api/search?limit=4&starred=true Failed to load resource: the server responded with a status of 401 (Unauthorized)

Possibly unhandled rejection: {"message":"Unauthorized","severity":"warning"}

[Debug log errors]

t=2017-11-07T15:18:44+0000 lvl=eror msg="Failed to start session" logger=context error="Error 1062: Duplicate entry '0eccb4edd2c58de8' for key 'PRIMARY'"
t=2017-11-07T15:18:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.1.5.1 time_ms=13 size=29 referer=
t=2017-11-07T15:18:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=10.1.5.1 time_ms=42 size=24 referer=
t=2017-11-07T15:18:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.1.5.1 time_ms=19 size=29 referer=
t=2017-11-07T15:18:44+0000 lvl=eror msg="Failed to start session" logger=context error="Error 1062: Duplicate entry 'aad573403c2cad6f' for key 'PRIMARY'"
t=2017-11-07T15:18:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=10.1.5.1 time_ms=62 size=24 referer=
t=2017-11-07T15:18:44+0000 lvl=eror msg="Failed to start session" logger=context error="Error 1062: Duplicate entry '1aaddb186c868ca5' for key 'PRIMARY'"
t=2017-11-07T15:18:44+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.1.5.1 time_ms=13 size=29 referer=
t=2017-11-07T15:18:45+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=10.1.5.1 time_ms=42 size=24 referer=
t=2017-11-07T15:18:45+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.1.5.1 time_ms=18 size=29 referer=
t=2017-11-07T15:18:45+0000 lvl=eror msg="Failed to start session" logger=context error="Error 1062: Duplicate entry '4f35ef17d49f0d39' for key 'PRIMARY'"
t=2017-11-07T15:18:45+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=302 remote_addr=10.1.5.1 time_ms=56 size=24 referer=
t=2017-11-07T15:18:45+0000 lvl=eror msg="Failed to start session" logger=context error="Error 1062: Duplicate entry '459810fca0f0cc47' for key 'PRIMARY'"

**Comment by daniellee** [comment]
Did you solve this - there is nothing obvious that is wrong in your configuration.

Are you using https? Could be a cookies problem.

**Comment by szediktam** [comment]
Did this problem solved?
I have same problem in grafana4.4?

**Comment by lixiangjun** [comment]
I have the same problem with grafana 4.4.

**Comment by vipsql** [comment]
I have the same problem with grafana 5.2.4

**Comment by daniellee** [comment]
I never got an answer from the author. Closing this due to lack of follow up.
