### ISSUE TITLE
[Bug] Cannot import data sources from __input field  

### ISSUE THREAD

**Issue by Xopherus** [grafana/grafana#9812]
## What Grafana version are you using?
4.6.1

## What datasource are you using?
In this case a MySQL datasource, though all data sources would probably be affected.

## What OS are you running grafana on?
Docker

## What did you do?
I exported a dashboard I made via the UI. According to the [export/import documentation](http://docs.grafana.org/reference/export_import/), this JSON file included an `__inputs` object which should specify the data sources that are used for the various panels. I then used the [terraform-provider-grafana](https://github.com/terraform-providers/terraform-provider-grafana) to create the dashboard using the [go api client](https://github.com/apparentlymart/go-grafana-api). I would expect it to just work according to the documentation. Terraform is able to create the dashboard, but when I open it in the UI, I get the following error in my panels: *Datasource named ${DS_BIZMETRICSDB} was not found*.

Here's the dashboard JSON which is being loaded:
```
{
  "__inputs": [
    {
      "name": "DS_BIZMETRICSDB",
      "label": "bizmetricsdb",
      "description": "",
      "type": "datasource",
      "pluginId": "mysql",
      "pluginName": "MySQL"
    }
  ],
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "hideControls": false,
  "id": null,
  "links": [],
  "rows": [
    {
      "collapse": false,
      "height": "400",
      "panels": [
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": true,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgb(88, 126, 255)"
          ],
          "datasource": "${DS_BIZMETRICSDB}",
          "description": "",
          "format": "none",
          "gauge": {
            "maxValue": 100,
            "minValue": 0,
            "show": false,
            "thresholdLabels": false,
            "thresholdMarkers": false
          },
          "id": 1,
          "interval": null,
          "links": [],
          "mappingType": 1,
          "mappingTypes": [
            {
              "name": "value to text",
              "value": 1
            },
            {
              "name": "range to text",
              "value": 2
            }
          ],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "rangeMaps": [
            {
              "from": "null",
              "text": "N/A",
              "to": "null"
            }
          ],
          "span": 3,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "tableColumn": "sum(value)",
          "targets": [
            {
              "alias": "",
              "expr": "",
              "format": "table",
              "intervalFactor": 2,
              "rawSql": "select sum(value) from X;",
              "refId": "A"
            }
          ],
          "thresholds": "0,1",
          "timeFrom": null,
          "title": "Total",
          "type": "singlestat",
          "valueFontSize": "200%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg"
        }
      ],
      "repeat": null,
      "repeatIteration": null,
      "repeatRowId": null,
      "showTitle": false,
      "title": "Row title",
      "titleSize": "h6"
    }
  ],
  "schemaVersion": 1,
  "style": "dark",
  "tags": [
    "bizmetrics"
  ],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-2d",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "TestPanel",
  "version": 1
}
```

The data source was already manually created, so that's not the problem. It seems as though the `__inputs` field is just ignored or not rendered properly when it is imported. I've looked at the terraform-provider-grafana and it doesn't seem like it's the problem, but I'd definitely appreciate some assistance to find the exact issue.

I do know that when you import a dashboard via the UI you have to specify the data source to use anyway, so it seems like that would override the `__inputs` which are specified in the JSON. Any help would be greatly appreciated!

**Comment by torkelo** [comment]
I do not think terraform is using the import api

**Comment by Xopherus** [comment]
Do you mean the dashboard API @torkelo? You can create dashboards via the [provider](https://www.terraform.io/docs/providers/grafana/r/dashboard.html). Or is export/importing a separate feature from the dashboard API?

**Comment by torkelo** [comment]
Yes the import api is special, only used by the import UI so users can select datasources.

**Comment by Xopherus** [comment]
Is there any public documentation on this import api? I haven't seen it on docs.grafana.org. 

For now I've been able to workaround it by just replacing `${DS_BIZMETRICSDB}` with `bizmetricsdb`, but it would be great to not have to take this step each time I'd like to update the graph.

**Comment by torkelo** [comment]
No there is no docs, this api is only used by the UI and is not meant for automation use cases as it requires user selecting and mapping data sources
