### ISSUE TITLE
Add custom quick ranges

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#9814]
Please include this information:
- What Grafana version are you using? **4.7.0-pre1**
- What datasource are you using? **Influx**
- What OS are you running grafana on? **Ubuntu 17**
- What did you do? 
Using Quick ranges, but unable to add my own/custom ranges
- What was the expected result?
Would be great to have an option to add custom ranges, like for example choosing between annotation tags query timestamps.
For example let's assume annotations query returns application versions: v1.0, v1.1, v1.2, v1.3 ... v1.9
It would be great to be able to choose time range from v1.0 to v1.1 or v1.4 to v1.9 etc.

- What happened instead?
No custom date ranges

**Comment by torkelo** [comment]
duplicate o https://github.com/grafana/grafana/issues/2417

**Comment by lukaszgryglicki** [comment]
Well, this one was supposed to be more specific - to allow quick ranges based on annotation values.

**Comment by torkelo** [comment]
Ah I see this feature request is a bit different

**Comment by cubranic** [comment]
Would you consider a patch where the current hard-coded quick ranges (variable `rangeOptions` in [app.core.utils.rangeutil](https://github.com/grafana/grafana/blob/master/public/app/core/utils/rangeutil.ts#L15)) can be modified via the config file?

**Comment by lukaszgryglicki** [comment]
It would be better than what we already have, but what I need is support for dynamic date ranges allowing choosing from annotation query results.

**Comment by Tatranskymedved** [comment]
@torkelo Hi, sorry I just want to confirm - You've closed #13766 and then refered me to #2417. I see that the clsoed one is more closer to this one and I'm not sure, on which thread we should follow. Could You clarify/set into right direction? Thanks!

**Comment by torkelo** [comment]
what do you mean? Do you think the issues are different and we should have two separate feature requests ?

**Comment by Ingeteam-TomasValasek** [comment]
@torkelo Hello, could You please assign me to this issue? I have the feature created and I'd like to create a pull request. Thanks!

**Comment by torkelo** [comment]
I can only do that to repo contributors

**Comment by Ingeteam-TomasValasek** [comment]
@torkelo Is there a way for me to become repo contributor? I´ve created feature that allows for custom timer ranges to be defined and browsed easily and I would like to add it to Grafanas repo. 
If possible I´d like to know how to become a contributor and what steps are needed for me to add this feature to Grafana. Thanks!

**Comment by torkelo** [comment]
closing as it's similar to ttps://github.com/grafana/grafana/issues/2417
