### ISSUE TITLE
[Bug] Signup page allows inserting arbitrary text above form

### ISSUE THREAD

**Issue by brittag** [grafana/grafana#9816]
**Thanks and credit to [yumi](https://hackerone.com/yumi) for reporting this issue to my team as part of the [TTS Bug Bounty program](https://hackerone.com/tts).**

You can make a URL that inserts arbitrary text (not full arbitrary HTML) in part of the signup form. Since the text is displayed above the form, a person could craft and send a URL that could mislead a user to follow incorrect instructions, such as browsing to a phishing page.

Here's how to reproduce this issue on a Grafana instance, tested on our instance which is running version 4.0.0:

1. Go to `https://EXAMPLE.COM/signup?email=[]`
2. Replace `[]` with any text, such as `https://EXAMPLE.COM/signup?email=An error have occured, please visit evil.com for more informations.`
3. The text is displayed on the page:

![image](https://user-images.githubusercontent.com/391313/32519746-924c7ed8-c3c2-11e7-9852-0fa4adc9b11f.png)

This is most likely a low-impact issue, but it could be mitigated in a few fairly simple ways, such as constraining the allowed input in this spot.

**Comment by torkelo** [comment]
thanks for reporting this!
