### ISSUE TITLE
Improve ds/plugin proxy error reporting

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#9817]
Currently if there is an error proxying a data source or plugin request the user gets an opaque response from Grafana (often just an http 502 with no body at all), this makes it difficult for the user to determine what has gone wrong without going through the server logs looking for `http: proxy error:` entries.

Grafana should provide helpful responses to the user including the error details if there is a problem proxying a request.

**Comment by torkelo** [comment]
Agree, this can be much improved. One of the reasons why this is not very good right now is that the Go httputil.ReverseProxy director (where the proxy logic happens) has not error handling / way to return errors. So I am not sure how to "abort" the proxy call and return an error as the only way to do that (from what I can see) is to panic inside the director.

The errors that currently happen and are only logged in the server log and not returned to the user happen inside call:
https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L169

Which calls the ds proxy director:
https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/ds_proxy.go#L102

Don't see how we can handle errors in the director and expose them to the http response (without causing error/crash in the proxy.RoundTrip call that the reverse proxy calls after the director call). 

Might need to find a way to move all code that can cause errors out of the proxy director, or move to https://github.com/vulcand/oxy .

**Comment by huseyinkozan** [comment]
> The errors that currently happen and are only logged in the server log
How can I find this server logs ?

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
