### ISSUE TITLE
Change name units

### ISSUE THREAD

**Issue by felipinho-lima** [grafana/grafana#9818]
What Grafana version are you using?  Grafana v4.5.2 (commit: ec2b0fe)
What datasource are you using? Zabbix and MySQL
What OS are you running grafana on? RHEL 6.5

Hello,

I have a doubt. What file I need to change to show GiB and TiB units for GB and TB but I am Brazilian and here is better show this.

Thanks.

**Comment by torkelo** [comment]
There two data unit types metric and IEC in grafana , select the metric ones

**Comment by felipinho-lima** [comment]
Thanks Torkel.
I changed. Sorry for i don’t see that.

                         Atenciosamente,

[Descrição: Descrição: Descrição: cid:image002.jpg@01CF528A.345A6EA0]

FELIPE LIMA DE OLIVEIRA

Serviço de Monitoramento de Infraestrutura de TI (SEMIT)

Departamento de Infraestrutura de TI (DEINF)

Diretoria Geral de Tecnologia da Informação (DGTEC)

Poder Judiciário do Estado do Rio de Janeiro

Tel: +55(21) 3133-2620



E-mail: felipelo@tjrj.jus.br<mailto:felipelo@tjrj.jus.br>

Ato Executivo Conjunto TJ/CGJ nº 04/2004, art. 8º, de 27/01/2004: "As comunicações por correio eletrônico entre Serventias, Secretarias de Órgãos Julgadores e demais Órgãos do Poder Judiciário terão o mesmo efeito de entregues pessoalmente".



De: Torkel Ödegaard [mailto:notifications@github.com]
Enviada em: quarta-feira, 8 de novembro de 2017 04:12
Para: grafana/grafana
Cc: Felipe Lima de Oliveira; Author
Assunto: Re: [grafana/grafana] Change name units (#9818)


There two data unit types metric and IEC in grafana , select the metric ones
