### ISSUE TITLE
Configuration of Visualization for BOOL Values

### ISSUE THREAD

**Issue by jankiessling** [grafana/grafana#9820]
I am using V4.5.2.
Datasource is InfluxDB 0.10.0

I try to find the correct settings to visualize BOOL values that will change by subscription (so when changing).

I wonder how to set up the fields SELECT and FILL.
So in query language:
SELECT ???("value") FROM "measurement" WHERE $timeFilter GROUP BY time($__interval) fill(???)

I played around a little and in comparison to the real database entries, it seems not to fit.

Is it even possible having a graphical visualization and seeing value changes for BOOLs when the change is within a second but I am looking at e.g. 30 days time period. 

Or can I influence this by setting GROUP BY time(1s). Was also not working for me but maybe it should...

Thanks and regards,
Jan

**Comment by torkelo** [comment]
I do not think InfluxDB support aggregation functions (and group by time) for bool values
