### ISSUE TITLE
[Feature] Zabbix Triggers panel - Add disable acknowledgement option

### ISSUE THREAD

**Issue by dodikvt** [grafana/grafana#9821]
It would be nice to have option to disable acknowledge event in Zabbix trigger panel.

I need to disable acknowledgement option for user with viewer roles. Maybe it would be great if acknowledgement option could follow user role.

Disabled acknowledgement for role Viewer
Enable acknowledgement for role Editor, Admin

**Comment by torkelo** [comment]
open this issue in the zabbix grafana repository https://github.com/alexanderzobnin/grafana-zabbix
