### ISSUE TITLE
Annotations: Add support for panels with time override

### ISSUE THREAD

**Issue by mathieulongtin** [grafana/grafana#9822]
- What Grafana version are you using? 4.6.1
- What datasource are you using? InfluxDb
- What OS are you running grafana on? CentOS 6
- What did you do?
On a dashboard, the global time range is the last 24 hours, but a few graph have an override to the last 30 days.

I put an annotation on the 30 day graph that starts about 36 hours ago and stops about 12 hours ago.

The annotation now looks like this, covering the entire last 30 days:
![bad-annotation](https://user-images.githubusercontent.com/617359/32555275-4c67eabc-c46a-11e7-84fc-dba50f827bfc.png)

If I change the dashboard's time range to last 30 days, the annotation looks fine, covering just yesterday.

My guess is that the annotation drawing looks at the global time range, not the current graph's time range. But that's just my uneducated guess.

**Comment by torkelo** [comment]
Annotations do not work for panels with overridden time range. Think we need to disable annotations for these panels so they are never shown.

**Comment by gi11es** [comment]
IMHO the point of having annotations is that they show up everywhere they make sense to. If you consider that support in overridden time ranges is a no-go, it makes annotations unusable on a lot of our dashboards. It seems counter-intuitive to me that the annotations load or not based on the "main" dashboard time range.

Surely when you're constructing the page you know that there are some overridden time ranges and you could fetch annotations going further back than the main time range? Even if it's async and takes a second to load after the dashboard have, it would be acceptable for us.

**Comment by torkelo** [comment]
Would have to to do a fetch call for each panel with overriden time range. Would be possible true.

**Comment by gi11es** [comment]
For each one, or figure out a time range that covers all the overridden ones and do a single request?

**Comment by torkelo** [comment]
> For each one, or figure out a time range that covers all the overridden ones and do a single request? 

that wont work, the time range could be vastly different between panels, say one graph had last year time range range which could return millions of annotations (hover only top 100 would be returned depends on annotation source) but all other graphs show last 1h, but would show no annotations (if it shared the same query with the last year query)

**Comment by Kimberlite** [comment]
Just allow me to use your conversation to ask you a question : it is possible to create an annotation range in elasticsearch and display it in grafana ? a priori, the only possibility is to keyboard the annotation range in grafana at the opposite of the simple annotation marker who can be created in elasticsearch... many thanks for your reply !
