### ISSUE TITLE
Comparison of 'state' parameter in oauth_generic does not handle urldecode correctly, resulting in "state mismatch"

### ISSUE THREAD

**Issue by maxenced** [grafana/grafana#9823]
Please include this information:
- What Grafana version are you using?
4.6
- What datasource are you using? 
N/A
- What OS are you running grafana on?
Debian Stretch

- What did you do?

Configured oauth_generic with ADFS 4 openid provider. Configuration is : 
```
[auth.generic_oauth]
enabled = true
name = OAuth
allow_sign_up = true
client_id = 22c3f87a-c13a-47a4-8dd7-ae2a67ecc892
client_secret = 11GkpLGhAc1pPVeHhDHoZ0QmGYBJI_PccS54wnD3
scopes = openid
auth_url = https://adfs-preprod.adm.domain.net/adfs/oauth2/authorize/
token_url = https://adfs-preprod.adm.domain.net/adfs/oauth2/token/
api_url = https://adfs-preprod.adm.domain.net/adfs/userinfo
allowed_domains = 
```

- What was the expected result?

Login correctly

- What happened instead?

Login failed with "state mismatch" error message. I checked the root_url, session cookie etc etc, everything was fine. Also hexumped my session file and the base64 was the same than in the callback GET param "state". The issue is that string generated as "state" value is converted as base64. However, this may contains '+' char. When sent as GET parameters by ADFS, the "state" param is urldecoded, which means '+' are converted to space. Those, grafana ends to compare '+' with  ' ' : 

```
lvl=eror msg="failed to compare state " logger=oauth.login saved state="ZS/OQfCGVAjwD+8hnStMq+OZ3BP4PjxVYOX/9T/lzzs=" query state="ZS/OQfCGVAjwD 8hnStMq OZ3BP4PjxVYOX/9T/lzzs="
```

**Comment by torkelo** [comment]
looks like a ADFS bug then, that it does not url decode the query state properly when redirecting back? 

No other oauth provider has reported this issue. Grafana base64 and hands it of to the oauth2 lib that then I guess url decodes it before generating the redirect url. 

Grafana will url decode the state query param and compare against the base64 coded string. So either it's a bug in the go oauth lib or in ADFS

**Comment by penguinpowernz** [comment]
I'm having this problem using AWS Cognito provider.  Seems that the `+` symbols in the base64 string are being removed by the `net/url` package (see here: https://github.com/golang/go/blob/master/src/net/url/url.go#L251).

Seems that the quick fix would be to modify the `GenStateString` method at https://github.com/grafana/grafana/blob/master/pkg/api/login_oauth.go#L35 to look like this:

```
func GenStateString() string {
	rnd := make([]byte, 32)
	rand.Read(rnd)
	b64 := base64.StdEncoding.EncodeToString(rnd)
	return strings.Replace(b64, "+", "", -1)
}
```

**Comment by torkelo** [comment]
this was fixed in v5.
