### ISSUE TITLE
Documentation or implementation wrong for __timeFilter in PG

### ISSUE THREAD

**Issue by volter** [grafana/grafana#9825]
docs/sources/features/datasources/postgres.md claims:

`*$__timeFilter(dateColumn)* | Will be replaced by a time range filter using the specified column name. For example, *dateColumn > to_timestamp(1494410783) AND dateColumn < to_timestamp(1494497183)*`

... and so does the query editor help.

However, pkg/tsdb/postgres/macros_test.go and pkg/tsdb/postgres/macros.go support what I found in practice:

```
        case "__timeFilter":
                ...
                return fmt.Sprintf("extract(epoch from %s) BETWEEN %d AND %d", args[0],
```

**Comment by svenklemm** [comment]
i guess the docs are out of sync. do you have a problem with either version? the result should be the same except for the boundaries. BETWEEN includes the boundaries while the earlier version didnt.

**Comment by pepl** [comment]
The results will be the same but the runtime will be significantly slower with `extract(epoch from %s) ` because Pg won't make use of indexes on the dateColumn then.

**Comment by svenklemm** [comment]
You are right i was optimizing the macros mostly for statement brevity i'll do a pass over them and rewrite them to avoid expressions on the time column where possible.

**Comment by svenklemm** [comment]
After thinking about it I remember the reason for that version of the macro. It got changed to support Amazon Redshift which does not have to_timestamp to convert from unix timestamp to timestamptz

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/9841
