### ISSUE TITLE
Infrequent Graphite data not displayed in Grafana

### ISSUE THREAD

**Issue by cmclaughlin** [grafana/grafana#9829]
Sorry in advance if this is a usage question... I can't find any other issues about it.

- What Grafana version are you using?  4.6.0 
- What datasource are you using?  Graphite 
- What OS are you running grafana on?  AWS Linux

I have a custom collectd plugin that sends a counter. Most of the time it's 0.  It runs a large database querry, so I'd like to adjust the frequency/interval at which it runs.

* When the collectd plugin interval is set to 10s (which is the same as my global collectd interval, btw) I see the data in Graphite and Grafana.

* When I raise the collectd plugin interval to 600s, I see the data in Graphite but not in Grafana.

Here are some screenshots to demonstrate the problem:

![graphite](https://user-images.githubusercontent.com/1061109/32574059-e45cf8a2-c484-11e7-92a4-31683f6034af.png)

![grafana](https://user-images.githubusercontent.com/1061109/32574068-ea7870cc-c484-11e7-9108-881c2d8905ad.png)

Any ideas how I can debug this further?

**Comment by torkelo** [comment]
Change null mode in display options, or add graphite function transformNull
