### ISSUE TITLE
Postgresql 500 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ekote** [grafana/grafana#9830]
- What Grafana version are you using?
locally: grafana-4.6.1 and also hosted version 
- What datasource are you using?
postgresql
- What OS are you running grafana on?
ubuntu 16.04
- What did you do?
Try to add data source
- What was the expected result?
Added postgresql as a data source
- What happened instead?
500 Internal server error
 - Include raw network request & response
 
`t=2017-11-08T22:43:27+0100 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="runtime error: invalid memory address or nil pointer dereference"`

-
![screenshot from 2017-11-08 22-51-41](https://user-images.githubusercontent.com/6086762/32576536-89f9950c-c4d7-11e7-9460-4efe5daad6a5.png)

![1234](https://user-images.githubusercontent.com/6086762/32576436-3ceaaef4-c4d7-11e7-8646-65d37fafc8df.png)

**Comment by ekote** [comment]
Issue connected with https://github.com/grafana/grafana/issues/9772#issuecomment-342978521

**Comment by svenklemm** [comment]
Hmm since you get proper error messages with wrong credentials, the postgres driver seems to be initialized correctly. There is something different about your postgres that doesnt match my test setup.
Which version of postgres are you using? Are you using .pgpass?

There was a similar issue 2 weeks ago https://community.grafana.com/t/postgres-datasource-plugin/3459 which the reporter solved by using a different database user but it would be really nice if we could find the cause of the error.

**Comment by ekote** [comment]
1. Postgresql `PostgreSQL 9.6.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit` 
2. I am trying to connect to Postgres hosted on AWS
3. I saw the report, that's why I created a user: `grafanareader` with only `SELECT` privileges type.|

What is more, I was able to add successfully  this data source to `redash.io`, but I want to use grafana, not redash.

**Comment by svenklemm** [comment]
The conclusion in the report was not correct, grafana does not check if the user is restricted. The problem might still be permission related though.
Unfortunately i was not able to reproduce the issue yet.

**Comment by svenklemm** [comment]
Ok i can at least get the driver to panic now but i can't reproduce the invalid memory address yet. Does your password contain special characters that might break the connection string?

**Comment by ekote** [comment]
@svenklemm

**Comment by ekote** [comment]
@svenklemm 
I did once again:
`CREATE USER grafanareader WITH PASSWORD 'simplepassword';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafanareader;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO grafanareader;`

Now it works. My previous password was generated so was more complicated.
Thanks for help!

**Comment by svenklemm** [comment]
@ekote Great. Can you tell me which special character you used to make it break so i can reproduce and fix it.

**Comment by ekote** [comment]
Sure @svenklemm . My password was `MLyC9#]qF)>rr)g[k.]F`
`

**Comment by wanderutwells** [comment]
I've experienced this issue as well. My password contained '#' as well.

**Comment by rafi** [comment]
I can confirm `#` in password was the culprit.
