### ISSUE TITLE
percent_diff() returning a 0.000 value in all cases

### ISSUE THREAD

**Issue by tinder-chrisobrien** [grafana/grafana#9831]
Grafana v4.7.0-pre1 (commit: 5b38c23)
Prometheus
Ubuntu 

Issue: percent_diff() is failing to return a non-zero value on all metrics from the data source, even when there is a substantial difference.

This issue started in 4.6.1. In versions prior, it worked without issue.

**Comment by torkelo** [comment]
Percent diff is a prometheus function and not implemented in Grafana. Maybe you need to change the range vector or min step option

**Comment by tinder-chrisobrien** [comment]
@torkelo To clarify, I am referring to Grafana alert function implemented as part of https://github.com/grafana/grafana/pull/9386

**Comment by torkelo** [comment]
Can you show output of when you click Test Rule?

**Comment by tinder-chrisobrien** [comment]
firing:false
state:"ok"
conditionEvals:"[false OR false] = false"
timeMs:"10.606ms"
logs:Array[4]
0:Object
message:"Condition[0]: Query Result"
data:Array[1]
0:Object
name:"ws"
points:Array[91]
0:Array[12571,1510336104000]
1:Array[12571,1510336114000]
2:Array[12601,1510336124000]
3:Array[12601,1510336134000]
4:Array[12601,1510336144000]
5:Array[12601,1510336154000]
6:Array[12601,1510336164000]
7:Array[12601,1510336174000]
8:Array[12616,1510336184000]
9:Array[12616,1510336194000]
10:Array[12616,1510336204000]
11:Array[12616,1510336214000]
12:Array[12616,1510336224000]
13:Array[12616,1510336234000]
14:Array[12636,1510336244000]
15:Array[12636,1510336254000]
16:Array[12636,1510336264000]
17:Array[12636,1510336274000]
18:Array[12636,1510336284000]
19:Array[12636,1510336294000]
20:Array[12632,1510336304000]
21:Array[12632,1510336314000]
22:Array[12632,1510336324000]
23:Array[12632,1510336334000]
24:Array[12632,1510336344000]
25:Array[12632,1510336354000]
26:Array[12564,1510336364000]
27:Array[12564,1510336374000]
28:Array[12564,1510336384000]
29:Array[12564,1510336394000]
30:Array[12564,1510336404000]
31:Array[12564,1510336414000]
32:Array[12691,1510336424000]
33:Array[12691,1510336434000]
34:Array[12691,1510336444000]
35:Array[12691,1510336454000]
36:Array[12691,1510336464000]
37:Array[12691,1510336474000]
38:Array[12667,1510336484000]
39:Array[12667,1510336494000]
40:Array[12667,1510336504000]
41:Array[12667,1510336514000]
42:Array[12667,1510336524000]
43:Array[12667,1510336534000]
44:Array[12647,1510336544000]
45:Array[12647,1510336554000]
46:Array[12647,1510336564000]
47:Array[12647,1510336574000]
48:Array[12647,1510336584000]
49:Array[12647,1510336594000]
50:Array[12638,1510336604000]
51:Array[12638,1510336614000]
52:Array[12638,1510336624000]
53:Array[12638,1510336634000]
54:Array[12638,1510336644000]
55:Array[12638,1510336654000]
56:Array[12585,1510336664000]
57:Array[12585,1510336674000]
58:Array[12585,1510336684000]
59:Array[12585,1510336694000]
60:Array[12585,1510336704000]
61:Array[12585,1510336714000]
62:Array[12590,1510336724000]
63:Array[12590,1510336734000]
64:Array[12590,1510336744000]
65:Array[12590,1510336754000]
66:Array[12590,1510336764000]
67:Array[12590,1510336774000]
68:Array[12581,1510336784000]
69:Array[12581,1510336794000]
70:Array[12581,1510336804000]
71:Array[12581,1510336814000]
72:Array[12581,1510336824000]
73:Array[12581,1510336834000]
74:Array[12586,1510336844000]
75:Array[12586,1510336854000]
76:Array[12586,1510336864000]
77:Array[12586,1510336874000]
78:Array[12586,1510336884000]
79:Array[12586,1510336894000]
80:Array[12754,1510336904000]
81:Array[12754,1510336914000]
82:Array[12754,1510336924000]
83:Array[12754,1510336934000]
84:Array[12754,1510336944000]
85:Array[12754,1510336954000]
86:Array[12717,1510336964000]
87:Array[12717,1510336974000]
88:Array[12717,1510336984000]
89:Array[12717,1510336994000]
90:Array[12717,1510337004000]
tags:Object
__name__:"rollup"
job:"prod"
1:Object
message:"Condition[0]: Eval: false, Metric: ws, Value: 0.000"
data:null
2:Object
message:"Condition[1]: Query Result"
data:Array[1]
0:Object
name:"ws"
points:Array[31]
0:Array[12585,1510336704000]
1:Array[12585,1510336714000]
2:Array[12590,1510336724000]
3:Array[12590,1510336734000]
4:Array[12590,1510336744000]
5:Array[12590,1510336754000]
6:Array[12590,1510336764000]
7:Array[12590,1510336774000]
8:Array[12581,1510336784000]
9:Array[12581,1510336794000]
10:Array[12581,1510336804000]
11:Array[12581,1510336814000]
12:Array[12581,1510336824000]
13:Array[12581,1510336834000]
14:Array[12586,1510336844000]
15:Array[12586,1510336854000]
16:Array[12586,1510336864000]
17:Array[12586,1510336874000]
18:Array[12586,1510336884000]
19:Array[12586,1510336894000]
20:Array[12754,1510336904000]
21:Array[12754,1510336914000]
22:Array[12754,1510336924000]
23:Array[12754,1510336934000]
24:Array[12754,1510336944000]
25:Array[12754,1510336954000]
26:Array[12717,1510336964000]
27:Array[12717,1510336974000]
28:Array[12717,1510336984000]
29:Array[12717,1510336994000]
30:Array[12717,1510337004000]
tags:Object
__name__:"rollup"
job:"prod"
3:Object
message:"Condition[1]: Eval: false, Metric: ws, Value: 12717.000"
data:null

**Comment by tinder-chrisobrien** [comment]
<img width="658" alt="screen shot 2017-11-10 at 10 05 35 am" src="https://user-images.githubusercontent.com/32073713/32672104-b9f33c68-c5fe-11e7-87f8-e231d2e03587.png">
