### ISSUE TITLE
Cannot build 4.6.0 or 4.6.1 from source in Homebrew

### ISSUE THREAD

**Issue by mikepurvis** [grafana/grafana#9832]
Attempting to install 4.6.1 on macOS using homebrew. 

- What Grafana version are you using? 4.6.1
- What OS are you running grafana on? macOS
- What did you do? `brew edit grafana`, updated the tarball URL and sha256, then `brew upgrade grafana`. 
- What was the expected result? Grafana builds and can be used.
- What happened instead? Grafana fails to build from source:

```
==> go run build.go build
==> yarn install --ignore-engines
==> node_modules/grunt-cli/bin/grunt build --force
Error: No such file or directory - public_gen
```

Related PR with a more verbose log: https://github.com/Homebrew/homebrew-core/pull/20139

**Comment by torkelo** [comment]
need to update the formula and change this line:
 https://github.com/Homebrew/homebrew-core/blob/master/Formula/grafana.rb#L41

the public_gen dir is no longer there it's just public

**Comment by torkelo** [comment]
This is fixed in latest homebrew formula
