### ISSUE TITLE
[Feature Request] Allow users to specify a custom backend for saving annotations

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#9837]
it seems to me that the creation of annotations (CTRL + select in line plots) can only be written to the internal annotation storage even though I have an InfluxDB annotation configured for the dashboard. Even if I disable the internal storage it gets written there. Did I miss anything or perhaps this limitation (read only for other storages) is not clear from the documentation. If this is a limitation, there is a plugin that allows writing annotations, however it does not integrate as nice (CTRL + select with popup) so a native implementation is perferred.

Versions:
Grafana:latest (docker hub,  v4.6.1)
InfluxDB version 1.3.7

Docs (2017-11-09): 
http://docs.grafana.org/reference/annotations/
http://docs.grafana.org/features/datasources/influxdb/#annotations

**Comment by torkelo** [comment]
Yes, the native annotations can only be stored in grafanas db.

**Comment by daniellee** [comment]
Adding a reference to the plugin you mentioned (in case someone searching for this issue wants to use it):

https://grafana.com/plugins/novalabs-annotations-panel

**Comment by martinler** [comment]
We have just tested native annotations feature and it's super-easy to use and helps a lot, but connection with specific data (not dashboard) it necessary. I would appreciate native integration with InfluxDB with use of variable as reference for writing of data to InfluxDB.

**Comment by torkelo** [comment]
you can add tags to your annotation to associate with data

**Comment by martinler** [comment]
Please, can you elaborate? I tried to set annotations query by tags, tag "$unit_id" (because that's my variable used in this dashboard), but this is not working. 

![screen shot 2018-02-20 at 12 25 21](https://user-images.githubusercontent.com/19344005/36421571-43715a80-1639-11e8-935e-bc4dea458275.png)

BTW i just tested plugin referenced by @daniellee and it's not working correctly, it will not save my settings in annotation option (setting of db source, tag mapping), so not very usable. Known bug, but no reaction from author.

**Comment by torkelo** [comment]
using variable there is still an open PR for, https://github.com/grafana/grafana/pull/10163

**Comment by torkelo** [comment]
I was just referring to that annotations are not only linked to the dashboad/panel, if you add tags to the annotation when you create it you can show it on other dashboards as well.

**Comment by martinler** [comment]
Yes, i was not aware of that, thanks. So when this PR will land it should work for us, perfect!!

**Comment by StephenSorriaux** [comment]
Is there any work/attempt on this feature? I am willing to implement it.
