### ISSUE TITLE
graphite backend with http basic auth issue

### ISSUE THREAD

**Issue by alter** [grafana/grafana#9838]
Read before posting: 
Please include this information:
- What Grafana version are you using?
4.6.1

- What datasource are you using?
graphite

- What OS are you running grafana on?
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

- What did you do?
Set http basic auth to nginx with graphite:
auth_basic_user_file /etc/nginx/htpasswd.users;

In grafana source I set "basic auth" and input login/pass, try to test and got failed
Checked with chrome inspect and see that there is no credentials in request!
Add "with credential" checkbox, but got the same result.
Leave only "with credential" checkbox, without basic auth and found -H 'authorization: Basic tWttaWs6SXNoZWEcb2hKbagydWV0dt=', grafana said that test has been successful, BUT when I open dashboard browser ask me to input login/pass for basic auth,

Looks like it's grafana bug.

**Comment by torkelo** [comment]
are you using direct or process access?

If you using proxy access then the basic auth header will be added by grafana server and the user / password will not be exposed to the browser (the Authorization header is added by the backend when it proxies requests to Graphite)

**Comment by alter** [comment]
I use direct access

**Comment by torkelo** [comment]
Is your graphite configured to support cors? Can you show the network traffic?
