### ISSUE TITLE
Axes not show right!

### ISSUE THREAD

**Issue by xzmagic** [grafana/grafana#9843]
Please include this information:
- What Grafana version are you using? 
 grafana-4.5.2
- What datasource are you using?
influxdb-1.3.5
- What OS are you running grafana on?
windows
- What did you do?
i use grafana to display collectd's disk usage  about disk_otects,
where read and write data are all above 0,when Axes Y-min =auto ,Y-max=auto,read,and write all show
but write display below 0, not right,
when i set Axes  left-Y's  Y-Min  =0, write not show ;
- What was the expected result?
read and write all above 0, so in the graph they all must show above 0
- What happened instead?
only read show, write not show 
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![image](https://user-images.githubusercontent.com/3382620/32639534-5d3f0726-c5ff-11e7-80b1-5721ddd469d3.png)
![image](https://user-images.githubusercontent.com/3382620/32639594-9c0c24ca-c5ff-11e7-8121-1aed4efb8c4f.png)

**Comment by torkelo** [comment]
Can you expand the Query Inspector (metrics tab) and copy the raw response from InfluxDB?

**Comment by torkelo** [comment]
Also what browser are you using? 

Very strange. not able to replicate this. Do you have any series display override? (Graph display tab), only thing that can cause this is of you have a Transform negative Y on the write series.

**Comment by xzmagic** [comment]
thank  you for your reply, yes just because a Tranform negative y, sorry for my negligence in setting graph series.
