### ISSUE TITLE
Missing sub-second time resolution from PostgreSQL

### ISSUE THREAD

**Issue by mikepurvis** [grafana/grafana#9844]
According to past issues (#714), this is resolved for other data sources, but it looks like it's a gap for the PostgreSQL driver.

- What Grafana version are you using? 4.6.1
- What datasource are you using? PostgreSQL 10.0
- What OS are you running grafana on? Linux (Postgres on OS X)
- What did you do? Tried to plot a bunch of data with sub-second timestamps
- What was the expected result? Smooth plots as I zoom in.
- What happened instead? A big chunky mess.

I haven't looked much at the code, but based on the changes made for influxdb in ebcf2c3f6854cbe2903ad8c97af18018c5b42c7b, I'd guess the following area requires attention:

https://github.com/grafana/grafana/blob/5e11f1a2a1f9ca6ef8aa61e59578111dae1e310a/public/app/plugins/datasource/postgres/response_parser.ts#L127-L137

**Comment by svenklemm** [comment]
The code you linked to is for annotations. You are doing a normal timeseries query though i guess. What datatype does your time column have? datetime subsecond precision seems to get lost in backend atm unix timestamp milliseconds get passed to the frontend at least.

**Comment by mikepurvis** [comment]
I'm currently using a `timestamptz`: https://www.postgresql.org/docs/9.1/static/datatype-datetime.html

I can confirm your suggestion, though— if I extract the epoch seconds in my query, it does the correct thing:

```
SELECT extract(epoch FROM stamp) AS time, to_number(content->>'data','9999.99') AS foo FROM xxxxxxx WHERE yyyyyyy ORDER BY stamp
```

So my immediate problem is resolved, but it would be great to get first class support for the native Postgres date types. Feel free to close this ticket if that effort is being tracked elsewhere.
