### ISSUE TITLE
Add Median as an legend option in the graph panel

### ISSUE THREAD

**Issue by sunmit9** [grafana/grafana#9846]
As per https://github.com/grafana/grafana/pull/2540/commits, all the graph panel legends should have an option to display the Median. 

![image](https://user-images.githubusercontent.com/8079226/32646621-59a3b86e-c613-11e7-9832-425387621cbb.png)

**Comment by namanbada0606** [comment]
+ 1

**Comment by no-identd** [comment]
🤔

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
