### ISSUE TITLE
Add optional option sign out url for generic oauth 

### ISSUE THREAD

**Issue by nickvth** [grafana/grafana#9847]

**Comment by bejondshao** [comment]
I'm facing this issue. I believe this is an important function for auth.generic_oauth. Does this issue get noticed? If not, it's grateful for someone can give some advice on extending grafana. Thank you.

**Comment by torkelo** [comment]
what would the purpose be and is there any other systems that have this feature?

**Comment by bejondshao** [comment]
Hi torkelo, yes, I've found Jenkins with keycloak-jenkins plugin can achieve sign out behaviour.

**Comment by torkelo** [comment]
usually the oauth service have no concept of session, they give out an access token that expires.

**Comment by bejondshao** [comment]
Yes, you're right. Grafana needs to notify IdP that the use has log out. It just needs to invoke the log out API.

**Comment by fchiacchiaretta** [comment]
Hi,
I've configured generic oauth for grafana and keycloak using URLs in [Keycloak docs](https://www.keycloak.org/docs/3.4/server_admin/index.html#keycloak-server-oidc-uri-endpoints).

When I logout in Grafana, Keycloak does not destroy the session in its database, so trying to login again using generic_oauth does not ask for credentials and reuse the existing session.

Having Grafana call the proper logout uri endpoint would result in proper logout on Keycloak side.

**Comment by marefr** [comment]
As a workaround you can probably achieve expected result using a reverse proxy in front of Grafana with some custom redirect rules after signing out from Grafana. Just a thought

**Comment by fchiacchiaretta** [comment]
To all interested, I managed to get (what seems) a proper logout integrating with Keycloak and using Apache as reverse proxy, as suggested.

Here is the relevant configuration for httpd:
```
  RewriteEngine on
  RewriteRule ^/logout - [C]
  RewriteRule . "https://keycloak_host/auth/realms/insert_realm_here/protocol/openid-connect/logout?redirect_uri=https\%3A\%2F\%2Fgrafana_host\%2Flogin" [NE,R=302,CO=grafana_sess:INVALID:;]
  RewriteRule ^/login$ /login/generic_oauth [L,R=302]

  ProxyPass / http://grafana_host:3000/
  ProxyPassReverse / http://grafana_host:3000/
  RequestHeader set X-Forwarded-Proto "https"
```
Basically everything is managed by ProxyPass(Reverse), I added also a rule to redirect /login to /login/generic_oauth which may be omitted.
Please note that the second RewriteRule is matched only if you call /logout; this RewriteRule also invalidates grafana_sess cookie, so if you navigate to https://grafana_host authentication is requested again.

**Comment by roidelapluie** [comment]
@fchiacchiaretta this is awesome
