### ISSUE TITLE
Graph: Shared tooltip, option to show series summary values in tooltip 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#985]
I am not sure if this would be very useful but could be (if so please +1). The shared multi series tooltip (new in vNext 1.9) could be further extended to include columns for the series min, max and avg values (and total, current etc). 

![](https://cloud.githubusercontent.com/assets/10999/4443017/cbdf428c-47e4-11e4-8293-371f0395a156.png)

By adding more columns to this tooltip for series min, max, avg etc it could in some cases eliminate the need for the legend, or legend values. I am not sure if this is a good idea or not :)

**Comment by turiandras** [comment]
+1

**Comment by mtanda** [comment]
+1

**Comment by Elfo404** [comment]
@torkelo is this still relevant?
