### ISSUE TITLE
Handle built-in variables (such as $timeFilter) in template variables

### ISSUE THREAD

**Issue by dameiss** [grafana/grafana#9853]
Grafana 4.5.0 on MacOS and Linux, using InfluxDB.

I am able to create and use query-type template variables which use other template variables, such as

    show tag values from metric with key = "$SelectBy"

where `SelectBy` is a custom template variable.

However, I am unable to use $timeFilter in the same query-type template variable, as in

    show tag values from metric with key = "$SelectBy" where $timeFilter

The error I get is “Template variables could not be initialized: error parsing query: missing parameter: timeFilter”

It would be very helpful if built-in variables, specifically $timeFilter in my case, could be used (and properly handled) within template variables.

See [this message](https://community.grafana.com/t/using-timefilter-in-template/2925)

**Comment by torkelo** [comment]
This is currently not possible. 

Closing this as there already is a feature request for this:
https://github.com/grafana/grafana/issues/7918
