### ISSUE TITLE
[Bug] Custom code editor language definitions not loading from external plugins 

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#9857]
The change https://github.com/grafana/grafana/pull/9224 is removed at https://github.com/grafana/grafana/commit/0c86241c5b476cf3b4e8876dd92027cad9f95a0f#diff-5a71f47b576439c46b9ae9726b5662a0L57 .

**Comment by mtanda** [comment]
@torkelo @alexanderzobnin Would you check this?

**Comment by mtanda** [comment]
Error message for my plugin at https://github.com/mtanda/grafana-google-stackdriver-datasource/commit/89ed6f5d20209a97a0d3756605ca80fd67b49cd2.

![image](https://user-images.githubusercontent.com/224552/32696494-d3699bdc-c7bc-11e7-9304-871b11f93372.png)

**Comment by torkelo** [comment]
it is exposed via the code editor directive, not sure we want to expose it directly 

https://github.com/grafana/grafana/blob/master/public/app/core/components/code_editor/code_editor.ts

**Comment by hagen1778** [comment]
@torkelo but it is impossible now to use custom highlight rules for ace-editor

**Comment by mtanda** [comment]
@torkelo How should I do fix the issue.
If datasource plugin author want to use Ace editor, we can't use Grafana itself ace editor?

**Comment by mtanda** [comment]
You simply revert my work, it causes error, you should be more responsible about the issue.

**Comment by torkelo** [comment]
@mtanda sorry, I did not know you used the ace editor directly. I thought you used the code-editor directive. Is there a feature missing in the code editor ? Did you duplicate that directive?

**Comment by alexanderzobnin** [comment]
@torkelo I think a problem in paths. I used `setModuleUrl()` function for patching ace components path. And this function with @mtanda patch is also using for loading custom ace components (such as custom highlight rules) from external plugins.

**Comment by torkelo** [comment]
ok, can replicate now if I try to add a custom language file in an external plugin. 

I thought it would work since it works for prometheus:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/query_ctrl.ts 

But seems like plugins cannot see the ace global variable, might need to add it as a global in the plugin systemjs config, not sure if that will solve it.

**Comment by mtanda** [comment]
@torkelo Thanks for your investigation :-)
The ace editor really good feature for plugin developer, I make stackdriver datasource plugin, stackdriver has it's query language, really need assistance by editor.

@alexanderzobnin Thanks for help too 👍

**Comment by torkelo** [comment]
After testing some more I got this to work just fine without doing anything to core grafana.

Example here
https://github.com/grafana/simple-json-datasource/blob/code-editor-language-test/src/query_ctrl.js

**Comment by mtanda** [comment]
Finally, I success to fix the issue.

Accidentally, I skip SystemJS filter for mode-stackdriver.js, and it work with former code_editor implementation.
https://github.com/mtanda/grafana-google-stackdriver-datasource/blob/ba898f4604ebe707738ecbc8c28f03630d7070c7/Gruntfile.js#L55

But mode-stackdriver.js should be converted by SystemJS, by adding setting, fix the issue.
https://github.com/mtanda/grafana-google-stackdriver-datasource/commit/35f38b15ddccfcbb7672d97d24287185edce8c61

I don't understand SystemJS is it... It cause this issue. Sorry...
