### ISSUE TITLE
Non fluctuating data leads to bouncing graph because of Y-axis rouding

### ISSUE THREAD

**Issue by Jeroen88** [grafana/grafana#9858]
Please include this information:
- What Grafana version are you using? 4.4.1 (just upgraded to 4.6.1, issue stays the same)
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Ubuntu
- What did you do? Pushing lineair data every 15s
- What was the expected result? A straight line
- What happened instead? A bouncing line
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![roundings](https://user-images.githubusercontent.com/29522434/32694302-e9be9250-c73c-11e7-85a2-5c79d6b0bf7d.png)

**Comment by torkelo** [comment]
looks like your data has a very large value that only change a tiny amount. 

Try settings a y-axis min/max or hard code the number of decimals you want.

**Comment by Jeroen88** [comment]
thnx Ford your reaction Torkel.  The point is: the data is not fluctuating,  exact the same values are written in the database.  

Fixed axis is no option,  because data canvas change and without bounds. It is aan rounding error of Grafana I think. 

Any suggestions? 


Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Torkel Ödegaard <notifications@github.com> </div><div>Datum:13-11-2017  10:40  (GMT+01:00) </div><div>Aan: grafana/grafana <grafana@noreply.github.com> </div><div>Cc: Jeroen88 <info@el-mago.nl>, Author <author@noreply.github.com> </div><div>Onderwerp: Re: [grafana/grafana] Non fluctuating data leads to bouncing graph
  because of Y-axis rouding (#9858) </div><div>
</div>looks like your data has a very large value that only change a tiny amount.

Try settings a y-axis min/max or hard code the number of decimals you want.
