### ISSUE TITLE
Add time pick data to query for nodes

### ISSUE THREAD

**Issue by sgran** [grafana/grafana#986]
graphite-api allows queries of the form:
```
/metrics/find/?query=*.*.*.*
```
This is what grafana currently does.  There are also optional parameters that can be passed to timebox the query.  This takes the form:
```
/metrics/find/?query=*.*.*.*&from=then&until=now
```
This allows the backend to trim the list of metrics currently valid for the given time period.  We use ephemeral development environments, and our metrics include the instance id, so without this change, our list is growing daily.

Cheers,

**Comment by torkelo** [comment]
@sgran is this only supported by graphite-api? cannot get it to work against graphite-web 0.9.x branch

**Comment by sgran** [comment]
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/metrics/views.py suggests it should work.

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/issues/1931
