### ISSUE TITLE
Changing charset in MYSQL DataSource

### ISSUE THREAD

**Issue by igorkarolesky** [grafana/grafana#9865]
- What Grafana version are you using? 4.4.3
- What datasource are you using? MYSQL
- What OS are you running grafana on? Linux
- What did you do? Add a new Datasource
- What was the expected result? That it works
- What happened instead?Didn't work
I Get this error message when i try to test my connection with the DataSource:
Error
Error 1115: Unknown character set: 'utf8mb4'
Want to change this default utf8mb4 to latin1 how do i do that ?

**Comment by torkelo** [comment]
Grafana MySQL only supports version 5.5+
