### ISSUE TITLE
Escapeing template variables values in influxdb queries

### ISSUE THREAD

**Issue by wiku-PSNC** [grafana/grafana#9869]
Hi all,

I have in grafana template variable named interface (`show tag values with key="ifname" where device =~ /^$device$/`) and the values are eg. 'xe-0/0/0', 'xe-0/0/1'. There is no problem if the variable is multivalue and the panel is repeated for every value, but if I change the variable to be NOT multivalue the value is not escaped in influx query, eg.` SELECT mean("In.bytes") FROM "traffic" WHERE device =~ /^[[device]]$/ and ifname =~ /^[[interface]]$/ and $timeFilter group by time([[interv]]) fill(null)`, so it causes the error.

Grafana version: 4.6.1
datasource: influxdb
OS: Debian GNU/Linux 9

Best regards,
wiku

**Comment by torkelo** [comment]
Only multi value (or All) variables are regex escaped. For single value variables do not use =~ InfluxDB operator but use = "$myvariable"  (or = "[[myvariable]]")

**Comment by wiku-PSNC** [comment]
Thank you! In fact there should be single quotation (at least it works for me):
`= '$myvariable'` (or `= '[[myvariable]]`)

So for all multivalue variables it is required:
`=~ /^$myvariable$/` (or `=~ /^[[myvariable]]$/`)
and for single value variable:
`= '$myvariable'` (or `= '[[myvariable]]`) - escaped value
`=~ /^$myvariable$/` (or `=~ /^[[myvariable]]$/`) - nonescaped value
