### ISSUE TITLE
String interpolation is broken for certain symbols.

### ISSUE THREAD

**Issue by clarkent86** [grafana/grafana#9871]
- What Grafana version are you using? 4.6.1
- What datasource are you using? InfluxDB
- What OS are you running grafana on? redhat
- What did you do? Select a symbol in a where query
- What was the expected result? String interpolation to insert the correct symbol
- What happened instead?
![image](https://user-images.githubusercontent.com/9669831/32739995-1fb7e9a8-c867-11e7-901e-e5d72938f9c6.png)

Selecting the symbol from the dropdown causes this issue, but when you manually type the symbol it works fine.

**Comment by daniellee** [comment]
Confirmed as a bug.
