### ISSUE TITLE
Entire build can be run with a single go-get

### ISSUE THREAD

**Issue by Vaelatern** [grafana/grafana#9873]
The following is a request for the future direction of grafana. At present, the build script is not necessary in any way, shape, or form. The entire build can be successfully driven with `go get -x github.com/grafana/grafana/pkg/cmd/grafana-{cli,server}`.

Will grafana keep in sync with this standard way of building golang packages? Or is the build script an indication of grafana's intention to diverge?

**Comment by torkelo** [comment]
I don't know of any big golang project that does that, sure simple command line tools do, but grafana includes a big frontend as well. And if you build grafana like that you suggest you cannot set ldfags.

Checking on the most popular go projects all have build instructions that include a make file or build script :)

**Comment by Vaelatern** [comment]
You can totally set ldflags.
`go get -x -ldflags="$FLAGS" github.com/grafana/grafana/pkg/cmd/grafana-{cli,server}`

**Comment by Vaelatern** [comment]
Many of those projects drive `go get` in those makefiles.

**Comment by torkelo** [comment]
not seeing a go get in 
https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile
https://github.com/coreos/etcd/blob/master/build

> Many of those projects drive go get in those makefiles.

What is the point of doing that compared to go build? is it just that you want the binary in $GOPATH/bin ? 

> You can totally set ldflags. 

Cool! did not know that. But still grafana needs to set those ldflags and for that there needs to be a build script or makefile. 

You can run `go get -x github.com/grafana/grafana/pkg/cmd/grafana-{cli,server}.` but not sure why you want grafana to have that as the solo build instruction. You will only end up with a binary and no frontend :)

**Comment by Vaelatern** [comment]
I just want to know that if I choose to build grafana using `go get` that you folks won't outright break it, and that your use of a go script is not a deliberate break from normal go style.
