### ISSUE TITLE
Grafana Diagram does not allow input for either Diagram or Display (Both options are blank) 

### ISSUE THREAD

**Issue by luv4diamonds** [grafana/grafana#9874]
- What Grafana version are you using?  grafana-4.5.1-1
- What datasource are you using?  elasticsearch
- What OS are you running grafana on?  CentOS 7.2.1511
- What did you do?  Installed jdbranham-diagram-panel verion 1.4.0
- What was the expected result?  Was trying to create diagrams
- What happened instead?  Underneath the tabs for Diagram and Display have nothing underneath and nothing can be added.
- If related to metric query / data viz:  Metric query
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 According to the Dev Tools:
1.  GET http://localhost:3000/public/plugins/jdbranham-diagram-panel/diagramEditor.html   HTTP/1.1 404 Not Found
1.  GET http://localhost:3000/public/plugins/jdbranham-diagram-panel/displayEditor.html   HTTP/1.1 404 Not Found

I verified these files are actually there.

**Comment by torkelo** [comment]
Not able to replicate this. 

Try upgrading to Grafana 4.6.1

![image](https://user-images.githubusercontent.com/10999/32773802-a503b768-c92a-11e7-90e6-ecc2211aaba5.png)

**Comment by torkelo** [comment]
are you running the browser on the same centos machine? The requests are to localhost which looks strange. 

Try setting grafana.ini 

root_url = http://yourgrafanaserver:3000

(set this to the root url you use in the browser to access grafana)
