### ISSUE TITLE
Alerting: Duplicate alert config when we duplicate a panel

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#9875]
- What Grafana version are you using? - Latest master
- What datasource are you using? - Cloudwatch
- What OS are you running grafana on? - MacOS
- What did you do? - Duplicated a panel
- What was the expected result? - Was expecting the alerts config as well to be duplicated
- What happened instead? - None of the alert config was duplicated in the new panel

**Comment by utkarshcmu** [comment]
Why did we do this? https://github.com/grafana/grafana/commit/079b0ef44ad5ee30b8be9f98e85e482c7efdb31a

Any specific reasons?

**Comment by torkelo** [comment]
To avoid duplicate alert rules.

**Comment by utkarshcmu** [comment]
Ok... so do we want to continue avoiding duplicate alert rules or should we allow duplicate alert rules when we duplicate panels? what should be the expected behavior for alert rules when we copy a panel?

If we agree on avoiding duplicate alert rules, then lets keep the code as it is.
But if we agree on duplicating alert rules when we duplicate a panel, I can make a PR for it.

Thanks! 😄

**Comment by torkelo** [comment]
Tricky, I honestly don't know which behavior is preferred.

**Comment by mike-sol** [comment]
I'd love for alerts to be duplicated - I have multiple identical environments and recreating alerts by hand is painful. I can also see how, if the dash in question has controls presently in an alert state, it could cause problems.

Probably better to offer it as an option in the Save As dialogue?

**Comment by poglazoff** [comment]
Please allow alerts to be duplicated! My current task: our company monitors 16 circuit breakers at every of 6 different locations, and want to have Telegram notification for every incident. Since variables can't be used in Alert rules, I have to create special dashboard for every location. Also I have to create separate Graph panel for every circuit breaker, since I want alerts to be independent. And now I should not only copy Graph panel with hotkeys, but also add alert back to every new panel.
BTW, I think that removing alert after copying is much simpler than adding alert back with all its settings.

**Comment by andyvig** [comment]
You should definitely allow the option to duplicate alerts.  Since we can't save provisioned dashboards the only way to persist changes is to save a copy, which wipes the alerts, which is a terrible experience if you want those alerts.  

Ultimately we're trying to create a workflow where we can modify dashboards, save them to source control and then auto-deploy to other environments.  We've accomplished this via a bit of scripting but wiping alerts makes this process more painful...

**Comment by safadig** [comment]
Definitely go for duplicate Alert...Much easier to remove/disable than to add in duplicate

**Comment by disa-faith** [comment]
An option could be to duplicate the alert by default but set it to disabled. Then it's easy to enable it by hand or discard it depending on your needs.

**Comment by lucastex** [comment]
Same case here, we have +15 elasticsearch instances and we have to create all alerts by hand, one by one. Even cloning the dashboard...

Another option would be to check if you want to clone alerts when cloning dash, the same way we already have "clone tags".

**Comment by xavier-isecurity** [comment]
Definetly duplicate the alerts, I have to clone a panel 63 times, changing just some names of the queries and the most painful part is create the alert again while I could edit just the name of it.

**Comment by fjlour** [comment]
+1 I would also love to have the ability to optionally duplicate or not the alerts embeded in a panel.
To prevent duplicate names/ids, just grafana could just add "alertname_N" as a suffix.

This kind of kills the purpose of using Grafana as a monitoring tool, if it is cumbersome to scale horizontally.

**Comment by relgisri** [comment]
Is there any update on if this feature is worked on or in some kind of consideration?
I really would like to have some kind of way to copy/duplicate my whole dashboard with the alerts for an easy management and a bigger scalability.

**Comment by adityagundecha** [comment]
We definitely need to duplicate the alert. Its way easier to delete alerts than to create one.

**Comment by igcherkaev** [comment]
+1 for allowing duplicating alerts from panel (would be nice to make it as an option when we choose to duplicate it)

**Comment by deepaksundar** [comment]
Duplicating the alerts will be helpful.. deleting doesn't require the alerting configs, but to create we need to configure it again

**Comment by astafan8** [comment]
bump! very much looking forward to being able to "make a copy" of an alert (like panels) or "save as"

**Comment by tinchopu** [comment]
yes I'd also like to be able to duplicate existing alerts- would make things easier

**Comment by mvalletta** [comment]
+1

**Comment by wardbekker** [comment]
@torkelo this issue can probably be closed as it's not relevant any more with unified alerting?

**Comment by anjuramola** [comment]
+1

**Comment by jantman** [comment]
> this issue can probably be closed as it's not relevant any more with unified alerting?

@wardbekker I'm relatively new to Grafana (or, I should say, was away for 5-ish years and now am back) but it's not at all clear to me how Unified Alerting solves this? I'm having some serious issues understanding how alerts are supposed to work with duplicated panels, "for each" rows, etc., and duplicating a panel still doesn't duplicate its alerts...

**Comment by sswarren** [comment]
Another variant that seems to work for me is to Duplicate the panel, then inspect the json for the source panel and copy over _only_ the `alert` section, and paste it into the destination panel (up near the title, or wherever; Grafana seems to rearrange it when you save).  The only ID I see in the alert section is the uid for the notifications, and I typically want that to be the same.  Then update the alert definition (at least name, message) in the json, or via the UI dialogs after applying the json change.
Changing the json feels a bit fragile and there have been times I must have changed the panel definition in the UI in another tab and got the panel into a bad way, but it usually works.

**Comment by grobinson-grafana** [comment]
With Grafana Managed Alerts (used to be called Unified Alerting) alerts are separate from dashboards/panels. While alert rules can still be associated with a dashboard/panel, dashboard/panels no longer "own" their associated alerts. With Grafana Managed Alerts, duplicating a dashboard or a panel in a dashboard un-links the alert from the duplicate, but preserves it in the original.
