### ISSUE TITLE
Cloudwatch source: Cannot read property 'metricFindQuery' of undefined

### ISSUE THREAD

**Issue by andrey-sra** [grafana/grafana#9876]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
 grafana/master@6d7eacfa814f3b30b7cd779f080a965d02ec08fb
- What datasource are you using?
Cloudwatch
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Added a CloudWatch data source and tested
- What was the expected result?
Pass
- What happened instead?
`Cannot read property 'metricFindQuery' of undefined`
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
N/A

**Comment by torkelo** [comment]
where did get this error? Can you explain more the steps you took? 

Did you get this after saving the data source? After adding a panel and editing the query? After adding a template variable?

**Comment by whereisaaron** [comment]
I started getting this error after upgrading to 4.7.0-pre1.
*All* previously operational CloudWatch dashboards and panels started failing. Some simply say 'no data points'. Some display this error on dashboard load that @andrey-sra  reported: "Templating init failed. Cannot read property 'metricFindQuery' of undefined"

![image](https://user-images.githubusercontent.com/1109585/32795862-09d1f2b2-c93b-11e7-9c20-2a4ac6d5f136.png)

**Comment by torkelo** [comment]
Can I see you template variable definitions?

**Comment by whereisaaron** [comment]
![image](https://user-images.githubusercontent.com/1109585/32797321-6ad34dfa-c93f-11e7-80fe-7e24ad53362d.png)

**Comment by utkarshcmu** [comment]
I am facing this same issue.... in latest master......

**Comment by utkarshcmu** [comment]
I upgraded grafana from (4.7.0-10113pre1) to (4.7.0-10190pre1) and now all the cloudwatch dashboards are showing no datapoints....
