### ISSUE TITLE
How to create new user roles?

### ISSUE THREAD

**Issue by ubaidsworld** [grafana/grafana#9877]
I am trying to look for an option in grafana, so that I can assign new user role apart from the the default ROLES what grafana already have.

I want to have a separate dashboard for the users so that will be able to perform the task that is for them only and will not get reflected on other persons dashboard.
I hope my query and issue is clear. Looking for a solution

**Comment by bergquist** [comment]
That's currently not possible but something we are working on. In Grafana 5.0 we will introduce dashboard folders and user groups that you can associate with a dashboard folders.

**Comment by nthienan** [comment]
Really need a way to create custom roles with different permissions to existing roles (admin/editor/viewer). My situation is exactly same as what @mcarbonneaux wants

**Comment by ZVilusinsky** [comment]
Commenting here, as I am just going through the same issue. Need to assign user (from external company) to view a single dashboard. But as he has to be at least viewer role, so he can see all dashboards with viewer permissions. There is no effective way to block his access to other dashboards without creating a new organisation role.
