### ISSUE TITLE
MySQL datasource can't display Chinese in Panels correctly. 

### ISSUE THREAD

**Issue by sanmalove0** [grafana/grafana#9878]
- What Grafana version are you using?
 grafana-4.6.0-1.x86_64
- What datasource are you using?
MySQL 5.1 
- What OS are you running grafana on?
CentOS 5
- What did you do?
Use MySQL as the datasource to display some Chinese in Panels.
- What was the expected result?
Display Chinese correctly.
- What happened instead?
The Chinese are displayed as ????

I want to ask whether the MySQL version caused the problem. Or I can set the character set somewhere. The database is already set to utf8.
---------------------------------------
I tried another MySQL database of 5.1 version, even the character set is Latin1, Chinese can be displayed correctly in the panels. So I am confused why in the first database, Chinese can't be displayed correctly.

**Comment by torkelo** [comment]
Try a newer version of MySQL that supports utf8mb4 , then it should work
