### ISSUE TITLE
GitHub authentication failure (using postgres as a backend)

### ISSUE THREAD

**Issue by dictvm** [grafana/grafana#9881]
- What Grafana version are you using? 4.6.1
- What datasource are you using? PostgreSQL 9.6.3 (AWS RDS)
- What OS are you running grafana on? Debian 8 (official Dockerhub Grafana image running in Kubernetes)
- What did you do? We configured Grafana to authenticate users against our Github org with a Postgres backend.
- What was the expected result? Users with a Github account that's in our organisation should be able to login to Grafana.
- What happened instead? The user gets a "Server side error :(" message. The Grafana log contains the the snippet attached below.

Grafana is configured mostly via env vars and they have been confirmed to work for most of our users, except for the one who reported this issue. 

These env vars are:
```
GF_SERVER_ROOT_URL
GF_AUTH_GITHUB_ENABLED
GF_AUTH_GITHUB_ALLOW_SIGN_UP
GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
GF_AUTH_GITHUB_SCOPES
GF_AUTH_GITHUB_TEAM_IDS
GF_AUTH_GITHUB_CLIENT_SECRET
GF_AUTH_GITHUB_CLIENT_ID
```

The actual error message from the logs:
```
t=2017-11-14T10:03:55+0000 lvl=eror msg="Failed to create account" logger=context userId=0 orgId=1 uname= error="pq: duplicate key value violates unique constraint \"UQE_user_login\""
t=2017-11-14T10:07:32+0000 lvl=eror msg="Failed to create account" logger=context userId=0 orgId=1 uname= error="pq: duplicate key value violates unique constraint \"UQE_user_login\""
t=2017-11-14T10:09:14+0000 lvl=eror msg="Failed to create account" logger=context userId=0 orgId=1 uname= error="pq: duplicate key value violates unique constraint \"UQE_user_login\""
```

**Comment by torkelo** [comment]
Someone else (with a different) email must have his username. 

Can you go to Grafana > Admin > Global Users > search for the user (by his github username) and if it's not another user, remove it .
