### ISSUE TITLE
Support dashboard PNG rendering 

### ISSUE THREAD

**Issue by vasekch** [grafana/grafana#9883]
EDIT: changed wording to fit "feature request" rather than original "bug" nature.

**User Story**
As a Grafana user/admin I'd like to be able to get PNG images of whole dashboards, not just only single panels, on a special URL.

**Technical**
It already works in 4.6.1 when instead of single panel rendering url, ie.`...grafana/render/dashboard-solo/db/mydashboard?panelId=4&width=...`, you'll use original dashboard url with `render/` prefix, ie. `grafana/render/dashboard/db/mydasboard?width=...`. Still need rendering parameters as per [docs](http://docs.grafana.org/reference/sharing/#direct-link-rendered-image), but no need for `panelId` any more.

This feature implementation should include changes to the docs on http://docs.grafana.org/reference/sharing/#direct-link-rendered-image

Only issue I encountered was when dashboard contained 'empty space', fix is simple, see bellow.

Not sure if some UI component should better be stripped from the page before render (control buttons like 'add row'). These may be cropped additionally, though.

_IDEA1_ it may be nice to add render parameters for edge cuts, like "crop_bottom=20" resulting in cropping bottom 20px of how full page render is.

_IDEA2_ it may be nice to add more logging (console.log in addition to current errors) and have them both propagated to main grafana log for more convenient debugging (ie. errors in scripted dashboards). Another logging improvement may be recording number of panels rendered vs. total page when timeout is reached to help identify timeout origin.

_IDEA3_ pictures stored at `/var/lib/grafana/png` may be removed once the file has been served.

**Original bugreport**
- version: Grafana 4.6.1
- datasource: independent
- OS: centos 7
- What did you do? directly render dashboard with empty space by prepending '/render/'
- What was the expected result? get PNG image
- What happened instead? 500 server error (timeout internally)

My dashboard looks like this:
![image](https://user-images.githubusercontent.com/2572537/32789768-8ebef51a-c954-11e7-8a40-f2e898ff13b0.png)

To debug this, I ran render.js directly in terminal to see JS errors and edited as follows to see console.log messages (may be nice to have this by default) particularly number of panels rendered / total:
```
  page.onConsoleMessage = function(msg, lineNum, sourceId) {                                                                                                                                                       
    console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');                                                                                                                        
  }; 
  ...
  console.log('  rootScope.panelsRendered='+rootScope.panelsRendered+'  panels='+panels); 
  return rootScope.panelsRendered >= panels;
```

Output was:
```
CONSOLE:   rootScope.panelsRendered=undefined  panels=11 (from line # in "")
...
CONSOLE:   rootScope.panelsRendered=undefined  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=1  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=1  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=2  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=5  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=5  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=5  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=6  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=7  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=8  panels=11 (from line # in "")
CONSOLE:   rootScope.panelsRendered=9  panels=11 (from line # in "")
...
CONSOLE:   rootScope.panelsRendered=9  panels=11 (from line # in "")
... until time out
```

I think the problem is with this line:
```
var panels = angular.element('div.panel:visible').length;
```
As it will count empty space as panel, but that will never make it into rendered counter.

Fix is simple as changing the selector to exclude empty space panels.
```
var panels = angular.element('div.panel:visible + div:not(.panel-drop-zone)').length;
```

**Comment by ryantxu** [comment]
see also #8363

**Comment by Natalique** [comment]
+1 for grafana 5

**Comment by mr-yaky** [comment]
+1 for Grafana 6.x

**Comment by ryantxu** [comment]
Latest version of the render plugin will handle dashboards :tada:
