### ISSUE TITLE
Singlestat: Disable or hide prefix & postfix font size when gauge mode is enabled 

### ISSUE THREAD

**Issue by xenio** [grafana/grafana#9884]
Prefix and Postfix font size are not working when Show Gauge is on.

![screen shot 2017-11-15 at 00 34 01](https://user-images.githubusercontent.com/153355/32810896-5eac75b6-c99d-11e7-85a2-1059928bc71d.png)

**Comment by torkelo** [comment]
The gauge mode only has a single "value" label, and so does not not support the prefix and postfix.

Should disable the font size options when guage mode is enabled.
