### ISSUE TITLE
Support Panel Alert heart status when using now delay

### ISSUE THREAD

**Issue by bedrin** [grafana/grafana#9885]
Using Grafana 4.6.1

I've defined alerts on few panels with InfluxDB datasource.
However on predefined time ranges like "Last 1 hour" or "Last 2 days" the heart icon is always in default white state even though alert has triggered.

It is caused by the time range - predefined ranges set "to" date to "now-10s"
If I change it to "now" heart icon will turn green or red.

**Comment by torkelo** [comment]
If you have a now delay Grafana will not fetch alert status.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
