### ISSUE TITLE
elasticsearch on grafana , choose the time "today", It shows 8 points from yesterday to 8 today.

### ISSUE THREAD

**Issue by swch125** [grafana/grafana#9886]
i have the problem,when i choose the time "today".It shows 8 points from yesterday to 8 today's data,not today's data!
And i change the time zone,its use the local time zone, but data already show 8am from yesterday to 8am today, is it issue?  i wanna the data is  between 0am from yesterday to 0am today . how should i do ?

I try to change local time zone, if i change the time zone +7 , it'll show the data from 7am to 7am . it is not reasonable, pls help me ! @torkelo

**Comment by torkelo** [comment]
strange, when I select Today time range, I get a graph with time range 00:00 (the day before) to 00:00 (today)

![image](https://user-images.githubusercontent.com/10999/32835352-078063c4-ca06-11e7-9654-ae72d1e7630e.png)

What does the graph time show for you? 
http://play.grafana.org/dashboard/db/today?orgId=1

**Comment by swch125** [comment]
![tim 20171116093323](https://user-images.githubusercontent.com/24468307/32869340-685c808c-cab1-11e7-9957-edeec53aa9dc.png)
as this pic, i use the elasticsearch as my data source . I query the data which interval is one day.The local time zone is +8 utc and the column 'everyTime' which i save in ela is +8UTC too.  I wanna the Today data's time range between 00:00 to 00:00 .But, the data in week is 8AM to 8AM.  how should i do ?@torkelo

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/6222
