### ISSUE TITLE
[v5]: Panels should not be able to extend beyond their bounds. 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9887]
v5 is in develop branch (make sure you do yarn install after switch). 

- [ ] Add scrollbar to dashboard list panel, use the gemini-scrollbar component see https://github.com/grafana/grafana/blob/develop/public/app/core/components/search/search.html#L43  
- [ ] add scrollbar to alert list, use gemini-scrollbar
- [ ] add scrollbar to text panel.

**Comment by alexanderzobnin** [comment]
@torkelo should we close this issue?

**Comment by torkelo** [comment]
yes, we still have an issue with graph panel and legend (when there are many series, in legend in non table mode), not sure how to solve it yet.
