### ISSUE TITLE
Exported JSON files are not compatible with the API

### ISSUE THREAD

**Issue by beardpapa** [grafana/grafana#9890]
Dashboards exported from the admin interface are missing fields required by the API.

You can only use the file to import again through the admin interface.

The two formats should be normalized so they are interchangeable.

**Comment by torkelo** [comment]
UI Dashboard Export feature is designed to be used with the UI import feature (to share & import dashboards via grafana.com/dashboards for example).  It uses a specific import api that is a bit tricky to use as it requires user input on what local datasources the imported dashboard should use (one reason this API is undocumented). 

Use the documented normal dashboard API (http://docs.grafana.org/http_api/dashboard/) to save/load dashboards and to get dashboard json use cogs menu View JSON. 

I know this is a bit confusing and poorly documented, will think on ways we can improve this.
