### ISSUE TITLE
Grafana subpath issue using docker containers

### ISSUE THREAD

**Issue by uppalarakesh2** [grafana/grafana#9892]
Hello 
I am using docker 1.12 version and installed grafana:latest image in docker. i am able to  hit the grafana outside using 3000 port and it works fine when i try to change the subpath in /etc/grafana/grafana-ini to
root_url = http://10.2.11.111/grafana it is not working . i passed env varaiable and tried docker run -i -t -d -p 3001:3000 -e "GF_SERVER_ROOT_URL=http://10.2.11.111/grafana " . it shows {{alertitle}} as displaypage.

**Comment by torkelo** [comment]
for subpath you need a reverse proxy as well (nginx, apache), that does the url translation to the subpath

**Comment by torkelo** [comment]
http://docs.grafana.org/installation/behind_proxy/#nginx-configuration
