### ISSUE TITLE
[Feature Request] Allow passing Table Panel sort order in Url parameter 

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana#9893]
Currently Table Panel allows the rows to be sorted by any single column, by clicking on the column header.
Its stored in json as below.
```js
"sort": {
    "col": 8,
    "desc": true
  },
```

However this can't be passed as part of the dynamic URL. I have a panel shows bunch of links along with their traffic patterns. I have another dashboard where I want to give two links (e.g. Most hit, Least visited ) which should open same panel with different sort order. Can this be passed as a two URL parameters (e.g. `sortColumn=8`&`sortOrder=desc`) which is automatically applied for the panel. A dashboard level setting can control whether or not table should use it or not.

**Comment by torkelo** [comment]
closing as we have a feature request that covers this already, https://github.com/grafana/grafana/issues/9617
