### ISSUE TITLE
`/api/metrics` --> {"message":"Not found"}

### ISSUE THREAD

**Issue by quantonganh** [grafana/grafana#9894]
- What Grafana version are you using?
4.6.1

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Debian GNU/Linux 8

- What did you do?
Access to `/api/metrics` follow this doc: http://docs.grafana.org/installation/configuration/#metrics

- What was the expected result?
See internal metrics in JSON format

- What happened instead?
{"message":"Not found"}

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/commit/bfd8afaf13d7772dbb3e32e0f36a4db9ec92ee43

live in a few minutes.
