### ISSUE TITLE
timestamp format for ElasticSearch in Table panel

### ISSUE THREAD

**Issue by msteggink** [grafana/grafana#9895]
* What Grafana version are you using? Grafana v4.6.1 (commit: cac8b97)
* What datasource are you using? ElasticSearch
* What OS are you running grafana on? CentOS7 / RedHat 7
* What did you do?
I am trying to create a table of items, sorted by day. The returned timestamp is not recognized.
* What was the expected result? 
Timestamp should be formatted nicely (human readable)
* What happened instead?
The query fired to ElasticSearch contains format: epoch_millis. Table does not know how to format this.
![dateformat1](https://user-images.githubusercontent.com/13614464/32879428-37917d42-caaa-11e7-8d59-0cc2d5c45aeb.PNG)

![dateformat2](https://user-images.githubusercontent.com/13614464/32879429-37a76760-caaa-11e7-9ad8-ddb72ea093a1.PNG)

![dateformat3](https://user-images.githubusercontent.com/13614464/32879430-37bd6880-caaa-11e7-8ccd-f17893722ea4.PNG)

A solution could be to modify the table panel to recognize this timestamp, or modify the (datasource) query to allow other date formats for ElasticSearch which Grafana/Table does understand.

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/mapping-date-format.html

```
"date_histogram": {
"interval": "1d",
"field": "@timestamp",
"min_doc_count": 0,
"extended_bounds": {
"min": "1510814063355",
"max": "1510817663355"
},
"format": "epoch_millis"
}
```

The query defaults: grafana/public/app/plugins/datasource/elasticsearch/query_builder.ts

**Comment by torkelo** [comment]
what is the response from your Elasticsearch query? Seems like ES has changed how it is returning dates.

**Comment by msteggink** [comment]
I cut up the response:
```
{
  "responses": [
    {
      "took": 15,
      "timed_out": false,
      "_shards": {
        "total": 3,
        "successful": 3,
        "skipped": 0,
        "failed": 0
      },
      "hits": {
        "total": 534,
        "max_score": 0,
        "hits": []
      },
      "aggregations": {
        "3": {
          "buckets": [
            {
              "key_as_string": "1510790400000",
              "key": 1510790400000,
              "doc_count": 534,
              "6": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": [
                  {
                    "key": "Thailand",
                    "doc_count": 4,
                    "5": {
                      "doc_count_error_upper_bound": 0,
                      "sum_other_doc_count": 0,
                      "buckets": [
                        {
                          "key": "xxx",
                          "doc_count": 4
                        }
                      ]
                    }
                  },
                  {
                    "key": "Taiwan",
                    "doc_count": 5,
                    "5": {
                      "doc_count_error_upper_bound": 0,
                      "sum_other_doc_count": 0,
                      "buckets": [
                        {
                          "key": "xxx",
                          "doc_count": 5
                        }
                      ]
                    }
                  },
                  {
                    "key": "Republic of Korea",
                    "doc_count": 4,
                    "5": {
                      "doc_count_error_upper_bound": 0,
                      "sum_other_doc_count": 0,
                      "buckets": [
                        {
                          "key": "xxx",
                          "doc_count": 4
                        }
                      ]
                    }
                  },
                ]
              }
            }
          ]
        }
      },
      "status": 200
    }
  ]
}
```

**Comment by akrus** [comment]
Would be nice to have it as unix timestamp is not really user-friendly :-/

**Comment by volter** [comment]
I think the problem happens because the query results used stem from the _source field. We are indexing a field, that is not the primary time field of the document, as type "date" and "epoch_second". In the current state, this results in a query result like this:

```
...
"_source" : {
   "@timestamp" : "2018-08-29T10:28:33.587216+02:00",
   "mydate" : 1535532513
},
"fields": {
  "@timestamp" : [  1535531313587 ]
},
...

```

The fields hash is filled with "casted" data for selected fields. If the interface exposed an option to select certain fields to be added to the docvalue_fields list in the query , that would allow to properly cast any date format -- no matter how it was indexed.

**Comment by aocenas** [comment]
Considering how old this issue is I am closing it now, please reopen if this persists in new versions of Grafana.
