### ISSUE TITLE
Singlestat panel not showing latest value (prometheus)

### ISSUE THREAD

**Issue by matejzero** [grafana/grafana#9899]
- What Grafana version are you using?
4.6.1

- What datasource are you using?
Prometheus

- What OS are you running grafana on?
Linux (CentOS 7)

- What did you do?
Created a singlestat panel with the following query:
```
irate(logstash_node_pipeline_events_in_total{instance=~"logstash.domain.tld"}[20s])
```

and set options->value->stat to *current*.  

- What was the expected result?
When I shutdown service and metric doesn't exist anymore in current time (Prometheus console is showing no data), singlestat should also show 0 oz N/A, since it shouldn't have any data for "current" timestamp.

- What happened instead?
Value was non-zero (it had some value which would made sense if the service was running and was changing with every refresh). Looking at spark line, it's cleary seen that there are no new data available.

If I run the same query in Prometheus explorer, I get no data, since there are non available for the current timestamp.

I hope search-foo did not fail me and I missed a ticket solving this problem.

![screen shot 2017-11-16 at 14 02 11](https://user-images.githubusercontent.com/4689252/32892527-cce6f8be-cad6-11e7-83c5-aaead7bd1c4c.png)

- If related to metric query / data viz:
  - Request URL: https://grafana.domain.tld/api/datasources/proxy/32/api/v1/query_range?query=irate(logstash_node_pipeline_events_in_total{instance="logstash.domain.tld"}[30s])&start=1510833896&end=1510837496&step=60
  - Request params:
```
  query irate(logstash_node_pipeline_events_in_total{instance="logstash2.arnes.si"}[30s])
  start 1510833896
  end 1510837496
  step  60
```
 
  - Response:
```json
{  
  "status":"success",
  "data":{  
    "resultType":"matrix",
    "result":[  
      {  
        "metric":{  
          "instance":"logstash.domain.tld",
          "job":"logstash"
        },
        "values":[  
          [  
            1510834436,
            "709.3"
          ],
          [  
            1510834496,
            "475.2"
          ],
          [  
            1510834556,
            "508.8"
          ],
          [  
            1510834616,
            "468.7"
          ],
          [  
            1510834676,
            "521.9"
          ],
          [  
            1510834736,
            "675.9"
          ],
          [  
            1510834796,
            "606"
          ],
          [  
            1510834856,
            "718.9"
          ],
          [  
            1510834916,
            "465.2"
          ],
          [  
            1510834976,
            "699.1"
          ],
          [  
            1510835036,
            "486.1"
          ],
          [  
            1510835096,
            "693.4"
          ],
          [  
            1510836656,
            "630.9"
          ]
        ]
      }
    ]
  }
}
```

**Comment by bergquist** [comment]
Weird...I don't understand why you get 779 instead of 630. Might be due to a bug in the singlestat panel not rerendering when changing the stat property. 

The values in the result seem to be in the range of your query so that seems correct? 

Just so you know we added support for instant queries/console in 4.6. Which might be what you want in this case.

**Comment by matejzero** [comment]
If I set 'current' in singlestat panel, should it show the last value that it gets from the query? Even if that  value is 14min old?

If you look at the timestamp, value 630 was at 1510836656 and end parameter for query was 1510837496. Diff is 840s (14min), so 630 was 14 minutes old.

I'll take a look at instant queries.

**Comment by bergquist** [comment]
`Current` will give you the last value in the serie. 

The name is kinda weak. I guess a better name would be `Last`

**Comment by matejzero** [comment]
Ok, I get it now:)

Instant queries solved my problem.

**Comment by AndreaFranchini** [comment]
Same exact problem here.

I'm monitoring a process RSS with a Singlestat.
- stat: current
- query: processRSS{job='leads'} / 1024 / 1024
- value mapping: null => N/A

When I stop the process i'm expecting to see N/A, but instead Grafana keep showing the last value, even if Prometheus show "No Data".

**Comment by andy-han** [comment]
@AndreaFranchini did you find a solution? I'm facing a similar issue

**Comment by AndreaFranchini** [comment]
Unfortunately not

**Comment by pmcossey** [comment]
Hello
Facing the same issue, I use the parameter "step" in metrics panel.
I have a metric polled every minute and have to set step value at "1s" to get the real last value.
If you leave it blank, value displayed seems to depend on selected time range.
