### ISSUE TITLE
reCaptcha integration with login

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#9900]
We are using LDAP authentication for login. Recently, we faced some brute-force attack to our grafana application and most of the user accounts were locked out.  Is it possible to setup maximum retries to the login to avoid BF attack or it would be nice if we **integrate reCaptcha for login to reduce attacks**.  

What Grafana version are you using? - 4.6.1
What datasource are you using? - NA
What OS are you running grafana on? - Ubuntu

**Comment by bergquist** [comment]
That's a good suggestion. But I'm closing this since its a dupe of https://github.com/grafana/grafana/issues/7616
