### ISSUE TITLE
Table panel with multiple data sources in table format does not show data correctly.

### ISSUE THREAD

**Issue by genzo0101** [grafana/grafana#9904]
Table panel with 2 data sources does not show data in Table format correctly.

- grafana-4.6.2-1.x86_64.rpm
- 2 prometheus data sources
- RHEL 7.3
- What I did
  - set up 2 data sources of prometheus
  - create a dashboard and a table panel on it
  - set datasource "--Mixed--" in Metrics tab
  - set a querie for each data sources (2 queries overall)
- The expected result is data from both data source can be seen in table panel with Table format.
- What happens instead
  - Only data in Table format from first data source shows up in table, but data in Table format from second data source does not.
  - Data from 2 data sources in "Time series" format show up correctly, which means both data sources and panel are working. The issue happens only when Table format is selected.

**Comment by torkelo** [comment]
The table panel only supports a single table query. If a query returns table data it will only take the first response.

**Comment by mvintila** [comment]
Is this going to be fixed? If not, shouldn't the Mixed option be disabled for Table?

**Comment by vldbel** [comment]
+1 for previous question. Current behaviors is misleading.
