### ISSUE TITLE
Found row with no time value

### ISSUE THREAD

**Issue by fatg1988** [grafana/grafana#9908]
Please include this information:
- What Grafana version are you using?  docker run grafana/grafana
- What datasource are you using? mysql
- What OS are you running grafana on? centos 7.1 3.10

I am getting this error in Grafana.
Found row with no time value

![default](https://user-images.githubusercontent.com/3365952/32941405-afa4924e-cbc0-11e7-97bb-284ccd187c3d.png)

when choose Fomat as table : can see one row returned:

![default](https://user-images.githubusercontent.com/3365952/32941452-cc3b2a26-cbc0-11e7-8b65-fc52225c6a7f.png)

**Comment by svenklemm** [comment]
The time column in mysql needs to be named time_sec not time unless you are doing an annotation query.
So your query should like something like this:
```
SELECT type as metric, date_at as time_sec, click_count as value FROM click where $__unixEpochFilter(date_at)
```

**Comment by daniellee** [comment]
@fatg1988 Closing this as @svenklemm has pointed out the problem. Can reopen if it turns out it is a bug.
