### ISSUE TITLE
Introduce new template variable interpolation syntax that allows for formatting options

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9911]
The initial work to support Graphite tags was implemented in https://github.com/grafana/grafana/issues/9230 but there are issues remaining to fully support multi valued template variables. 

In order to be able to have on data source that can use both globing and regex formating for multi valued variables we need to extend the variable interpolation syntax to support formatting option. 

New syntax: 

```bash
${servers:regex}
```

Which means we have to add this syntax to interpolation engine in frontend and in backend.

**Comment by shanson7** [comment]
Currently, these sort of options are set in the template variable config, rather than at the use of the variable. Should it be possible to configure a default way to interpret the variable when configuring it?

**Comment by mtanda** [comment]
If possible, I want to extend this feature to support multiple step transformation.
For example, AWS EC2 Instance Name to Instance ID.

```
${instance_names:names_to_ids:regex}
```

When templating feature convert template values, it calls some datasource API like `interpolateQueryExpr`, and datasource plugin handle `names_to_ids` conversion.
https://github.com/grafana/grafana/blob/v5.0.0-beta4/public/app/plugins/datasource/prometheus/datasource.ts#L57

**Comment by bergquist** [comment]
This requires documentation before it can be consider done.

**Comment by torkelo** [comment]
closing as this was merged in v5.0

**Comment by bergquist** [comment]
> This requires documentation before it can be considered done.

@torkelo I saw that you opened a new issue for that but I think it's better to include the docs work in the same issue. Makes it easier to correlate and I don't think we should consider issues done until we have docs.

**Comment by torkelo** [comment]
ok, that is not how we usually do it (we usually create docs issues?), but might be good to enforce docs as part of a bigger issue. But very confusing in this case as to what release it is included in as this was included in v5.0
