### ISSUE TITLE
Avatar in annotations jiggles on hover

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#9916]
- Grafana version: v4.6.0
- Reproducible at: <https://dashboard.sitespeed.io/dashboard/db/browsers?orgId=1>

Point to an annotation's vertical line and then hover towards the tag (e.g. "Update" in the above example). When doing so, the circular crop around the avatar appears to shift by 1px up and down.

![Screen capture](https://user-images.githubusercontent.com/156867/32968434-0fca65e8-cb96-11e7-9083-ebb6efe99e48.gif)

**Comment by bergquist** [comment]
@Ijin08 could you take a look?
