### ISSUE TITLE
Support two levels of sub queries with graphite in alerting

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#9917]
- Grafana version: v4.6.1
- Datasource: Graphite
- OS: Linux

I have the following metric queries in a graph panel:

<img width="567" alt="screen shot" src="https://user-images.githubusercontent.com/156867/32975600-ab9ec816-cbbd-11e7-801f-9d486c50d79d.png">
<img width="378" alt="screen shot" src="https://user-images.githubusercontent.com/156867/32975601-abb8016e-cbbd-11e7-87a1-844631ae5c27.png">

When an alert started with a reported value of `1.023...` I assumed this was happening because one of the embedded queries must've been null and somehow produced an odd value due to Graphite assuming 0 for null in most contexts.

However, even after changing the alert to query from "1h, 5m" instead of "1h, now", it was still happening.

Furthermore, inspecting the raw data in the Alert panel shows that this isn't just about the last value but about **all values**.

<img width="650" alt="screen shot" src="https://user-images.githubusercontent.com/156867/32975632-09c6a0ee-cbbe-11e7-87cc-55fe860464aa.png">
<img width="600" alt="screen shot" src="https://user-images.githubusercontent.com/156867/32975634-12d7a94e-cbbe-11e7-8676-f49f3d729f40.png">

**Comment by bergquist** [comment]
This is a problem with graphite subqueries and Grafana alerting. 
The current support is very limited so I suggest you build one long query for alerting at the moment.

**Comment by torkelo** [comment]
We support queries like this already as long as the query was created originally in grafana v4.4 or later, try removing the last query and recreate it.

**Comment by Krinkle** [comment]
I deleted the alert, the panel and the row, and re-created them scratch but still got the same issue.

In the end I worked around it by using a slightly different query. (See below.)

I suspect that maybe the reason it was still failing is because I did not save and refresh the dashboard in between the deletion and re-creation, so something was perhaps still caching on the computed query. This problem is also described at https://github.com/grafana/grafana/issues/9918. I'll close this in favour of that for now.

<img width="859" alt="screen shot 2017-11-21 at 11 02 46" src="https://user-images.githubusercontent.com/156867/33091290-86d279ec-ceab-11e7-8f35-7442bb90023b.png">

**Comment by Krinkle** [comment]
Re-opening because I've tried everything I can think of (re-create alerts, panels, rows, including saving in-between), but I'm at a loss. As far as I can tell, I get the same internal server error no matter how much I change, or re-create the alert.

<img width="1012" alt="screen shot 2017-11-21 at 15 47 47" src="https://user-images.githubusercontent.com/156867/33102822-735c8f24-ced3-11e7-957d-523ebb3bbcf2.png">
<img width="774" alt="screen shot 2017-11-21 at 15 48 03" src="https://user-images.githubusercontent.com/156867/33102828-7b0d1522-ced3-11e7-97e7-86198fe4acfe.png">

**Comment by daniellee** [comment]
@Krinkle what is the error in the grafana server log? It is probably an unreadable Graphite stacktrace but just to sanitycheck that it is not something else.
