### ISSUE TITLE
Alert condition disagrees with logged result

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#9918]
- Grafana version: v4.6.1

An alert started firing. Allegedly with state "No Data".

However, the alert in question specifically states that "No data" should result in "Keep Last State", and this configuration has not changed recently.

Also, it appears the raw alert details show that it triggered the alert because `[true OR false] = true`. Yet, those same raw details indicate both fields as `false`, not `true`. Where is the `true` coming from? 

<img width="937" alt="screen shot" src="https://user-images.githubusercontent.com/156867/32976504-11d24b86-cbcc-11e7-8f5b-ddda937fd452.png">
<img width="747" alt="screen shot" src="https://user-images.githubusercontent.com/156867/32976510-3183453e-cbcc-11e7-9ee3-07b4300728c8.png">
<img width="1391" alt="screen shot" src="https://user-images.githubusercontent.com/156867/32976515-5cddbf16-cbcc-11e7-8f73-2bda64aceb95.png">

**Comment by soulgalore** [comment]
I think the alerts has a reference to an old query (we used to have another query there). I've removed the alerts, saved the dashboard, recreated the alerts, saved the dashboard and the alert stopped firing.

**Comment by Krinkle** [comment]
For some of Wikimedia's alerts, @soulgalore was able to workaround this bug by avoiding `diffSeries()` and `asPercent`, and instead using `divideSeries` with `offset(-1)`. However there are still various alerts going off with nonsensical data.

Here is one for example, alerting for "median above 20" when in fact all values close to or below 0. And even the test data agrees with this, and yet that same test data also claims that the alert is meant to be firing. This doesn't make sense.


<img width="978" alt="screen shot 2017-11-29 at 12 22 13" src="https://user-images.githubusercontent.com/156867/33397352-425725fa-d500-11e7-87d4-3dbdb86979a5.png">
<img width="1116" alt="screen shot 2017-11-29 at 12 22 21" src="https://user-images.githubusercontent.com/156867/33397358-44780cb4-d500-11e7-942e-e283d20ea1ba.png">
<img width="1108" alt="screen shot 2017-11-29 at 12 22 26" src="https://user-images.githubusercontent.com/156867/33397359-4499a3d8-d500-11e7-871b-aba22ffaf74d.png">
