### ISSUE TITLE
Graph comparison for the same metric for 2 different dashboards.

### ISSUE THREAD

**Issue by Abhishek321singh** [grafana/grafana#9919]
I have the kairos db + grafana setup which is working fine. To monitor my software changes[trunk] everyday  i create a new dashboard and run the same test and monitor things using grafana. Now we rollout the software every 2-3 months. To test the release software i again create a new DashBoard with the release name and run same test as i do on the trunk binary. Now my requirement is to compare the graphs only for the release software [which are in different dashboards] not the trunk binaries which means  i want to plot the graph either in the same panel without caring about the time on the X-axis. I am also very much ok to be with the graph on the different panel side by side but this should be achievable for 2 graphs residing in the different DashBoard.

Is it possible with Grafana+KairosDb?

I am very new to Grafana, your help is highly appreciated.

- What Grafana version are you using?    Grafana v4.2.0 (commit: 349f3eb) 
- What datasource are you using?      KairosDb v2.0.1
- What OS are you running grafana on?  3.13.0-116-generic #163-Ubuntu
- What did you do? Requirement Explained above
- What was the expected result? Want the same view of 2 graphs either in the same panel or side by side residing in different dashboards
- What happened instead? Don't know how to proceed

**Comment by torkelo** [comment]
Graphite is the only TSDB right now that supports timeShift,

Closing this as there are other similar feature requests:
https://github.com/grafana/grafana/issues/288
https://github.com/grafana/grafana/issues/300
