### ISSUE TITLE
The play.grafana.org  elastics demo case  failed

### ISSUE THREAD

**Issue by billychou** [grafana/grafana#9920]
Annotation Query Failed  HTTP Error (502) Bad Gateway  appeared in the play.grafana.org  elastics demo case. 
![image](https://user-images.githubusercontent.com/3585362/32981257-a23b6a50-cc39-11e7-82f7-13cbd0f32e3d.png)

**Comment by bergquist** [comment]
Thank you for reporting!

This has been fixed.
