### ISSUE TITLE
Timezones not displaying propery when querying from redshift via postgres connection

### ISSUE THREAD

**Issue by jaredswarren** [grafana/grafana#9921]
Please include this information:
- What Grafana version are you using?
Grafana v4.6.1 (commit: cac8b97)

- What datasource are you using?
Postgres (against an AWS Redshift instance)

- What OS are you running grafana on?
Linux

- What did you do?
1.  Load a table with data in my local timezone ('America/Chicago', aka -0600), and with the timezone explicitly provided in the insert (and the timezone set to America/Chicago on the host where the web browser is running).

EXAMPLE SQL to create test data:

create table public.tzdata (date timestamp, value int)
insert into public.tzdata values 
('2017-11-18 22:00:00 America/Chicago', 1)
insert into public.tzdata values 
('2017-11-18 23:00:00 America/Chicago', 2)

I verify the data with this query (with the timezone included in my client date format string) - this proves the data loaded in to redshift correctly, with the correct timezone:

select * from public.tzdata
date	value
2017-11-18 22:00:00 -0600    1
2017-11-18 23:00:00 -0600    2

2.  Create a new graph in grafana with the following query and set the time range to include (at least) 11-18-2017 22:00 - 11-18-2017 23:00:

SELECT
  $__time(date), value
  from public.tzdata
WHERE
  $__timeFilter(date)
order by date

- What was the expected result?
I expected to see a graph with the value "1" at 11/18/2017 22:00 and "2" at 11/18/2017 23:00.  

- What happened instead?
Instead, the value of "1" is at 11/18/2017 16:00 and "2" at 11/18/2017 17:00.  It appears Grafana isn't adjust the timezone correctly (like it does for other data sources)

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
Raw request:
{"from":"1510983110536","to":"1511155910536","queries":[{"refId":"A","intervalMs":120000,"maxDataPoints":1048,"datasourceId":4,"rawSql":"SELECT\n  $__time(date), value\n  from public.tzdata\nWHERE\n  $__timeFilter(date)\norder by date","format":"time_series"}]}

Raw response:
{"results":{"A":{"refId":"A","meta":{"rowCount":2,"sql":"SELECT\n  date AS \"time\", value\n  from public.tzdata\nWHERE\n  extract(epoch from date) BETWEEN 1510983110 AND 1511155910\norder by date"},"series":[{"name":"value","points":[[1,1511042400000],[2,1511046000000]]}],"tables":null}}}

**Comment by svenklemm** [comment]
If you wanna have timezone information in your dates you need to use timestamptz. Alternatively you can use timestamp and save dates as utc. timestamp datatype strips timezone information.

**Comment by jaredswarren** [comment]
Confirmed that this fixes my test case.  (switched data type to 'timezonetz').  Closing this issue with gratitude for your guidance....and heading off to fix my real life situation....
