### ISSUE TITLE
[BUG] Unable to select certain table transfroms from the options panel

### ISSUE THREAD

**Issue by mayt** [grafana/grafana#9927]
Please include this information:
- What Grafana version are you using? 
master

- What datasource are you using? 
Prometheus

- What OS are you running grafana on? 
Mac OS

- What did you do?
1. I create a new table.
2. Input some metrics and leave the `Format As` dropdown box as `Table`.
3. Proceed to the `Options` Panel
4. Go to the `Table Transform` and pick `Time series aggregations`

- What was the expected result?
Grafana gives me the time series aggregations table.

- What happened instead?
While the table content remains unchanged and get the following exception:
```
angular.js?10a4:14700 TypeError: Cannot read property 'length' of undefined
    at TimeSeries.isMsResolutionNeeded (time_series2.ts?98c9:238)
    at new TimeSeries (time_series2.ts?98c9:60)
    at Object.transform (transformers.ts?783e:93)
    at transformDataToTable (transformers.ts?783e:235)
    at TablePanelCtrl.render (module.ts?29d8:121)
    at TablePanelEditorCtrl.render (editor.ts?308f:81)
    at TablePanelEditorCtrl.transformChanged (editor.ts?308f:77)
    at fn (eval at compile (angular.js?10a4:33885), <anonymous>:4:184)
    at ChildScope.$eval (angular.js?10a4:18423)
    at eval (angular.js?10a4:26308)
```
Note: Refreshing the time resets the `Table Transform` back to `Table`
Note 2: The opposite issue happens when selecting in `Metrics` Panel, `Format as` `Time Series` first. The following exception is printed when toggling the `Table Transform` dropdown to `Table`
```
{message: "Query result is not in table format, try using another transform."}
```

**Comment by torkelo** [comment]
Only prometheus has a result property (InfluxDB has a differently named property) and other datasources do not have this setting at all.

The query format is decided from the metrics tab. I agree that this is not ideal from a UX perspective.

**Comment by torkelo** [comment]
What could be another solution is a to show an error message saying the transform cannot be used as the query returns table data (not time series)
