### ISSUE TITLE
Change user group concept name to teams

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#9930]

**Comment by torkelo** [comment]
So this requires a lot renames

1) Rename model property & code variables in the backend go code (and go tests)
2) Rename database column (you do not need to do a migration for this we can manually handle that) 

Sorry this is pretty boring task, but it's important to do this before we merge to master (as we cannot change db migrations in master)

**Comment by alexanderzobnin** [comment]
@torkelo what you mean "manually"? Should I change `addUserGroupMigrations()` and `addDashboardAclMigrations()` instead of adding new for teams?

**Comment by torkelo** [comment]
yes, I mean you can change those migrations instead of adding a new migration. Will be a bit of a pain for us running develop branch but that is fine.
