### ISSUE TITLE
Group BY Time($__interval)

### ISSUE THREAD

**Issue by Franra** [grafana/grafana#9931]
Hello,

I have read "the interval variable" from Grafana : http://docs.grafana.org/reference/templating/#the-interval-variable.
What I understand is that when you set "Group BY Time($__interval)" the $__interval is calculated using the time range and the width of the graph. So the $__interval is kind of an auto scaling variable.

My problem is that i whant to set the variable using the "Templating" option and disable the auto scaling. Because this comportment return false values.

- What Grafana version are you using?
4.3.2
- What datasource are you using?
InfluxDB 1.2.4
- What OS are you running grafana on?
Linux 3.10 (RHEL 7.1)
- What did you do?
![image](https://user-images.githubusercontent.com/33827929/33012484-58ca55d0-cde1-11e7-9458-9ffa452ebd2d.png)

![image](https://user-images.githubusercontent.com/33827929/33014465-afc63ec0-cde7-11e7-86eb-431661701865.png)

- What was the expected result?
![image](https://user-images.githubusercontent.com/33827929/33014492-ce37bcee-cde7-11e7-9d81-528a757d9cc5.png)

- What happened instead?
When you look at the min max avg and current values you can see that the data are completly wrong when I use the "Group BY Time($__interval)" for a large period of time. But it works fine for a 6 hours span for example or when I set "Group BY Time(5m)": 

![image](https://user-images.githubusercontent.com/33827929/33014522-e741f812-cde7-11e7-997d-63abd55a976e.png)

**Comment by daniellee** [comment]
If you are writing queries for InfluxDB then you do not usually use the $__interval variable directly. As I can't see the raw data here, I can only guess what is wrong - that the Min time interval is set too low and you are getting nulls for some timestamps. This results in gaps and a line cannot be drawn. (You can see this by choosing Points as the draw mode on the display tab). 

Have a look at the demo dashboard for InfluxDB on the [play site](http://play.grafana.org/dashboard/db/influxdb-templated-queries?panelId=1&fullscreen&edit&orgId=1&var-datacenter=Asia&var-host=All&var-summarize=$__auto_interval_summarize) and how it uses the Min time interval field:

![image](https://user-images.githubusercontent.com/434655/33018002-da6ae06a-cdf4-11e7-86c6-7e52aeab0c9a.png)

**Comment by zoltanbedi** [comment]
I think this question is answered by Daniel.
