### ISSUE TITLE
display others in grafana

### ISSUE THREAD

**Issue by TomasJavurek** [grafana/grafana#9938]
Imagine example of 25 series. My aim is to display only 10 largest series and the rest cover by 'others'. My approach was to display breakdown (10 series) and all 25 by one color as all. The difference is then the others.

The following graph is done with two series:

![stack-grafana](https://user-images.githubusercontent.com/33832672/33026017-cb36213e-ce0f-11e7-9aec-e4561a65c839.png)

first serie include a breakdown by some parameter A. With this serie, I want to show only 10 most occupied by parameter A and stack these 10 series on top of each other. The second serie (violet) represents all - doing a sum instead of breakdown by parameter.

Problem is that it is again displayed as stack on top of the first serie. But I want to put it in bacground. Then only all - best10 = others is visible.

**Comment by torkelo** [comment]
You can override stacking for specific series using style overrides in display tab (graph edit mode)

**Comment by TomasJavurek** [comment]
Well, I think my problem is bit more difficult. Basically, I have two separate series that I don't want to stack, BUT grouping by inside one of these series needs to be stacked. 

Most probably, there is more simpler way to display 'others', not related to stacking. This feature should deffinitely be there, it is really essential. Imagine that you have grouped by parameter that has 1000 values. This would perhaps even not fit into legend.

**Comment by torkelo** [comment]
You should be able to that in your query

**Comment by TomasJavurek** [comment]
The queries are on the picture. Could you please give me more info on how to achieve that?

![grafana-q](https://user-images.githubusercontent.com/33832672/33063725-9c16fb78-cea3-11e7-84d8-b11e20b94475.png)

**Comment by torkelo** [comment]
create one query so that it returns the total you want (maybe need to remove a filter or a group by to get the total you want)

**Comment by TomasJavurek** [comment]
Ok. But can you give me some example of doing aritmetic operations in queries? Honestly, I think this shall be new feature in grafana, and not pushing customers to put it query.

**Comment by torkelo** [comment]
What you describe is exactly the responsibility of the query & analytics features of your data source. What your asking is almost impossible to be implemented in Grafana (or would be extremely inefficient)
