### ISSUE TITLE
Dont show Add Annotation popover on un-saved dashboards 

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#9939]
latest grafana docker image
creating new dashboard and saving annotations directly (ctl+click , adding some stuff, hit save) -> the annotations won't save up

once you save the dashboard with a name, only then can you add annotations that will show up

**Comment by torkelo** [comment]
Eh, strange that you managed create annotations before saving? That should result in error (the add annotation pop over should not be displayed)

**Comment by ryantxu** [comment]
in 5x, you can still create an annotation on the 'new' unsaved dashboard.  It successfully creates an annotation with dashboardId=0 but then never shows it.
