### ISSUE TITLE
variable in templating not working correctly, mabye filter not working (CloudWatch)

### ISSUE THREAD

**Issue by phoppe93** [grafana/grafana#9940]
Hi Grafana Team, 

i tried to use the templating function to define variable.  The variable are needed in the next variable. When i select a stack the  server list is not updating.

![grafik](https://user-images.githubusercontent.com/19833844/33033673-853e2198-ce25-11e7-9bcf-3e2beb358191.png)

Query Option "On Dashboard Load" are for both variable active.

Is there a solution or a workarround for this issue ?

**Comment by torkelo** [comment]
when you change the stack parameter can you have chrome dev tools open and inspect the network traffic? There should be a call to /api/tsdb/query  , can you show the request body for that call (the first one if there are multiple)

**Comment by phoppe93** [comment]
![grafik](https://user-images.githubusercontent.com/19833844/33068134-a33693f2-ceb0-11e7-8b4c-39b3df2f42de.png)

@torkelo the instance id is always the same, doesnt matter what stack i choose

**Comment by torkelo** [comment]
what is the response from the first query? (the metricFindQuery) it should return an updated list of InstanceIds. 

Are you using the $server variable in the graph metric query?

**Comment by phoppe93** [comment]
results	{…}
metricFindQuery	{…}
refId	metricFindQuery
meta	{…}
rowCount	11
series	null
tables	[…]
0	{…}
columns	[…]
0	{…}
text	text
1	{…}
text	value
rows	[…]
0	[…]
0	i-002b858b6243fd0ba
1	i-002b858b6243fd0ba
1	[…]
0	i-0283beb06feedea5d
1	i-0283beb06feedea5d
2	[…]
0	i-04e9318d743adc4da
1	i-04e9318d743adc4da
3	[…]
0	i-054fef38f0c0a0665
1	i-054fef38f0c0a0665
4	[…]
0	i-06287b499d61d5718
1	i-06287b499d61d5718
5	[…]
0	i-06e595695052cca0e
1	i-06e595695052cca0e
6	[…]
0	i-0c4f563f9ba482ee7
1	i-0c4f563f9ba482ee7
7	[…]
0	i-0c8912675a4099ded
1	i-0c8912675a4099ded
8	[…]
0	i-0dc1250cba927464c
1	i-0dc1250cba927464c
9	[…]
0	i-7253c8b3
1	i-7253c8b3
10	[…]
0	i-b54e197b
1	i-b54e197b

@torkelo

**Comment by torkelo** [comment]
and when you check the server variable dropdown does it not contain those new instance ids?

**Comment by phoppe93** [comment]
@torkelo its contain all instance ids but it have to filter the instance ids of the stack.

example: 
dev-sensu
id:  i-sensu-1 , i-sensu-2
dev-bastion
id: i-bastion-node

choose the dev-sensu stack the filter have to scrape and show only the instance-id (i-sensu-1 , i-sensu-2)

But right now its always showing all instance id`s like here in the snippet
![grafik](https://user-images.githubusercontent.com/19833844/33122481-9f1c2d3c-cf77-11e7-8c87-e2947acba546.png)

DEV-LOGSTASH-KENESIS-INPUT have only 2 id (i-04e9318d743adc4da, i-06287b499d61d5718)

thats incorrect for me.

**Comment by torkelo** [comment]
But the metric find query returned a lot more than the 2, so either bug in cloudwatch api or the filters are not sent to aws correctly, thoughts @mtanda?

**Comment by mtanda** [comment]
I'll take a look.

@phoppe93 I want to know the Grafana version you use.

**Comment by phoppe93** [comment]
@mtanda 
Grafana cli version 4.6.1

**Comment by mtanda** [comment]
@phoppe93 Thanks.
Your issue is similar to https://github.com/grafana/grafana/issues/9667 .
Would you try to upgrade Grafana?

**Comment by phoppe93** [comment]
@mtanda yes its the same it works now !! thanks !
