### ISSUE TITLE
annotations without dashboardId/panelId to show up everywhere, doesn't work

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#9941]
my goal is to create annotations that simply show up on all dashboards and panels (at least those that don't have any special non-default configuration)

i'm using latest grafana docker image
http://docs.grafana.org/http_api/annotations/#create-annotation says

>  The dashboardId and panelId fields are optional. If they are not specified then a global annotation is created and can be queried in any dashboard that adds the Grafana annotations data source.

so I try this:

```
T 172.18.0.1:55394 -> 172.18.0.8:3000 [AP]
POST /api/annotations HTTP/1.1.
Host: localhost:3000.
User-Agent: Go-http-client/1.1.
Content-Length: 59.
Authorization: Basic YWRtaW46YWRtaW4=.
Content-Type: application/json.
Accept-Encoding: gzip.
.
{"Time":1511201116786,"Tags":["auto"],"Text":"Hello world"}
###
T 172.18.0.8:3000 -> 172.18.0.1:55394 [AP]
HTTP/1.1 200 OK.
Content-Type: application/json.
Date: Mon, 20 Nov 2017 18:05:16 GMT.
Content-Length: 30.
.
{"message":"Annotation added"}
```

if i understand correctly, this annotation should show up on any newly created dashboard.
because when i create a new dashboard and go to annotations, it already has the built-in annotations enabled.

I think I found out why:
```
15|1|0|1|0|0||||Hello world|||||1511200578|0|["manually added in ui"]
16|1|0|1|1|1||||fuckk world|||||1511200560|0|["auto"]
```

the fields are 0 in sqlite, yet when a dashboard does a http request it includes this:
```
..."dashboardId":1,"panelId":1,...
```

and in the source code i see:
```
        if query.DashboardId != 0 {
                sql.WriteString(` AND annotation.dashboard_id = ?`)
                params = append(params, query.DashboardId)
        }

        if query.PanelId != 0 {
                sql.WriteString(` AND annotation.panel_id = ?`)
                params = append(params, query.PanelId)
        }
```

so it won't match the annotations that i've added via the api

**Comment by Dieterbe** [comment]
one workaround i've found is i can change the filter in the dashboard to tags and use `auto`, but then I have to update all my dashboards that way, which is not practical. I just want these annotations to show up everywhere, like the docs say i can ?

**Comment by torkelo** [comment]
> my goal is to create annotations that simply show up on all dashboards and panels (at least those that don't have any special non-default configuration) 

This is not supported. You need to create an annotation query to show those annotations. Only annotations that have a dashboardId  (and panelId) will show up automatically on dashboards.
