### ISSUE TITLE
Group by 1 second shows nothing

### ISSUE THREAD

**Issue by maxp-edcast** [grafana/grafana#9942]
Hi I have CPU data coming into InfluxDB from Telegraf. I can see it fine on Grafana when I group by 10 seconds: 
![grafana1](https://user-images.githubusercontent.com/33328215/33034984-749f4016-cdde-11e7-8543-881cfc13fd50.png)

However when I change the group by to 1 second I see nothing:

![influx2](https://user-images.githubusercontent.com/33328215/33034999-865903f0-cdde-11e7-84d4-5f9c3adb2880.png)

This is the generated query for the latter, and I can see results when I paste this into the Influx console:

```
 SELECT mean("usage_user") FROM "one_hour"."cpu" WHERE ("cpu" = 'cpu-total') GROUP BY time(1s) fill(null)
```
My version:

- InfluxDB shell version: v1.4.1
- Telegraf v1.4.4 (git: unknown unknown)
- Grafana cli version 4.6.2

Note that these Influx & Telegraf versions are coming from the homebrew repositories. The grafana is the one bundled with Influx.

**Comment by msteggink** [comment]
Are you collecting metrics with the default interval of 10s? Then the interval(bucket) of 1s is too small to show anything.

**Comment by bergquist** [comment]
As @msteggink said. You cannot group by smaller values then your collection rate.

**Comment by maxp-edcast** [comment]
Cool thanks for being responsive guys :D
