### ISSUE TITLE
Support Modifying Default Dashboard Refresh Rates

### ISSUE THREAD

**Issue by codylewandowski** [grafana/grafana#9945]
We have experienced issues where a large number of our users set their dashboards to the most frequent refresh rate (5s) though in our environment there is not really a need for a rate more frequent than 1 minute. This ends up putting substantial extra load on our databases. 

Since education and training only go so far, it would be awesome if Grafana exposed a method for administrators to set what values are allowed for dashboard refreshes. Being able to remove values from the drop down in the time picker would solve most of the problems as a majority of our users just pick the most frequent option available.

**Comment by daniellee** [comment]
/duplicate #3356

and was fixed by #19416
