### ISSUE TITLE
Alert List panel options not working as expected

### ISSUE THREAD

**Issue by totorokk** [grafana/grafana#9946]
**Grafana Version**
`Grafana v4.6.1 (commit: cac8b97)`

**Option screenshot**: 
![image](https://user-images.githubusercontent.com/12398229/33041151-37741932-cdf2-11e7-8ff5-ca1126360406.png)

**API Query**: 
`/api/annotations?dashboardId=9&from=1508615543000&limit=20&newState=alerting&to=1511211143000&type=alert`. 

**What's expected**: 
It should return annotations in the last 30 days with `newState=alerting` only, and the list of annotations should change when the time range changes.

**What happened**:
* The data returns annotations in all states (including manually added ones) for this dashboard. Checking and unchecking the state filters only change the queries, but the data returned are all the same.
* While the data returns all annotations in the time range (20 items), the UI only shows 2 most recent ones (1 in "ok" state, 1 in "alerting" state), and there is no clear indication of what actual time range is used to display on the UI.

**Comment by bergquist** [comment]
Seems like something in the rendering is broken. 

To reproduce:

* Switching the `Show` dropdown in `Options` generated an error in the console. 
* Create a dashboard with alerts and alert list -> add annotations to a panel with alerts.

**Comment by torkelo** [comment]
Not sure we have ever state filters o  recent changes, they only work in current state. Think we fixed this in master by hiding the state filters

**Comment by torkelo** [comment]
Closing this as we have fixed this in master (the state filters are not shown as they have no effect when you look at state history)
