### ISSUE TITLE
Add AWS Cost Explorer API

### ISSUE THREAD

**Issue by Issif** [grafana/grafana#9953]
Hi,

AWS has launched yesterday a new API to access all raw data used by their Cost Explorer. It will be amazing to be able to create custom dashboard in Grafana to follow these new metrics. I know CloudWatch datasource is already able to display metrics about Costs, but Cost Explorer data are much more detailed.

Regards,

**Comment by vikaskoppineedi** [comment]
+1

**Comment by mtanda** [comment]
Just note. This is not CloudWatch feature. It is another AWS service.
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-explorer-api.html

To support this, need to add datasource plugin.

**Comment by moshikoy** [comment]
+1 for this

**Comment by kcl11** [comment]
+1

**Comment by Sher-Chowdhury** [comment]
+1

**Comment by jcmartins** [comment]
+1

**Comment by chamilbmll** [comment]
+1

**Comment by mateusrangel** [comment]
+1

**Comment by alanwds** [comment]
+1

**Comment by alanwds** [comment]
I just wrote a prometheus exporter to use CE API. I hope that be usefull https://github.com/alanwds/aws-cost-exporter

**Comment by suraganijanakiram** [comment]
+1 

This is a great feature to have since now a days every one is moving to cloud and AWS is having the majority of the share in the cloud.

**Comment by balda** [comment]
Be aware of the cost of this API: $0.01 per request!

**Comment by suraganijanakiram** [comment]
> Be aware of the cost of this API: $0.01 per request!

i think if they can put an option to send request like below then i hope cost wont be a big problem.
@hourly
@daily
@weekly
@monthly
etc.

**Comment by hmfritz** [comment]
+1 I'd like the ability to filter by tag for AWS Costs

**Comment by JamesDowning** [comment]
Is there any new information on this? The AWS/Billing data is very basic.

**Comment by aryak007** [comment]
Is there an update on creating a data source which talks to the AWS CE API? A timeline, perhaps?
