### ISSUE TITLE
/api/health returns HTTP 404

### ISSUE THREAD

**Issue by alexis-turpin** [grafana/grafana#9955]
Hi everyone,

We've encounter an unusual behavior while trying to deploy grafana in an HA environment.

## Situation
We've installed grafana on AWS, behind an elasticloadbalancer. Like any other load balancer we can use a health-check to validate that an instance is ready to receive request. We chose to check that /api/health returns HTTP 200. _According to what we found [here](http://docs.grafana.org/guides/whats-new-in-v4-3/#health-check-endpoint), that should be the case_.

## What we have
When we curl the api/health it seems ok
```
# curl 172.25.96.144:3000/api/health
{
  "commit": "8db5f08",
  "database": "ok",
  "version": "4.6.2"
}
```
But if we look carefully at the HTTP code returned something is off
```
# curl -I 172.25.96.144:3000/api/health
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=UTF-8
Set-Cookie: grafana_sess=95308aee1633f109; Path=/; HttpOnly
Date: Tue, 21 Nov 2017 09:11:12 GMT
Content-Length: 23
```
We receive a 404.

## Expected
HTTP 200 as explained [here](http://docs.grafana.org/guides/whats-new-in-v4-3/#health-check-endpoint). We also checked in the [handler](https://github.com/grafana/grafana/blob/0d12b37dfdbc4763e31394f621aa0c1b527f71f1/pkg/api/http_server.go#L196) and we don't understand where does the 404 come from.

**Comment by torkelo** [comment]
unable to replicate this
http://play.grafana.org/api/health

also local test
![image](https://user-images.githubusercontent.com/10999/33075816-1028d3c0-cecb-11e7-9fe1-594e40158de2.png)

Maybe you have an nginx or some proxy in-between?

**Comment by bergquist** [comment]
$ curl -I http://play.grafana.org/api/health
HTTP/1.1 405 Not Allowed
Server: nginx/1.8.0
Date: Tue, 21 Nov 2017 13:49:22 GMT
Content-Type: text/html
Content-Length: 172
Connection: keep-alive

**Comment by bergquist** [comment]
Can you configure the the loadbalancer to use `GET` requests?

`curl -I -X GET http://play.grafana.org/api/health` works fine

**Comment by alexis-turpin** [comment]
Nice catch @bergquist 

If I specify the HTTP verb (GET) it works.
