### ISSUE TITLE
no data from measurement

### ISSUE THREAD

**Issue by paulierco** [grafana/grafana#9956]
Hi all,

My issue is that i have no data when i select measurements from.
Saved query is working fine. Graphs are fine.

Without anydata in measurements is very hard for me to create new graphs.
[https://imgur.com/a/0u8LV](https://imgur.com/a/0u8LV)
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
Grafana v4.6.2
- What datasource are you using?
Influxdb
- What OS are you running grafana on?
Ubuntu
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment]
https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630
