### ISSUE TITLE
Chrome refuses to open https://play.grafana.com

### ISSUE THREAD

**Issue by paul-hammant** [grafana/grafana#9963]
https://play.grafana.org/ is using a certificate for stats.grafana.com and Chrome is refusing to go to the site.

**Comment by torkelo** [comment]
Where did you find the link? Play site is not using https.

We are going to rebuild the play site under https://play.grafana.com  but it's not ready yet

**Comment by paul-hammant** [comment]
I didn't find the link - I corrected http to https by hand as everyone should do in 2017.

GoHugo on GitHub, with Netlify and their one-click setup for LetsEncrypt for HTTPS is my recommendation.
