### ISSUE TITLE
[Bug] Useless horizontal scrollbar for table panel

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#9964]
Hi,

Version:  Grafana v4.7.0-pre1 (commit: 59eaecf) 

When you decide to Hide the Value column of a table panel because the interesting data are in the labels you have a disgracious horizontal scrollbar appearing

![screenshot-2017-11-22 grafana - k8s-cluster-resources](https://user-images.githubusercontent.com/153052/33119927-d1e722dc-cf70-11e7-8be7-d30605986564.png)

![screenshot-2017-11-22 grafana - k8s-cluster-resources 1](https://user-images.githubusercontent.com/153052/33119936-d41f0f38-cf70-11e7-83df-2ca2471ffc4d.png)

Regards.

**Comment by torkelo** [comment]
strange, unable to replicate:

![image](https://user-images.githubusercontent.com/10999/33162699-3ac6d03a-d02b-11e7-8983-f0318f3144dd.png)

What OS and browser are you using? Can you include the raw response from your metric query (found in Query Inspector in Metrics Tab)

**Comment by sylr** [comment]
I can replicate on Windows 10 * (Firefox 57 + Chrome  62.0.3202.94)

Here are screenshots on Chrome :

![grafana_scrollbar2](https://user-images.githubusercontent.com/153052/33166081-46b2ddcc-d039-11e7-8c47-7fc1f35f58f5.png)
![grafana_scrollbar](https://user-images.githubusercontent.com/153052/33166077-440c457c-d039-11e7-9988-35ec19bcee01.png)

**Comment by sylr** [comment]
```json
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/11/api/v1/query?query=avg(kube_node_info%7Bnode%3D~%22%5Ek8s.%2B%22%7D)%20by%20(node%2C%20kubelet_version)&time=1511430212"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {
            "kubelet_version": "v1.7.10",
            "node": "k8s-master-57301243-1"
          },
          "value": [
            1511430212,
            "1"
          ]
        },
        {
          "metric": {
            "kubelet_version": "v1.7.10",
            "node": "k8s-agent-57301243-0"
          },
          "value": [
            1511430212,
            "1"
          ]
        },
        {
          "metric": {
            "kubelet_version": "v1.7.10",
            "node": "k8s-master-57301243-2"
          },
          "value": [
            1511430212,
            "1"
          ]
        },
        {
          "metric": {
            "kubelet_version": "v1.7.10",
            "node": "k8s-master-57301243-0"
          },
          "value": [
            1511430212,
            "1"
          ]
        },
        {
          "metric": {
            "kubelet_version": "v1.7.10",
            "node": "k8s-agent-57301243-2"
          },
          "value": [
            1511430212,
            "1"
          ]
        },
        {
          "metric": {
            "kubelet_version": "v1.7.10",
            "node": "k8s-agent-57301243-1"
          },
          "value": [
            1511430212,
            "1"
          ]
        }
      ]
    }
  }
}
```

**Comment by pieterdejaeghere** [comment]
I can replicate this issue on grafana v4.6.2 with a dashboard with 2 of these tables:

On Firefox 57.0.4/windows7, they both render with the horizontal scrollbar.
Weirdly enough, Chrome 63.0.3239.132 renders only one with a horizontal scrollbar. If i make the table really wide (like full screen even though it has much fewer data), i can also make the last scrollbar disappear. In Firefox, it never disappears.
![table-nok](https://user-images.githubusercontent.com/24585008/35145735-35f50daa-fd09-11e7-8f6a-04d91a3afbb1.PNG)
![table-ok](https://user-images.githubusercontent.com/24585008/35145736-3613e28e-fd09-11e7-8682-6fa8e1a3576e.PNG)

**Comment by VR6Pete** [comment]
I also have this issue in IE.

**Comment by inbalzoran** [comment]
also here (chrome), it happens only on the dashboard display, when viewing only the panel it disappears (because it is bigger).
also it doesn't make sense because when enlarging and reducing the panel it appears/disappears with no logic

**Comment by inbalzoran** [comment]
![bug1](https://user-images.githubusercontent.com/6179556/36383658-7779b6dc-1595-11e8-973f-2b02970f89cc.png)
![bug2](https://user-images.githubusercontent.com/6179556/36383665-7ce9105e-1595-11e8-8b57-5aeeff682ab5.png)

**Comment by pieterdejaeghere** [comment]
Issue remains identical for me on grafana 5 with Chrome/Firefox, no change.

**Comment by daniellee** [comment]
Lots of changes were made to the scrolling in Grafana 5.1.0, is this still an issue?

**Comment by pieterdejaeghere** [comment]
It's still very present on grafana 5.1.0 on firefox 59/ internet explorer 11. (see attachment)
![capture](https://user-images.githubusercontent.com/24585008/39519774-7d2657ce-4e08-11e8-878d-f82a877bcb3e.PNG)

On Chrome, it's also present, but less disturbing
![capture](https://user-images.githubusercontent.com/24585008/39519822-9b024a8c-4e08-11e8-883d-cb9e02ef1e4d.PNG)

**Comment by daniellee** [comment]
@pieterdejaeghere have you got a dashboard that does not contain sensitive data that you can share?

I cannot reproduce this. For example, I don't see any horizontal scrollbars here (I've tried zooming in and out, different resolutions etc.): https://play.grafana.org/d/000000031/table-panel-showcase?orgId=1

**Comment by pieterdejaeghere** [comment]
I've stripped down the dashboard to the smallest version on which I can reproduce it.

The scrollbar appears as soon as data is loaded into the panel. If you need it, i can also give you a data sample.

[Location Status Copy-1526975197872.zip](https://github.com/grafana/grafana/files/2025490/Location.Status.Copy-1526975197872.zip)

**Comment by marefr** [comment]
Reproduced in #12510 and I think it's the same problem.

**Comment by YannisLamp** [comment]
Hello! I have been tinkering with the table panel for some time and I would like to make a suggestion.

In the table panel code, in renderer.ts, if these changes are made, the scrollbar does not seem to appear anymore:
<img width="391" alt="capture" src="https://user-images.githubusercontent.com/16855373/43258753-20fc6268-90d4-11e8-8f3f-6cb2753a8d04.PNG">

Basically, instead of rendering the elements and not displaying them if they need to be hidden, we could just not render them at all. (the extra display:none td seems to be what's confusing the scrollbar stuff)

This fix seems to be working for me, but I do not know if any bugs will appear to the table panel as a result.

Please let me know if this fix works for you.

**Comment by torkelo** [comment]
@YannisLamp can you submit a PR ?

**Comment by mmotoszko** [comment]
This happens to me when one of the column widths is very small. It's the same regardless of the column order. The empty values seen on the screen are indeed empty.

![image](https://user-images.githubusercontent.com/38533291/208717942-807db0cd-c964-4046-992b-5aa79a3fa580.png)
Top panel:
```
Instance: Column width: 150
Site: Column width: 58
Slave_SQL_Running: Minimum column width: 160 (no max)
Ch: Column width: 35
```
Bottom panel:
```
Instance: Column width: 150
Site: Column width: 58
Slave_SQL_Running: Minimum column width: 160 (no max)
Ch: Column width: 55
```
