### ISSUE TITLE
Templating field property in elasticsearch template query 

### ISSUE THREAD

**Issue by LeThuyVN** [grafana/grafana#9965]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by LeThuyVN** [comment]
hello,
I have 2 variable: 

$field    {"find": "fields", "type": "keyword"}
and $query   {"find": "terms", "field": "$field"}

However, variable 2nd is not run, do you know why? any solutions for this case?
Many thanks

**Comment by torkelo** [comment]
When you change the frist variable you see no query to fetch values for the second? 

I am unable to replicate this: works fine here: 
http://play.grafana.org/dashboard/db/elasticsearch-templated?orgId=1&var-source=backend&var-host=All&editview=templating

Strange, not sure what could be wrong for your. 

Can you have chrome dev tools > network tab open (clear it), then change the first variable. Should see a request made for the second variable. _msearch?search_type=...

**Comment by LeThuyVN** [comment]
hello, my main idea here is we add dynamic variable for Field, when variable changes the value, the field will change value. in your example, it is static value. we can change it automatic

**Comment by torkelo** [comment]
to fix this requires a trivial change here, https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.ts#L383 

the query.field also needs to be interpolated

**Comment by LeThuyVN** [comment]
hii torkelo,
I want to create dynamic value for field, when the variable change the value in field will change automatically. Like

$field {"find": "fields", "type": "keyword"} >>> List all fields we have with type = keyword
when we chose value of fields we have corresponding results for $query
$query {"find": "terms", "field": "$field"}

for example if $field is source.keyword
$query is /usr/share/filebeat/customerLogs/counters1
/usr/share/filebeat/customerLogs/counters2
/usr/share/filebeat/customerLogs/counters3
/usr/share/filebeat/customerLogs/counters4
.....

similar if the value of $field changes to hostname.keyword, server.keyword, ... we have values for $query


I tryed to do it a lot of time in grafana but it is not successful, do you know the way to do it

**Comment by torkelo** [comment]
I understand your issue, I said it needs a change in Grafana. Please don't post your problem on every elasticsearch issue, that is very rude.

**Comment by LeThuyVN** [comment]
oh, sorry

**Comment by Jonnymcc** [comment]
@torkelo I noticed looking at your example here http://play.grafana.org/dashboard/db/elasticsearch-templated?orgId=1&var-source=backend&var-host=All&editview=templating that at first the host picker has a list of hosts. But if I change the source picker to site and *then back* to backend, the host picker does not list the hosts as it did before. Is the problem that when picking a value the other variable queries do not execute? Seems like it works, until you change one of the variables. Is that still related to the datasource code? Seem like an on-change trigger is missing.

**Comment by marefr** [comment]
This seems to already have been fixed. Working demo: https://play.grafana.org/d/6sTHGm1mk/elasticsearch-templating-issue-9965?orgId=1

Closing this now, but will consider reopen if I misunderstood something.
