### ISSUE TITLE
Render tracing data from Kamon tracing like sequence chart

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#9968]
I use influxdb to store metrics and tracing data from Kamon, and I am wondering if Grafana could support render tracing data in sequence chart just like zipkin web UI in the future.

Kamon tracing:
http://kamon.io/documentation/kamon-core/0.6.6/tracing/core-concepts/

Zipkin web UI:
![zipkin web UI](http://zipkin.io/public/img/web-screenshot.png)

**Comment by bergquist** [comment]
Supporting tracing in Grafana would be really cool. Internally we use Jaeger and like it a lot. This won't be on our short time roadmap but maybe some time in the future :)
