### ISSUE TITLE
How to configure the same alerts for every servers in the cluster?

### ISSUE THREAD

**Issue by pdu** [grafana/grafana#9976]
I have got a cluster of more than 100 servers, I want to configure the disk usage alert for all the servers.

The trigger point is sending out the alert when the disk usage is more than 90%.

What's the most efficient way to do the job?

**Comment by torkelo** [comment]
Use a query that returns a series for every server (using a wildcard or regex)

Read the docs how this works
http://docs.grafana.org/alerting/rules/#multiple-series

Also this issue is relevant 
https://github.com/grafana/grafana/issues/6041
