### ISSUE TITLE
Prometheus does not need the escape of the period.

### ISSUE THREAD

**Issue by myokoo** [grafana/grafana#9977]
we are using
 - grafana 4.6.2
 - prometheus 1.7.0

When using the template function, it does not work as expected to have a period in the character string to be expanded.

![image](https://user-images.githubusercontent.com/1995330/33198198-fd7b5c66-d12c-11e7-9938-06c7d10a7884.png)

expected:
 ```
http://hoge.jp/api/datasources/proxy/3/api/v1/query_range?query=probe_duration_seconds{instance="xxxx.jp",job="http-response-time"}&start=xxxxx&end=xxx&step=xxxxx
 ```

now:
```
http://hoge.jp/api/datasources/proxy/3/api/v1/query_range?query=probe_duration_seconds{instance="xxxx\\.jp",job="http-response-time"}&start=xxxxx&end=xxx&step=xxxxx
```

**Comment by torkelo** [comment]
your template variable must have multi value or all enabled. If that is the case Grafana expects you to use a regex label value operator (=~) in that case the template variable values needs to be regex escaped
