### ISSUE TITLE
[Feat req] Reference cell per column name rather then column number

### ISSUE THREAD

**Issue by theute** [grafana/grafana#9982]
* What Grafana version are you using?
 v 4.6.2
* What datasource are you using?
Prometheus, but same applies with 'default'
* What OS are you running grafana on?
Fedora

I wanted to create a link in a table and refer a value of the table.
The way it works today: I have to specify __cell_{{column number}}

But my Prometheus query may return more or less labels, so I can't know the column number at the time I write the dashboard.

I would need to refer to the cell by its column name.

(An alternative way would be to explicitly list the columns to keep from the query, at the moment it automatically gets all the columns)

Thanks

**Comment by daniellee** [comment]
This is a feature request for the old table panel. It is now possible in the new table panel to refer to a field by name or by column number when building a link.
