### ISSUE TITLE
grafana4.6.2 show Nan,but response data is right

### ISSUE THREAD

**Issue by fwb7014** [grafana/grafana#9987]
Grafana:  v4.6.2 
Datasource: CrateDB 0.5.1
Os: Centos7

some type of string columns show Nan,but response data is right,
![qq 20171125092851](https://user-images.githubusercontent.com/7226434/33226261-8b48a494-d1c4-11e7-92de-c5ee4a21235b.png)

![qq 20171125094017](https://user-images.githubusercontent.com/7226434/33226274-c6a59d80-d1c4-11e7-84ed-5114032e9138.png)

Thx a lot

**Comment by torkelo** [comment]
As you say the response is in strings, and not numbers.

Please find the crate datasource project on github and open the issue there. They might now if its a bug or the data format is lot supported by crate
