### ISSUE TITLE
show table datas more than real exist

### ISSUE THREAD

**Issue by fwb7014** [grafana/grafana#9989]
Grafana: v4.6.2
Datasource: Influxdb
Os: Centos7

I find a strange thing.I use grafana table chart, it show more datas than query directly in Influxdb.
I had delete data from Influxdb command before.
thx a log.

**Comment by torkelo** [comment]
Please use community site for questions.

Grafana does not show more data than influxdb returns. Maybe your query has a fill function?

**Comment by fwb7014** [comment]
Yes, your are right,.I had use the fill function.
thank you a lot
