### ISSUE TITLE
How to implement $_interval in simpleJson grafana?

### ISSUE THREAD

**Issue by RashmiSaravanan16** [grafana/grafana#9997]
Read before posting: 

 I need to aggregate value of simpleJson data based on time interval . may be 1h,6h,24h and display it on graph .  because now graph consist of every single data points which makes the graph clumsy

Please include this information:
- What Grafana version are you using : 4.6.1
- What datasource are you using SimpleJson
- What OS are you running grafana on windows and linux
- What did you do?
- What was the expected result aggregation data based on timeline

**Comment by torkelo** [comment]
the repo for simple datasource plugin is here https://github.com/grafana/simple-json-datasource

**Comment by RashmiSaravanan16** [comment]
can it be done with help $_interval .

because i need it to be dynamic .
if it needs to be changed in code then it will remain static

**Comment by torkelo** [comment]
well it might require an update the data source plugin

**Comment by RashmiSaravanan16** [comment]
Can you give some hint or few points how it can be done .
which file i need to look into

**Comment by daniellee** [comment]
@RashmiSaravanan16 The simple json datasource does not support this out of the box - you might have to fork it and make your own version (that's how lots of new plugin start off). 

There are a few ways to do this:
- you could return a list of intervals in your /search endpoint.
- you could add support for a Template Variable of type Interval. See [this Graphite dashboard](http://play.grafana.org/dashboard/db/graphite-templated-nested?panelId=2&fullscreen&edit&orgId=1&var-app=backend&var-server=backend_01&var-server=backend_02&var-interval=30m) for an example of that and note how `$interval` is used in the query.

To add support for an Interval template variable:
1. You need to add a way to pass that value from the query editor to the query class. One way is to add an input field in the [html partial](https://github.com/grafana/simple-json-datasource/blob/master/src/partials/query.editor.html) (and maybe set a default value for the field [here](https://github.com/grafana/simple-json-datasource/blob/master/src/query_ctrl.js#L11)).

2. You would have to use the variable in the query function in the [datasource.js class](https://github.com/grafana/simple-json-datasource/blob/master/src/datasource.js#L19) and pass it your backend.
